### ISSUE TITLE
Bubsy screen flashing between cutscenes

### ISSUE THREAD

**Issue by joepogo** [ekeeke/Genesis-Plus-GX#101]
In the game Bubsy, (the first one) usually a little cut-scene will play before the level starts and bubsy will say something. Everything seems ok until you get to level 9, the screen before the level starts (Dances with Woolies) is flashing when bubsy falls over. Seems like something is off for a second or two. 

I tested this on real sega genesis to verify if this is bug on actual genesis and the screen does not flash on real genesis. Also the mountains in the first level seem to have some sort of small distortion when scrolling. It almost looks like little bits of static here and there. Its hard to explain. 

I know you are one for accuracy eke so i am not sure if this some tiny bug but figured you might want to know. I tested this also on retroarch and gx wii version against real genesis version to verify. Everything seemed to be ok up until this point. Everything is ok afterwards, maybe small vdp glitch or something. 

Just to verify ive been testing this game since beginning. So far, im at level 9, screen only flashes before level 9 starts for some reason, 1-8 seem to be ok.

**Comment by ekeeke** [comment]
I think it's only the overscan area (surrounding border) which is flashing because it's quickly changing colors beween scene. You can verify that if you disable the borders in video settings, that "flashing" probably do not occur, right?

Also, have you tested GX Wii version and real Genesis with the same TV? it's very likely overscan is less visible on an old CRT.

**Comment by joepogo** [comment]
yes ive tested with same tv with emu and real genesis. Im now up to chapter 10. (beavery careful) the screen is also flashing on this too showing dark mountains in the background when it should be black with the words on the screen. 

Its not the border flashing, its the whole screen on the tv. When you get to chapter 10 (im currently at) its really bad.

**Comment by ekeeke** [comment]
Can you make a video?

**Comment by joepogo** [comment]
yea, ill try to get one from my phone and upload it here. 

This is weird, if i use cheatcodes to get there then its fine and the screen will not flash. WTH. If i do it manually then it does flash. Let me keep messing with this and get a savestate for you too, might be easier. Ill edit this soon with vid and/or savestate. This is extremely odd. I cant be crazy.  :)

**Comment by ekeeke** [comment]
Well, I think I know what causes this. It seems HINT on line 224 is being interrupted by VINT between a VDP CTRL port write and a VDP DATA port write so, when it returns from VINT, it ends up writing to wrong location (in this case, CRAM address 0x80 instead of VRAM 0x8002, thus corrupting background color).

It seems to be timing-related and probably happens in other emulators.

**Comment by joepogo** [comment]
I watched other videos of people doing playthroughs of this game to see what it does, and it does not flash for them. 

So have i stumbled inadvertently upon some bug i presume? So bubsy requires precise timing? I never would have thought that would bubsy haha. And yea good to see i am not crazy. :)

**Comment by ekeeke** [comment]
Can you test the attached boot.dol (inside zip), it should fix the flashing issue.

[boot.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/417881/boot.zip)

**Comment by joepogo** [comment]
yes, for sure. I just got to work but can try this out when I get home. 

It will be a little bit as I just got to work but will update this as soon as I do. Do I need to test other games as well for any timing issues since I assume its probably a precise timing fix, correct?

**Comment by ekeeke** [comment]
It should not affect other games as it is actually more correct timings but you never know. It's impossible to know which one could potentially be affected though so I won't bother...

**Comment by joepogo** [comment]
so you updated the file to have more accurate timing?

Is this going to be a commit here on site if the test passes? So far so good, testing now.

**Comment by joepogo** [comment]
Everything looks peachy swell that I can see eke! Great work, I see no issues on this end. How long do you think this bug has been around? I tested a few other games and I see nothing messed up. If you added more accurate timings then theres no telling what else this may fix.

**Comment by ekeeke** [comment]
I don't know, it's one of the things that depends on many things, DMA timings accuracy, VINT and HINT occurence timings accuracy, etc... so it could be that it appeared after changing some of these timings. It could also explain why it does not happen in other emulators, it's one of the case where having some timings off would hide the bug.

Anyway, the fix has been committed: https://github.com/ekeeke/Genesis-Plus-GX/commit/fa8929eb3d2f0173e85976177c46b623e2990f28
