### ISSUE TITLE
libretro question

### ISSUE THREAD

**Issue by TheRetroSnake** [ekeeke/Genesis-Plus-GX#102]
So, I've been trying to get the libretro version to work for few hours here. I got the code to compile, but RetroArch will either spit it out or just crash when trying to run the core. I want to use this for research and eventually to modify it to make it a viable option for programming tools for MD programming (higher level languages and API's don't really tickle my fancy, I find 68k ASM and VDP far easier to work with), but its kind of hard if I cant compile working code =$
I do have a 64-bit operating system, which I guess could be the reason why it does not work, but using the online updater I can acquire working core. So I am guessing its plausible to compile 32&64-bit version of it, but I do not know how. Would like a clarification about this!

**Comment by ekeeke** [comment]
I am compiling 32-bit windows version using mingw by running make -f Makefile.libretro, which gives me a dll. Replacing existing core dll in retroarch directory is working fine for me.  I can not help you with Retroarch support, you are better directly asking Retroarch devs on libretro repository as to why your compiled core would crash it.

**Comment by TheRetroSnake** [comment]
Thats about the same I am doing. Weird that the reference dll on this repo doesnt work either
