### ISSUE TITLE
(libretro) Changing system region at runtime doesn't work properly

### ISSUE THREAD

**Issue by arakerlu** [ekeeke/Genesis-Plus-GX#103]
If system region is changed from the core options menu when Retroarch is running and game is loaded, the change doesn't propagate properly. When you change from NTSC to PAL, or vice versa the frame rate doesn't get updated respectively, but seems to be fixed at the framerate of the region that was selected at the start. 

However, region locked games do notice the change and refuse/accept to run if the selected region is restricted/allowed.

**Comment by ekeeke** [comment]
Should be fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/b5c243664d7f04e024b99892de7b0a479359d8d0
