### ISSUE TITLE
Earthworm Jim 2 main menu issue

### ISSUE THREAD

**Issue by stubl** [ekeeke/Genesis-Plus-GX#106]
In Earthworm Jim 1, in the main menu when you start the game, you can choose between "press start" and "options" and the words will move if they are selected

however, the main menu in Earthworm Jim 2 does not do this in genesis-plus gx, and only "options" moves

On the snes the menu moves differently pressing up/down, so I dont believe this to be the normal behavior for the genesis version of Earthworm Jim 2

**Comment by ekeeke** [comment]
Have you tried in other genesis emulators ?

**Comment by stubl** [comment]
ah, I thought it was a bit obvious, but I thought I had found a bug anyway

anyway, the emulator is great and thanks for all your work put in on it!
