### ISSUE TITLE
forgotten worlds not working 

### ISSUE THREAD

**Issue by filevans** [ekeeke/Genesis-Plus-GX#107]
Both versions of forgotten worlds rev 00 and rev 01 both won't enter level and immediately display game over

Wii version 1.7.5 (IOS 58)

**Comment by ekeeke** [comment]
This is a very well-known bug in the game, not the emulator. This happens on real hardware aswell if you are using a 6-buttons controller. 

Set pad type to 3-buttons or auto in Genesis Plus GX controller settings.

**Comment by filevans** [comment]
I see sorry, I did a search before posting the issue and nothing came up about this on Google, so that's why I posted, thanks for your quick reply
