### ISSUE TITLE
RetroPac and license

### ISSUE THREAD

**Issue by Kivutar** [ekeeke/Genesis-Plus-GX#109]
Hello, I got a phone call from kisskissbankbank saying that the authors of Genesis-Plus-GX made a commercial agreement with RetroPac developers that give them the right to use the core in their product.

Is this true?

**Comment by twinaphex** [comment]
In case it isn't, please e-mail these guys from Kiss Kiss Bank so that they know about the circumstances surrounding the kickstarter -

jean-samuel.kriegk@kisskissbankbank.com

adrien.aumont@kisskissbankbank.com

**Comment by ekeeke** [comment]
Charles and I have been approached for commercial licensing of our code but no official agreement has been made offiicially and no rights have been given for anything at this point, there have been only some theoretical discussions through email at this point.

**Comment by twinaphex** [comment]
Hi there ekeeke,

could you e-mail these guys at kisskissbankbank about this? We can shut down their kickstarter then, they are operating off the assumption you and Charles gave your consent. Same with a Snes9x fork for which they *claim* they have permission for, which they don't.

**Comment by ekeeke** [comment]
To be more precise, we haven't signed any agreement, neither defined any licensing terms, only gave our conditions. I appreciated the fact they contacted us from the start (contrary to many others before them) and they seemed relatively serious about making things the right way but technically, until anything is officially settled (if this ever happens), they don't have any rights for commercial use of our code.

I will email kisskissbankbank and retropac representatives to clarify that situation and make sure everyone is well aware what is granted and what is not.

**Comment by twinaphex** [comment]
They are not serious at all, they are two highschool French college kids setting up a typical startup and ripping us off (Lakka/RetroArch) in the process when we have NEVER given our permission.

I have to say if you did went for it I would have been disappointed, and I think it would make the noncommercial license not worth the TXT file it's written in. But that's up to you I guess.

**Comment by Kivutar** [comment]
They contacted me some month ago, asking if it was OK to use RA and libretro cores in their project. I told them that there is already enough projects like this, and that they need to respect the licenses.

They started telling to all the newspapers around that they had our full approval to do their stuff. Then started using Snes9x in their distro (!!!)
When I complained about it, they switched to ARMSnes, which is also snes9x. They also claimed to have the approval of the ARMSnes authors, which are many. @rmaz the maintainer of ARMSnes said they never contacted him.

**Comment by robertanisko** [comment]
Hello!

Lead of the development team at [KissKissBankBank](https://github.com/KissKissBankBank) here.

It sometimes takes time for us to investigate and hear all involved parties in such cases, but it is necessary to make sure we take the right decision.

We've been following the complaints surrounding the Retropac project for a few days now, and I wanted to get in touch directly to confirm that the campaign has been cancelled. We gathered enough information to be fully convinced this was the right thing to do.

We're very supportive of open-source software, and committed to help protect it whenever we can or have to.

**Comment by twinaphex** [comment]
@robertanisko Thanks very much for doing the right thing! This is refreshing and very heartwarming to see!

**Comment by Kivutar** [comment]
Thank you!

**Comment by mudlord** [comment]
As someone who worked on some of the cores, I am glad this happened, it restored my faith in people doing the right thing.
