### ISSUE TITLE
Hei Tao 2 - Super Big 2 does not work with BIOS ON

### ISSUE THREAD

**Issue by sergiobenrocha2** [ekeeke/Genesis-Plus-GX#115]
This game is not working with System bootrom ON

Hei Tao 2 - Super Big 2 (China) (Unl)
crc 31449113

Same problem with:

Huan Le Tao Qi Shu - Smart Mouse (China) (Unl)
crc DECDF740

Is it related to #69 ?

**Comment by ekeeke** [comment]
Yes, it's an unlicensed game that probably does not work on consoles with TMSS... like many other unlicensed games made with unofficial devkits so don't waste your time testing them with BIOS ON, it's really not worth it.
