### ISSUE TITLE
segaCD skip BIOS option

### ISSUE THREAD

**Issue by bigboo3000** [ekeeke/Genesis-Plus-GX#117]
Hi
Would it be possible to add an option to skip segaCD bios and to boot directly to the game?

**Comment by ekeeke** [comment]
No, it's not possible, it's part of the boot processing code which initialize the hardware and loads the game from the disc.

**Comment by Kekun** [comment]
@bigboo3000 It's probably possible to write a custom and less verbose BIOS requiring no input from the user, but I have no idea how to do so.

**Comment by bigboo3000** [comment]
@kekun Yes it's probably the best option. There is already a hacked pcengine cd bios to make it invisible during the boot process.

I found this modification to the mega-cd bios:
http://assemblergames.com/l/threads/region-free-bios-for-mega-cd-version-2-00.54254/
but It's only a partial skip.
