### ISSUE TITLE
Six button pad not recognized in The Lion King (Gen/MD)

### ISSUE THREAD

**Issue by Silanda** [ekeeke/Genesis-Plus-GX#119]
Ok, this is a bit of a weird one. The game primarily uses three button controls, but will use X, Y, or Z to perform the maul/flip attack as adult Simba if a six button pad is attached. At least, that's what's supposed to happen (and does on actual hardware). Emulated, however, the extra buttons do nothing and the move has to be performed using the B then C combo.  

This was tested using the Libretro version of Genesis Plus GX on a recent nightly of Retroarch x64 for Windows. I can't rule out some kind of weird config issue, but other six button compatible games seem to work just fine. I've attached a savestate from an adult Simba level, though the file will probably need to be renamed as I was using my own ROM dump.

[LionKing.0D3D.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/646677/LionKing.0D3D.zip)

**Comment by ekeeke** [comment]
Tested using level select cheat code to access an adult Simba level and it worked just fine.

That game does not indicate 6-Button support in its ROM header so you will have to force it in Input settings (i.e Joypad AUTO will default to 3-button). You might also need to start the game with 6-button selected since the game might detect it on startup (i.e loading a state which was started with  3-button controller might not work with 6-button controller)

**Comment by Silanda** [comment]
I may be going blind, but there appear to be no such options using current builds of Retroarch. There's no option to select pad type in either the quick menu controller or options menus, nor in the main input menu. So, if that's the case and I'm not just missing something obvious, the libretro implementation is entirely reliant on the ROM header at the moment.

**Comment by Silanda** [comment]
Yep. Played around some more, and it seems as if the option to change pad mode is simply no longer present using recent versions of Retroarch. The option used to be there, but now you're just given the choice of Retropad or none.

**Comment by Silanda** [comment]
Nope, I'm wrong, sort of. I compiled my own build and it works just fine. The one included with Retroarch does not.

**Comment by ekeeke** [comment]
The core has always reported supported input device descriptors since quite some time so it's either an issue with retroarch or you not using it correctly (I know you need to first load the game for core input descriptors to be available).

**Comment by Silanda** [comment]
I'm pretty sure I'm using it correctly. The dll that I compiled from source works, the one provided by libretro as the latest release does not, so I'm assuming that something is wrong their end.

**Comment by ekeeke** [comment]
If by compiling from source you are talking about this repository, it might be related to [this](https://github.com/ekeeke/Genesis-Plus-GX/commit/ff2cb27f486d61cf824bf1bd525b28ff2dfd65eb) commit which has still not been backported into libretro repositories. It might indeed cause some issues with input descriptors.
