### ISSUE TITLE
[SMD] Addams Family, The (black screen)

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#126]
This game freezes into black screen after selecting "**START GAME**". **PASSWORD** menu works correctly.

**Comment by lab313ru** [comment]
After scanning "Addams Family, The.7z" this game appeared in RetroArch menu. After selecting it, and pressing Start at "START GAME" menu, it freezes.

**Comment by ekeeke** [comment]
Works fine for me in standalone Wii port of Genesis Plus GX, you must be using a bad (corrupted) ROM or something is wrong with tou retroarch setup.
