### ISSUE TITLE
[Libretro][Wii] Pixel white on screen

### ISSUE THREAD

**Issue by John3d** [ekeeke/Genesis-Plus-GX#130]
I have verified that in the latest versions of this core for wii, a fixed white pixel appears on the screen.

Occurs with all Megadrive and Mega CD games, in Master system does not appear.

![alien storm](https://cloud.githubusercontent.com/assets/21139065/25196283/7be832de-2540-11e7-836c-8cb5b3776cdb.png)

I could not do a capture with wii, but in this image I simulated where the pixel appears.

Thanks

**Comment by ekeeke** [comment]
This does not happen in windows version of retroarch so this is not a bug in the core, more likely a bug with the Wii driver in retroarch or some messed up retroarch settings. Also does not happen in my Wii port or any other non-libretro port so this has something to do with libretro/retroarch, not the core.
