### ISSUE TITLE
Sound bug on Sonic 3

### ISSUE THREAD

**Issue by molul** [ekeeke/Genesis-Plus-GX#136]
Actually, I don't know if this bug is fixable, as I've seen it on different emulators and different OS.

When playing Sonic 3, in zones like Ice Cap, when I get rings, the ring sound effect stops one of the music channels (resumes after a second or so).

While I don't remember this happening in the real Mega Drive, I don't think this is something would left unfixed to release. It's not a game breaker, but I'm curious about the reason behind it.

**Comment by ekeeke** [comment]
Surely not an emulation bug (FM channels don't get "accidentally" muted), just the way the sound engine is programmed in this game. The number of sound channels available in hardware is limited so it seems reasonable to replace ones momentarily for sound effects. This never occured to me in this game though so it must not be that much noticeable.
