### ISSUE TITLE
Linux SDL2 build (Sound error)

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#140]
```
  as_desired.freq     = SOUND_FREQUENCY;
  as_desired.format   = AUDIO_S16LSB;
  as_desired.channels = 2;
  as_desired.samples  = SOUND_SAMPLES_SIZE;
  as_desired.callback = sdl_sound_callback;

  if(SDL_OpenAudio(&as_desired, &as_obtained) == -1) {
    SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, "Error", "SDL Audio open failed", sdl_video.window);
    return 0;
  }

  if(as_desired.samples != as_obtained.samples) {
    SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, "Error", "SDL Audio wrong setup", sdl_video.window);
    return 0;
  }
```
Second error message happens in Linux Mint 18.1.

as_desired.samples = 2048
as_obtained.samples = 1024

**Comment by ekeeke** [comment]
SDL build is not maintained and I personally do not use Linux

**Comment by lab313ru** [comment]
Anyway, is it required that sound samples size must be equal to 2048?

**Comment by ekeeke** [comment]
Retroarch uses the libretro port, which has nothing to do with this code.

Again, SDL port is not maintained and is not very stable or well tested, it shouldn't really be used for anything besides basic documentation on how to interface with the emulator.

**Comment by ekeeke** [comment]
No idea. Probably not, 2048 is the size reserved for sound buffer in bytes.
null
