### ISSUE TITLE
cram, tiles viewing

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#141]
Question is: I'm working on making GUI for GPGX, and one of the windows is VDP viewer.
I tried to use `cram` that is declared in "vdp_ctrl.h", to display palette, but it seems, that colors in it are not the same, that CRAM itself contains.

Can you point me to right direction? What data I can use do display tiles, cram?

**Comment by ekeeke** [comment]
16-bit port written data is packed to 9-bit into cram, see https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/vdp_ctrl.c#L2177
