### ISSUE TITLE
Build errors on x86

### ISSUE THREAD

**Issue by obsidianspider** [ekeeke/Genesis-Plus-GX#142]
I received errors while I was trying to manually build Genesis-Plus-GX on my x86 installation of RetroPie running on GalliumOS 2.1. 

Prior versions worked fine, but yesterday it was unsuccessful. [I put the log on Pastebin](https://pastebin.com/uLX52zBh). I'm not sure if/what may have changed since I updated a few months ago.

**Comment by ekeeke** [comment]
I assume you are talking about the libretro version.
From which repository are you compiling?
It compiles just fine for x86.
The error message seems to indicate you were using the libretro fork repository that twinaphex broke yesterday for a few hours.
https://github.com/libretro/Genesis-Plus-GX/commit/5e2ed42295c062e43541381f705fe7645271962c
