### ISSUE TITLE
blip_buf code mistakes

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#143]
`blip_buf.c (blip_add_delta)`:
```
short const* in  = bl_step [phase];
```
where `bl_step` is defined as:
```
static short const bl_step [phase_count + 1] [half_width] =
```
and:
```
enum { half_width  = 8 };
```
After that at line 496 the next magic happens:
```
out = in[0]*delta_l + in[half_width+0]*delta;
```
so `in[half_width+0]` will point over dimension of in array!

This situation will happen in every line, where `half_width + x` is used.

**Comment by lab313ru** [comment]
```short const* rev = bl_step [phase_count - phase];```
Usage of `rev` has the same mistake.

**Comment by ekeeke** [comment]
Probably not the best looking code (but again this is a third party library which a quite complex implementation) but there is nothing wrong here.

in[half_width+x] with 0<=x<=7 actually corresponds to next line of the bl_step table (next phase entries)

see how phase is calculated, it can be between 0 and (phase_count - 1) while bl_step table has (phase_count + 1) * lines

Again, this code is actively used for audio rendering so if there was something wrong here, there would have been quite noticeable issues.

**Comment by lab313ru** [comment]
I mean in[half_width+0]. half_width == 8, and in dimension is 8 totally. So...

**Comment by ekeeke** [comment]
I get it but in is a pointer, not a table so in + 8 actually points to the next line in the table

It could probably have been optimized by using two pointers:

```
in1 =  bl_step [phase];
in2 =  bl_step [phase+1];

```
then
`
out = in1[0]*delta_l + in2[0]*delta;
...
`

**Comment by lab313ru** [comment]
Oh, now I understand)

**Comment by ekeeke** [comment]
Here is some documentation on C pointers

https://www.tutorialspoint.com/cprogramming/c_pointers.htm

**Comment by lab313ru** [comment]
I thought that in case of multidimensional arrays, it should not point to the next dimension.

**Comment by ekeeke** [comment]
Multidimensional array is just a view of memory for the compiler. 
Data are still ordered sequentially in memory, like a big one-dimension array.
