### ISSUE TITLE
libretro joypads code mistakes

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#144]
`libretro.c (retro_set_controller_port_device)`:
Such lines will lead to constant comparison result every time (to false):
```
input.system[0] >= RETRO_DEVICE_XXX
```
or (to true):
```
input.system[0] <= RETRO_DEVICE_XXX
```

Because:
1) input.system[0] has unsigned char size;
2) Such device lines `#define RETRO_DEVICE_MDPAD_3B_WAYPLAY     RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_JOYPAD, 3)` will be expanded to: `(((3 + 1) << 8) | 1)`
3) (2) will be greater than one byte.

**Comment by ekeeke** [comment]
Indeed, I noticed this recently as it generated warnings in a build log.

RETRO_DEVICE_xxx should actually be replaced by SYSTEM_xxx equivalents
