### ISSUE TITLE
retro_cheat_set code mistakes

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#145]
`libretro.c (retro_cheat_set)`:
```
void retro_cheat_set(unsigned index, bool enabled, const char *code)
{
	char codeCopy[256];
	char *buff;
   
   /* Avoid crashing when giving empty input */
   if (code=='\0') return;
```
You're comparing const pointer against zero char, not the entered code itself. Is it `NULL` should be here, or `*code`?

**Comment by ekeeke** [comment]
The value of '\0' is 0 which correpsond to NULL pointer generally so that check is fine actually, but not necessarely the one wanted  by the original coder.

Should be

```
/* Avoid crashing when giving no input */
   if (code==NULL) return;
```

then
```

/* Avoid crashing when giving empty input */
   if (*code=='\0') return;
```
