### ISSUE TITLE
sms_ntsc / md_ntsc code optimization

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#147]
`sms_ntsc_impl.h (gen_kernel)`, `md_ntsc_impl.h (gen_kernel)`:
```
while ( alignment_count > 1 && --alignment_remain );
```
While `#define alignment_count 3` (for sms)
And `#define alignment_count 2` (for md)
So, first part of the comparison will be every time true.

**Comment by ekeeke** [comment]
Not a mistake, a missing opportunity for optimization maybe but keep in mind this is a 3rd party library that was meant to be configurable so it could explain why this was done like this.

I honestly never reviewed this code and barely understand what it does, there are probably many other optimizations to be done.
