### ISSUE TITLE
load_rom.c code misprint?

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#148]
`load_rom.c (load_rom)`:
```
    /* auto-detect 512 byte extra header */
    if (memcmp((char *)(cart.rom + 0x100), "SEGA", 4) && ((size / 512) & 1) && !(size % 512))
```
Is this memcmp compare correct? It should be `!memcmp`, doesn't it?

**Comment by ekeeke** [comment]
No,  memcp() returns value != 0 if buffer contents are not equal .

Here we detect that "SEGA" string is NOT present at cart.rom + 0x100, i.e that there is an extra header before normal Genesis header.

I appreciate you are reviewing the whole codebase suddenly but don't you think we would have serious problem loading file in the emulator if there was an error here?

**Comment by lab313ru** [comment]
Sure.:)
