### ISSUE TITLE
Separate displaying for planes

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#149]
Is it possible to add 'triggers' to switch off/on planes to display (debug purposes)?
As I found in your code, you're mixing them every line, so for now I can't do that.

**Comment by ekeeke** [comment]
render_bg and render_obj are function pointers so you could have specific functions for debugging 

I won't do it myself though since I have personally no need , interest or time for that but you are free to submit a pull request
