### ISSUE TITLE
Some comments are confusing

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#150]
vdp_render.c:L1638: `/* Plane A line buffer */` but code is related to Window plane.
vdp_render.c:L1828: `/* Plane A line buffer */` but code is related to Window plane.
vdp_render.c:L1980: `/* Plane A line buffer */` but code is related to Window plane.
vdp_render.c:L2171: `/* Plane A line buffer */` but code is related to Window plane.

**Comment by lab313ru** [comment]
These (and some other comments) make me confused, so I can't find code which draws Plane B and merges it with Plane A.

**Comment by lab313ru** [comment]
Tell me, please, about `uint8 linebuf[2][0x200];`
What data it contains, and at what offsets.

For example, I can't find usage of `&linebuf[0][0x00]`, but only `&linebuf[0][0x10];`, `&linebuf[1][0x20];`, etc.

**Comment by ekeeke** [comment]
Plane A and Window plane are shared on a line so they are using same line buffer in the emulator (which is named Plane A line buffer in comments for convenience).

linebuf[x] contains the various planes buffer (first not merged then merged).
offset is used to handle fine horizontal scrolling where 16-pixels columns on the left and on the right of the screen can be partially displayed.
active display starts at offset 0x20.

Now, I am afraid I don't really have time to help you with this so this will likely be my last answer on that topic, the code is here for you to learn and study, providing you have minimal knowledge of genesis hardware and are good at following and understanding C code.

This is also not really the place for discussing about what the code is doing (this is an issue report interface and I receive an email every time someone posts here) so please don't abuse it, thanks.

**Comment by ekeeke** [comment]
Plane A and Window plane are shared on a line so they are using same line buffer in the emulator (which is named Plane A line buffer in comments for convenience).

linebuf[x] contains the various planes buffer (first not merged then merged).
offset is used to handle fine horizontal scrolling where 16-pixels columns on the left and on the right of the screen can be partially displayed.
active display starts at offset 0x20.

Now, I am afraid I don't really have time to help you with this so this will likely be my last answer on that topic, the code is here for you to learn and study, providing you have minimal knowledge of genesis hardware and are good at following and understanding C code.

This is also not really the place for discussing about what the code is doing (this is an issue report interface and I receive an email every time someone posts here) so please don't abuse it, thanks.
