### ISSUE TITLE
Bunch of code mistakes

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#151]
1) [cdd.c:L659](https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/cd_hw/cdd.c#L659). In case of `cdd.sectorSize` is zero, divide by zero will occur;
2) [gfx.c:L610](https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/cd_hw/gfx.c#L610). Switch doesn't contain `default` section, so `uint32 mask;` in some cases may contain a garbage;
3) [graphic_board.c:L66](https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/input_hw/graphic_board.c#L66). The same situation;
4) Strange situation with [md_ntsc_impl.h:L249](https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/ntsc/md_ntsc_impl.h#L249). [sms_ntsc_impl.h:L249](https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/ntsc/sms_ntsc_impl.h#L249). Value to `n` is assigned, but in a loop below it becomes reused as the new var, and [upper bound of the loop check 1](https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/ntsc/md_ntsc_impl.h#L266), [upper bound of the loop check 2](https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/ntsc/sms_ntsc_impl.h#L266) now becomes strange.

**Comment by ekeeke** [comment]
Those are not mistakes, what you are describing in 1, 2 and 3 can simply not happen.

Now please stop bothering me with this useless code reviewing (probably based on some paranoiac compiler warnings setup) , it becomes boring and annoying. Everything is working fine with this code.
