### ISSUE TITLE
add support for CHD format for mega-cd

### ISSUE THREAD

**Issue by bigboo3000** [ekeeke/Genesis-Plus-GX#152]
Hi

CHD support have just been added in redream (dc emulator) and in the mednafen saturn core of libretro using this library:
https://github.com/rtissera/libchdr

Could you consider adding CHD support in Genesis-Plus-GX?

**Comment by ekeeke** [comment]
Nope.

**Comment by ekeeke** [comment]
Actually, I changed my mind after reading a bit more about CHD and learning how it worked. Also see https://github.com/libretro/Genesis-Plus-GX/issues/93

**Comment by KMFDManic** [comment]
I have tested Mednafen implementation of CHD support, notably PCE-Fast & PCFX.  Thus far, I am impressed with the results.  It is only natural, as a given, that integrating support for this into Genesis Plus GX will be a very nice step forward!  I look forward to seeing what you and rtissera pull off, in this case.  Fantastic work on Genesis Plus GX, by the way.  I check frequently for any and all commits, being this is one of my absolute favorite Libretro Cores.

**Comment by ekeeke** [comment]
Added in https://github.com/ekeeke/Genesis-Plus-GX/commit/05dc8faa0419869438fc1a3c2b1741e87fea0178
