### ISSUE TITLE
Larger image dimensions for snaps? 

### ISSUE THREAD

**Issue by unihandroll** [ekeeke/Genesis-Plus-GX#153]
I'd like to be able to view Genesis/MegaDrive box art instead of cartridge labels.  Would it be possible to allow for a larger "snaps" window?  And in the process, remove the static cart image, or change them to blank png's?  There definitely appears to be significant space next the browser/list for images with larger dimensions.

I suppose this isn't a super important issue.  But I'd sure appreciate it. 👍

**Comment by ekeeke** [comment]
I would rather have proper box art display instead as already listed here
https://bitbucket.org/eke/genesis-plus-gx/issues/84/box-covers
