### ISSUE TITLE
Skitchin' missing clouds sometimes

### ISSUE THREAD

**Issue by Pat86** [ekeeke/Genesis-Plus-GX#154]
I'm not 100% sure on this one, but i highly doubt, the game had "dynamic" weather back then.
Sometimes when you start the first race, there are no clouds in the sky. I just tested it on real hardware a couple of times and there were clouds everytime ...
![2017-08-02 11_43_05-store](https://user-images.githubusercontent.com/20128108/28868107-b128f0de-7778-11e7-95fe-c57551e700ff.png)

**Comment by ekeeke** [comment]
I also tested it back then on real hardware and I remember there were some times when there was no cloud. Looks like random weather or time, nothing much exceptionam

**Comment by ekeeke** [comment]
Just to be sure; this was just taken from my VA0 MD2 after a single soft reset. Same thing happens on  my VA4 MD1.

![20170806_154345](https://user-images.githufbusercontent.com/717091/29003899-81829322-7abf-11e7-8547-8f1026b851b6.jpg)
