### ISSUE TITLE
Techno clash and clicks in ym2612

### ISSUE THREAD

**Issue by dinkc64** [ekeeke/Genesis-Plus-GX#156]
Reproduce:
start Techno Clash, get past that talking stuff and walk upwards toward one of the columns, now use your fireball shot (B button) and shoot at a column - sometimes you'll have to do this several times, some shots will have a nasty click in them, sort of like a overflow in the sample.  img from Audacity https://s27.postimg.org/ayikng2hf/technoclashclick.png
Doesn't happen on hardware or other emulators, any ideas?

**Comment by dinkc64** [comment]
I think also, Power Drive titlescreen music, when the snares start also causes these clicks, I'm not sure if this one is a different cause though (seems like dac? I'm not 100% sure).

**Comment by ekeeke** [comment]
What port are you using ? I am unable to reproduce any of these clicks in my Wii port in any of these games. Try to record videos so I can see/hear what I should  be looking for exactly.

**Comment by dinkc64** [comment]
This can be closed, I found the issue - sorry for wasting your time!
