### ISSUE TITLE
[libretro] makefile needs updating for ARM non-RPI

### ISSUE THREAD

**Issue by zach-morris** [ekeeke/Genesis-Plus-GX#158]
I was having an issue with genesis_plus_gx core after installing Lakka-LibreELEC on an S905 device.  I found that after loading a game, the system would freeze particularly when the screen has to scroll with the game.

After some digging, it looks like the core needs to be compiled with -DALIGN_LONG and -DALIGN_DWORD to resolve this issue.  Found this info [here](https://forums.libretro.com/t/genesis-plus-gx/41/4?u=zachmorris).

 I assume the issue would be similar on ARM chip boxes that aren't RPi, like the ODROID, although I can't confirm since I don't have one.

**Comment by ekeeke** [comment]
This is correct (although -DALIGN_WORD does nothing in that emulator and could be ignored) but this would be under the responsibility of libretro or lakka devs to maintain/update platform specific Makefiles, not mine.

**Comment by zach-morris** [comment]
OK, thanks for the response.  I'll write an issue there
