### ISSUE TITLE
SFX bug? - Montezuma's Revenge SMS

### ISSUE THREAD

**Issue by SimpleTease** [ekeeke/Genesis-Plus-GX#164]
Hi, when Joe is walking around, the walking "crunching noise" often doesn't play correct - only sometimes you hear it fully. Same thing happens when landing (after jumping) - it often doesn't make the "hard landing" noise sound correct. Comes out muffled or muted or something; not the loud gritty hit.

Other SMS emulators don't do this; haven't checked real hardware. Thanks for considering this problem.

**Comment by ekeeke** [comment]
I doubt this is a bug considering how simple the PSG chip works. Most likely this is some filtered sound effect that sounds louder in other emulators.

Here is a real hardware footage: https://m.youtube.com/watch?v=hxmoBfVHiSE

I don't hear any noise when walking or jumping so I'm not sure what I should listen to exactly.

**Comment by SimpleTease** [comment]
https://m.youtube.com/watch?v=hxmoBfVHiSE
They talk a lot so it's hard to locate a good spot. Around 07:26 mark, you can hear the walking. Sounds like "tak tak tak". Filtered like I think you mentioned.

https://www.youtube.com/watch?v=hxmoBfVHiSE
Around 01:23, you can hear alternate walking sound. "TAK TAK TAK". Painful sharp and loud. Noticeable.

With Genesis Plus GX, start a new game. Choose level 1. Don't go down but walk right into the wall. Then keep walking right. Loudness volume keeps changing: "TAK tak tak tak TAK TAK tak tak TAK tak tak tak tak TAK". Mostly soft but sometimes loud. Based on those 2 videos, it appears it always should be consistently soft or consistently loud but not switching between both sound levels.

I think that's the important part I'm trying to describe. LOUD soft soft soft LOUD soft soft LOUD LOUD soft soft. When jumping up/down (00:57-00:59 on video2), it does this also sometimes with GX -- LOUD LOUD LOUD LOUD soft soft soft soft soft LOUD soft LOUD LOUD.

I should mention using Retroarch pc with no external audio, video filters. So maybe the frontend is playing tricks too but I'm unsure. I had to crank up the speaker volume to hear the sfx sometimes when it plays quietly.

Hope this makes sense. :o
Thanks for looking into it though!

**Comment by ekeeke** [comment]
[quote]I think that's the important part I'm trying to describe. LOUD soft soft soft LOUD soft soft LOUD LOUD soft soft. When jumping up/down (00:57-00:59 on video2), it does this also sometimes with GX -- LOUD LOUD LOUD LOUD soft soft soft soft soft LOUD soft LOUD LOUD.
[/quote]

Sorry but I don't understand what you mean: do you mean you hear similar variable sfx loudness on that real hardware video but not "exactly" the same sequence in emulator? In that case, this is very likely randomly generated and emulator is correct.

Anyway, from what you are hearing in that video, there are actually two sound effects on real hardware: one that is soft (which you mentionned as being incorrectly "muffled" in your initial issue report) and one that is loud? I will need to check what the game is doing exactly when I get some time but there are chances what you get on emulator is what happens on real hardware.

**Comment by ekeeke** [comment]
[quote]I think that's the important part I'm trying to describe. LOUD soft soft soft LOUD soft soft LOUD LOUD soft soft. When jumping up/down (00:57-00:59 on video2), it does this also sometimes with GX -- LOUD LOUD LOUD LOUD soft soft soft soft soft LOUD soft LOUD LOUD.
[/quote]

Sorry but I don't understand what you mean: do you mean you hear similar variable sfx loudness on that real hardware video but not "exactly" the same sequence in emulator? In that case, this is very likely randomly generated and emulator is correct.

Anyway, from what you are hearing in that video, there are actually two sound effects on real hardware: one that is soft (which you mentionned as being incorrectly "muffled" in your initial issue report) and one that is loud? I will need to check what the game is doing exactly when I get some time but there are chances what you get on emulator is what happens on real hardware.

**Comment by ekeeke** [comment]
Also I think something went wrong with your 2nd video link copypasting, it's the same as the one I posted.

**Comment by SimpleTease** [comment]
Found out retroarch can make movies...

Small 2MB mkv sample
http://s000.tinyupload.com/index.php?file_id=06202662435796645453

At 00:36, Joe does 10 jumps. 1,2,3(-),4,5(-),6(-),7(-),8(-),9,10
#1,2,4,9,10 = what I normally think it should sound like (with "right" pitch like in real hardware video; only Genesis Plus GX emulator seems to get this waveform "correct". No complaints.)
#3,5,6,7,8 = questionable landing; don't hear this short tiny tinny sound in real video or other emulators. To me it's like a "misfire" or stopped really early.

00:29 = walking sound
~ Around 00:33, 00:35, I can hear the "normal" sound briefly 2-3 times. Otherwise it's mostly the "bad" jumping effect


Was watching this video too. This seems "okay" to me everywhere, like other original real hardware video.
https://www.youtube.com/watch?v=JXYm5Vy6EJM


And I also believe you that Plus GX might already be true correct response and it's just some random game "feature" that bugs me. ;)

But thanks for responding. If emulator is generating the right audio playback, then I'm good with it. :)

**Comment by ekeeke** [comment]
There was actually indeed a bug with PSG noise: it was sometime accidentally muted when the game modified or reseted noise frequency.

This is now fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/31906b20cfcf48f3f132ecc365f4c8793f091024
