### ISSUE TITLE
Marvel Land freeze during attract mode

### ISSUE THREAD

**Issue by Tasosgemah** [ekeeke/Genesis-Plus-GX#165]
I found this obscure bug in Marvel Land while playing in RetroArch/Genesis Plus GX core. The game has a an attract/demo mode that shows the first level. But when it finishes (after the character dies) the game freezes into a black screen.

**Comment by joepogo** [comment]
Can confirm. Just tested this out and it indeed black screens after the character dies in attract mode. I am usually pretty good at catching bugs for eke in this emulator :P, but good catch on this one!!

**Comment by joepogo** [comment]
Hey Eke, do you see what we see or are we just crazy. :P I tested this again with different dumps and with the same result.

**Comment by ekeeke** [comment]
Chill out. I am not able to see anything because I can simply not test or fix anything atm. I am still on holidays with only email access so I can be bothered by github notifications once per day. I will have a look when I come back, don't worry.

**Comment by ekeeke** [comment]
Fixed by https://github.com/ekeeke/Genesis-Plus-GX/commit/527fd6ecd88109a22beb88d0defb33607a256811
