### ISSUE TITLE
WiiU Gamepad Support 

### ISSUE THREAD

**Issue by Ploggy** [ekeeke/Genesis-Plus-GX#168]
Could you compile the Wii Version of your GensplusGX with Fix94's new WiiU Gamepad Patch?

> This is only usable with a sepcial patched fw.img and homebrew injected into a wiiu vc title, details on the patches are below.
> The usage is quite simple, call WiiDRC_Init on boot and after that call WiiDRC_ScanPads every time you update your pad inputs.
> See the "demo" folder for an example on how to use it in a bit more detail.

https://github.com/FIX94/libwiidrc

Thanks :)

**Comment by ekeeke** [comment]
What's the problem with current WiiU Pro controller support ? Or is or something else ?

**Comment by Ploggy** [comment]
This is for WiiU Gamepad Control support not WiiU Pro, this would allow us to play your Emulator off screen WITH the Gamepad buttons too :)

**Comment by ekeeke** [comment]
I see. It does not seem much complicated indeed to support it so I guess I could have a look when I got some time. This would be 100% untested though since I don't have a WiiU.

**Comment by Ploggy** [comment]
That's fine. I'll be happy to test it for you :)
The hope is to find other Wii Emudevs and see if they can re-compile their Emulators with this patch too.
It's too good a feature imo.

Thanks :)

**Comment by Ploggy** [comment]
Did you get a chance to look into the WiiU Gamepad patch?

**Comment by ekeeke** [comment]
Yes but it requires a little more work to get it interfacing with the emulator than just copying some code.

PS: I changed the title as GensPlusGX is not a thing, that emulator has nothing to do with Gens or Gens Plus emulator despite people insisting in naming it like that ;-)

**Comment by Ploggy** [comment]
:P No probs. I'll be here waiting patiently.. :)

**Comment by tatundria** [comment]
Please, if you can recompile it with liwiidrc, that would be great! I can always test it for you. Thanks!

**Comment by wicksand420** [comment]
I'm a tester also, just let me know, or ploggy can too.

**Comment by Ploggy** [comment]
@ekeeke Unrelated but thought I should bring it to your attention :)
Fix94 has managed to unlock the full WiiU CPU Clock Speed in Wiimode, so all Emulators for the Wii now run at the full WiiU Clock Speed.

Not64 and WiiSX has had a Major boost in speed :-)

**Comment by tatundria** [comment]
Any news on this?

**Comment by ekeeke** [comment]
Yes, I've made a WiiU Gamepad icon to display in the emulator controller settings.

Sorry but this is quite low priority to me and obviously not as simple as "recompiling" with a library, as said above, it needs some work to be properly integrated and my coding time is very limited.

**Comment by wicksand420** [comment]
Thanks ekeeke, I love this emulator, and it is worth waiting for gamepad support, Glad to see people still working this, I'm sure if you need any help with the libwiidrc fix94 will help you out.

**Comment by ekeeke** [comment]
Please give this test version a try and report any encountered issues.

In particular, check (in following order) that: 

1. gamepad is detected and works fine in menu
2. gamepad is automatically assigned to player 1 by default ( in controller settings menu, there should be a new gamepad icon when you select player 1 controller configuration)
3. all gamepad buttons (except SYNC and HOME) can be remapped to emulated device buttons
4. you can still loop between detected controllers when assigning controller to players in controller settings menu
5. ZL/L/ZR/R buttons work let you fastscroll through games in ROM browser 
6. gamepad works fine when emulating game

[wiiu_gamepad_test1.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/1363315/wiiu_gamepad_test1.zip)

**Comment by JafuOleanders** [comment]
Hello EkeEke, sorry to jump in, I had been waiting for such a patch, and by chance she you have just done this- and so i gave it a try. Dpad nor Analog directions seem to work on the WiiUgamepad with your Test1.. however all other buttons work. If using a wiimote to get into a game, all buttons still work on the gamepad, and movement works with Analog only. I'm happy to say everything else works just fine though.

**Comment by Ploggy** [comment]
1. gamepad is detected and works fine in menu
Gamepad is detected but cant navigate the menu (button presses are recognised)
2. gamepad is automatically assigned to player 1 by default ( in controller settings menu, there should be a new gamepad icon when you select player 1 controller configuration)
Yes.
3. all gamepad buttons (except UP/DOWN/LEFT/RIGHT, SYNC and HOME) can be remapped to emulated device buttons
Yes
4. you can still loop between detected controllers when assigning controller to players in controller settings menu
Yes, Managed to cycle between Wiimote and Gamepad correctly :)
5. ZL/L/ZR/R buttons let you scroll through games list in ROM browser
ZL/L/ZR/R Does let you control the Rom list :-)
6. gamepad works fine when emulating game
Yes, Gamepad and Buttons work fine. (analog only controls character, dpad doesn't)
7. HOME button lets you you return to menu
Yes, Home Button works as expected.
8. POWER OFF button shutdowns the console (in-game or in menu)
Yes, Power Button works as expected :)

Thanks Ekeeke, Its almost perfect just cant navigate the menus :P

**Comment by ekeeke** [comment]
Thanks for the detailled report.

I indeed forgot handling dpad buttons, this should work better in test2 .dol below

[wiiu_gamepad_test2.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/1363872/wiiu_gamepad_test2.zip)

**Comment by Ploggy** [comment]
Thanks Ekeeke The new version fixed the Problem :) the Emulator Runs perfectly with the Gamepad now.

**Comment by wicksand420** [comment]
Thanks ekeeke, you are awesome!!!

**Comment by JafuOleanders** [comment]
Beautiful, You were sure on top of that EkeEke! Now to enjoy beautiful WiiU Sega retro goodness.

**Comment by ekeeke** [comment]
Added by https://github.com/ekeeke/Genesis-Plus-GX/commit/5c7eb1a55dc4a18ca02086ae54cb8826e321588b

**Comment by OOKAMIFR** [comment]
hello
i was looking for a version compatible with gamepad and wonder if you have the full pack , not the test dol only

i want to create a wup install to make it working on my wii u gamepad

many thanks for your help and time

**Comment by Ploggy** [comment]
> Hello Thanks for your reply
> 
> I see no release available on this git and all version I saw was not compatible with Gamepad
> 
> If you have a link for the larest release ? Or maybe you have wup package ready for the Wii U ?
> 
> Many thanks for your help and time

I've made a wup package of Genesis Plus GX with WiiU Gamepad support if you want it.  Are you the same OOKAMIFR on GBAtemp? 
if so msg me there I'll sort you out ;)
