### ISSUE TITLE
High-accuracy YM3438 emulation

### ISSUE THREAD

**Issue by nukeykt** [ekeeke/Genesis-Plus-GX#172]
Hi. I'm working on the high-accuracy YM3438 emulator based on the YM3438 die shot analysis. Emulation is complete now, but possibly there are some small bugs left. It's available at https://github.com/nukeykt/Nuked-OPN2
Are you interested in integrating this core to the emulator? I'm fine to use it under project's non commercial license.

**Comment by ekeeke** [comment]
Looks great, thanks for the offer, this could actually be integrated as an alternative to MAME core for people to test it out and report eventual bugs (I won't have the time to debug them however).

It seems like you already integrated it in a Genesis Plus GX fork, could you maybe make it as an optionnal core (there are already configurable function pointers for FW writes/updates) ?

**Comment by ekeeke** [comment]
Added in https://github.com/ekeeke/Genesis-Plus-GX/pull/173
