### ISSUE TITLE
Mono option in the worng place (cosmetic).

### ISSUE THREAD

**Issue by James-F2** [ekeeke/Genesis-Plus-GX#180]
https://github.com/ekeeke/Genesis-Plus-GX/blob/296b3c7a086e5589586906a99b643fa6154a62d2/libretro/libretro.c#L1676

Hi ekeeke.
This is not really an issue but more a minor cosmetic annoyance.

The Mono/Stereo switch is sandwiched between Lowpass and Lowpass-%.
Maybe place it before Lowpass to keep Lowpass and Lowpass-% one after the other?

Thanks

**Comment by ekeeke** [comment]
Done in https://github.com/ekeeke/Genesis-Plus-GX/commit/388f73d658c7564d363a1f48f49b5e3fcecfdeb4
