### ISSUE TITLE
Problem compiling GPGX

### ISSUE THREAD

**Issue by James-F2** [ekeeke/Genesis-Plus-GX#186]
Hi ekeeke.

I've learned to compile using this guide for quicker testing:
https://bot.libretro.com/docs/compilation/windows/

It seems that there is something in the code that shown and ERROR during compilation using the method pointed above, but it is already fixed in the libretro branch and it compiles well there.
Here is the fix:
https://github.com/libretro/Genesis-Plus-GX/pull/113

I have managed to manually change these lines in Notepad++ and only then the main trunk GPGX compiled.

Thanks!

**Comment by ekeeke** [comment]
I know, yes, this is only when trying to build with buked ym3438 core. Libretro commits usually get merged after a while.
