### ISSUE TITLE
4:3 aspect ratio option

### ISSUE THREAD

**Issue by eugene-s-nesdev** [ekeeke/Genesis-Plus-GX#191]
Hi, genesis-plus-gx devs.

Can you add classic 4:3 core-provided display aspect ratio to libretro port?
This option done in fceumm core, it has "NTSC PAR", "PAL PAR" and "4:3"

**Comment by ekeeke** [comment]
No, Genesis is different from the NES and NTSC PAR is approximately 1.31 which is close enough to 4:3 but more accurate (the exact value takes the actual dot clock and applies it to width/height ratio).

If you don't like accurate aspect ratio provided by the core, you can always force whatever aspect ratio you want with retroarch, but it's not the role of the core to provide made up aspect ratios.
