### ISSUE TITLE
USB-HID support would make sense

### ISSUE THREAD

**Issue by eleriaqueen** [ekeeke/Genesis-Plus-GX#192]
Hello,
Please consider adding support for USB-HID controllers, even if it ends up way at the bottom of your ToDo list. It would make sense.

Thanks.

**Comment by ekeeke** [comment]
The thing is, unless this is already supported by a library (either libogc or a third-party library) that can be used by emulators, I have no idea how to implement this kind of support as this is way too much low-level for me.

**Comment by ekeeke** [comment]
Duplicate of #321
