### ISSUE TITLE
Broken save state compatibility again

### ISSUE THREAD

**Issue by clobber** [ekeeke/Genesis-Plus-GX#194]
Commit https://github.com/ekeeke/Genesis-Plus-GX/commit/9bb64c47f969dffe44c4bafe1f2651b88652ab36 broke compatibility with previous Genesis/Mega Drive save states. Is it possible to fix this?

**Comment by ekeeke** [comment]
Nope, this is inherent to core changes

**Comment by clobber** [comment]
Nah I don’t buy that. Mupen64Plus has undergone major refactoring for over a year now and they have managed to keep save state compatibility. It’d be nice if you gave a little more care in that regard. I notice you bend over backwards for any other request, so why not save states.

**Comment by OptimalJew** [comment]
@clobber I don't think it's reasonable to expect states to work between versions where significant changes may have occurred. If you're using states for archival purposes, I would recommend keeping a copy of the core you used at the time. For regular gameplay, I wouldn't update until you're done with that playthrough, or have an SRM to load.

**Comment by KMFDManic** [comment]
@ekeeke does a hell of a lot for the emulation scene.  I appreciate it all.  But, with change comes compromise, unfortunately.

**Comment by clobber** [comment]
@OptimalJew @KMFDManic T-thanks for the valuable input! I'll take that under advisement! Also @Oggom piss off with the 'thumbs down emoji', coward.

Ekeeke you've fallen into the perpetual beta cycle trap and stopped making releases. I guess that's what happens when you've given up on your own frontend and let others downstream become the 'de facto' frontend.


It's clear you don't give a shit about save state compatibility, so the least you could do is conform to the API and update your own [state versioning](https://github.com/ekeeke/Genesis-Plus-GX/blob/8f597825b79fd24f8d4dad290f80cabd869e5685/core/state.c#L55) so the emulator doesn't dutifully load a state that crashes it. That's fucking sloppy, man.

**Comment by clobber** [comment]
Also I see you clowns copy pasting in your 'anonymous' 4chan thread. Keep talking shit, literal nobodies.

http://boards.4chan.org/vg/thread/193785087

**Comment by rz5** [comment]
@ekeeke, hi.

Some concerns have been raised about these types of core changes breaking save states and examples of how to address this problem include mupen64-plus and Mednafen, projects which both have some sections of kludge code for the sake of the end-user.

Bumping the version number in the line that @clobber linked won't make old save states work but it would at least make the core not crash...could you please give this problem some of your time?

**Comment by ekeeke** [comment]
@clobber: I don't owe you anything, getting angry or calling people out over such tiny issue won't get you anywhere either. Again, broken savestate is something that cannot be fixed when I completely rewrite something from scratch (PSG core) and drop the older core or when new stuff are added. Maintaining backward compatibility is something I tried for a while but it became too much complicated and time consuming. I myself do not have much free time anymore to fully maintain this emulator  so be happy I still commit some stuff from time to time. If someone has time for this and has a solution to propose, fell free to submit pull requests, that's what github is for.

**Comment by clobber** [comment]
@ekeeke Okay, understood. Sorry to come off as rude and entitled.
