### ISSUE TITLE
MEGA-CD: Doesn't detect proper regions on retroarch

### ISSUE THREAD

**Issue by garytr** [ekeeke/Genesis-Plus-GX#195]
Genesis-Plus-GX doesn't detect proper MEGA-CD regions on retroarch.
```
$ git clone --depth=1 https://github.com/ekeeke/Genesis-Plus-GX.git
$ make -j4 -f Makefile.libretro
```
Retroarch: the latest git version
OS: Linux

I tested "time gal (japan)" and "shining force cd (japan)" (CHD format).
System hardware: auto
System region: auto

I can't run the games.
> THIS IS AN NTSC-COMPATIBLE SEGA-CD  
> FOR USE IN NTSC REGIONS OTHER THAN  
> JAPAN AND SOUTHEAST ASIA.

I converted them to bin+cue.
I can run the cue files on picodrive_libretro,
but I can't run them on genesis_plus_gx_libretro.

**Comment by ekeeke** [comment]
It's possible there is a bug with region detection with CHD files. Have you tried with other games in cue/bin format (not converted from chd) ? Also what you mean exactly by "i can't run them". Same region error message ? Or something else ?

Also make sure you have all 3 correct bios for each region (i've already seen people having us bios copied in place of jp bios)

**Comment by KMFDManic** [comment]
Works fine for me.  Every chd has loaded, despite region.  Yes, bios have to be properly configured.  Absolutely love the chd format!  I would love to see it get employed into use with Yabause, 4DO, and PCSX ReArmed Neon, for sure.

**Comment by ekeeke** [comment]
@garytr : what happens if you force system region to game region ?

**Comment by garytr** [comment]
@KMFDManic 
Thank you for the hint!

@ekeeke 
Sorry for the confusion, I checked md5sum of my "bios_CD_J.bin".
The file was for "bios_CD_U.bin".
https://github.com/retropie/retropie-setup/wiki/Sega-CD

I replaced the bios and I can play the games now.
