### ISSUE TITLE
[SEGA CD] time gal (usa): the emulation is rather fast

### ISSUE THREAD

**Issue by garytr** [ekeeke/Genesis-Plus-GX#196]
I ran "time gal (usa)" (SEGA CD, CHD format) on retroarch.
I think the emulation is rather fast. We don't have enough time to push keys.

**Comment by ekeeke** [comment]
Yes, that game is hard. But the emulator does not make it run faster, that's for sure.

**Comment by garytr** [comment]
Thanks ekeeke,

> Yes, that game is hard. But the emulator does not make it run faster, that's for sure.

Then I became too old to play. :-)
