### ISSUE TITLE
Lunar The Silver Star: The color of the selected menu item is thin

### ISSUE THREAD

**Issue by garytr** [ekeeke/Genesis-Plus-GX#199]
Lunar The Silver Star (USA) (CHD)
I think the color of the selected menu item is thin.
I need to increase brightness to play the game.

Genesis-Plus-GX:
![lunar - menu genesis-plus-gx](https://user-images.githubusercontent.com/32613349/32147329-d91e2f46-bd28-11e7-9977-55c0924503d0.png)

Original (?):
https://www.youtube.com/watch?v=WLjC4qyocMU#t=5m53s

Screenshot:
![lunar - menu original](https://user-images.githubusercontent.com/32613349/32147320-cda9e772-bd28-11e7-8e3b-6ddec630c6ec.png)

**Comment by ekeeke** [comment]
The color is defined by Genesis palette, which is accurately emulated, at least in digital domain. The thing is, you will never get exact same color on a modern computer screen as you would have on an old analog TV screen. That video could also has been made with a TV with increased brightness, how would you know?

Anyway, that's what video filters and CRT shaders are for.
