### ISSUE TITLE
Support for playing in 3d anaglyphs master system and Netplay games

### ISSUE THREAD

**Issue by spielvan** [ekeeke/Genesis-Plus-GX#203]
Hello, I would like to add an option that gives to play in 3d anaglyphs of those games of sega master system like zaxxon 3d, outrun 3d etc. would be a great addition, or if they want to add a netplay like other wii snes9xGX emulator! was a request from the member Caio Mauricio there from the blog.

**Comment by ekeeke** [comment]
For 3D support, a feature request already exists but the fact it is 6 years old and still not implemented tells you a lot: https://bitbucket.org/eke/genesis-plus-gx/issues/207/3d-support-for-sms-mark-iii-games

For netplay support, there is no support for that in snes9xgx (or any other Wii homebrew emulators from what I know) and very little chances it ever happens in Genesis Plus GX either as I personally have no idea how to implement this efficiently on Wii.
