### ISSUE TITLE
6 button and savestate

### ISSUE THREAD

**Issue by Superlap1** [ekeeke/Genesis-Plus-GX#208]
many games are unplayables cause the 6 buttons fonction 's no available.Is there a hope you will fix that, and the savestates issue too?? I need to use this emulator , the all in one retroarch is too glitchy, i don t like it... i  have pulled a request but it is closed, maybe i was in the bad section, sorry for that.
...But please answer me and others people, thks.

**Comment by ekeeke** [comment]
I already answered you in the pull request (which is by the way for submitting code changes, not issue reports, hence why it was closed).

Again, I am not the author of the PSVita port and I am not maintaing it. If there are missing or broken features specifically in that port, you have to report is to the developers responsible for it (https://github.com/frangarcj/Genesis-Plus-GX/issues)

**Comment by Superlap1** [comment]
Sorry, didn't saw your answer. I ll try to send a request in the good section.
