### ISSUE TITLE
Ultraverse Prime Cutscene graphics issue

### ISSUE THREAD

**Issue by DiggidyDelRio** [ekeeke/Genesis-Plus-GX#213]
I apologize in advance if this causes confusion or an issue.  

I'm having an issue similar to #81  when playing Ultraverse Prime on the Wii. 

All the other graphics in the game behave well and as expected, but when I beat a boss, the image and text that appears for the little cutscene appear garbled and warped beyond recognition, but it looks perfectly fine for a second after using the restart function on the main menu. 

It's only shown in the cutscenes that appear after you beat a boss. I'll get a picture uploaded of it as soon as I can. 

Again, I'm hoping that I'm not causing a problem by posting this as an issue, the last thing I want to do is waste someone's time but I've used the latest version of Genesis-Plus-GX avaliable for the Wii. 

Thanks in advance.

**Comment by ekeeke** [comment]
This is the right place to report issue. 

I now remember I made some later changes to the code that fixed issue #81 but I did not thought about testing against regressions in that game.

Could you test with these two (older) builds ?

https://github.com/ekeeke/Genesis-Plus-GX/blob/527fd6ecd88109a22beb88d0defb33607a256811/builds/genplus_wii.dol

https://github.com/ekeeke/Genesis-Plus-GX/blob/07f333b1edc6f64149c1365359e5d8a22702fada/builds/genplus_wii.dol

**Comment by ekeeke** [comment]
I tested the game in easy mode (first 2 boss) with latest builds and could not reproduce the issue so I assume you are using an older version.
