### ISSUE TITLE
Wii port - Sega CD issue with music tracks

### ISSUE THREAD

**Issue by SieKensou** [ekeeke/Genesis-Plus-GX#222]
I was playing Eternal Champions CD and when I was fighting agaisnt Jetta I noticed that when the song ends it plays the begining of the next song. It's a clean rip of the original game (cue + bin). I did more tests and it seems that it happens in all stages. After that I tested Sonic CD and it doesn't happen. I'm using the last version (June 20, 2018).

**Comment by SieKensou** [comment]
I'm using the NTSC game. I still didn't tried with different BIOS, but I will. I don't have the Sega CDX connected right now but I will test it too with the original game (Although I don't think the original game has this problem). The problem is that it plays 1 or 2 seconds of the next track and then it restart the track that was playing before.

I have done more tests:
I tested in FUSION for Windows and it does the same with this bin+cue iso, but it works fine with the tracks in different bin files, so I tested this ISO in GenPlus GX too and it works fine. Then I tested the bin+cue in the BIOS menu, listening the music in the player and it happens the same, the tracks doesn't end where they should, the end when the next track already started... I noticed that in this case, the cue+multiple bin has a 2 seconds countdown before start the next track but it plays a bip noise between songs... So after all these tests I think everything points that maybe the problem is the cue itself, but how to fix it? I checked and it looks fine (with the PREGAP set to 2 and everything) Do you have a good working cue+bin to see the difference? I have all my games in just bin+cue because they work better.

**Comment by ekeeke** [comment]
It's definitively an issue with the cue file, could you post it here ? It is possible the 2s pause is actually included within the bin and it should be INDEX 00 commands instead of PREGAP. 
null

**Comment by SieKensou** [comment]
Okay, yes, this is my cue file:
FILE "ETERNAL CHAMPIONS (U).BIN" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    PREGAP 00:02:00
    INDEX 01 14:42:24
  TRACK 03 AUDIO
    INDEX 01 16:36:41
  TRACK 04 AUDIO
    INDEX 01 18:06:07
  TRACK 05 AUDIO
    INDEX 01 19:53:53
  TRACK 06 AUDIO
    INDEX 01 21:43:14
  TRACK 07 AUDIO
    INDEX 01 23:33:15
  TRACK 08 AUDIO
    INDEX 01 25:23:12
  TRACK 09 AUDIO
    INDEX 01 27:13:07
  TRACK 10 AUDIO
    INDEX 01 29:02:64
  TRACK 11 AUDIO
    INDEX 01 30:51:44
  TRACK 12 AUDIO
    INDEX 01 32:37:67
  TRACK 13 AUDIO
    INDEX 01 34:32:16
  TRACK 14 AUDIO
    INDEX 01 36:23:36
  TRACK 15 AUDIO
    INDEX 01 38:05:74
  TRACK 16 AUDIO
    INDEX 01 40:05:36
  TRACK 17 AUDIO
    INDEX 01 41:55:66
  TRACK 18 AUDIO
    INDEX 01 43:44:06
  TRACK 19 AUDIO
    INDEX 01 46:01:03

**Comment by ekeeke** [comment]
Comparing to redump.org track layout available here http://redump.org/disc/2263/ ,
it seems track 02 length is 2s too long (it should be 01:52:17 but here it is 01:54:17 =16:36:41 - 14:42:24), which would explain the issue you are having (all following audio tracks start are shifted by 2s).

Adding 00:02:00 to the INDEX 01 value of all tracks starting from track 03 should fix it.

**Comment by SieKensou** [comment]
Yes, thanks. It works well now.

**Comment by SieKensou** [comment]
Yes, thanks. It works well now.
