### ISSUE TITLE
Wii port - Control enhancements

### ISSUE THREAD

**Issue by SieKensou** [ekeeke/Genesis-Plus-GX#224]
Would be possible to add the option to "restore to default controls"? It would be useful sometimes when you messed up something (specially with the GameCube controller, you can't set the right analog to open the emulator menu as it is originally).
Would be possible to save different control configurations for 3 button pad and 6 button pad (or even control configurations per game, if not saved configuration for the game, use defaults)? The deffault controls for the 3 buttons pad is perfect, but the default configuration for the 6 button controller is very uncomfortable, specially for fighting games.
The best configuration for default games that uses 6 buttons pad would be:
A: y
B: b
C: a
START: +
X : x
Y: R
Z : ZR
MODE: L or -

The best configuration for fighting games (like Street Fighter II and Eternal Champions), for classic controller would be:
A: y
B: x
C: ZR
START: +
X : b
Y: a 
Z : R
MODE: -
This is because is very uncomfortable to press L and ZL while you are using the directional pad. This way all buttons are controlled with the right hand. And this different configuration is why I would like to save controls per game. Not too much games needs this but it would bake things easier to play with this controllers.
This configuration "brokes" the games that uses the 3 buttons control pad and I have to edit the controls again and again...
Obviously this configuration wouldn't work for the GameCube Controller because it doesn't have all these buttons.

**Comment by ekeeke** [comment]
Too much complicated with current codebase, and too much work just for the benefit for a few games .

**Comment by SieKensou** [comment]
That's really sad... it would be really good to have that custom control files per game... is it too much complicated even just for separate the 3 buttons pad config from the 6 button pad config?

**Comment by SieKensou** [comment]
Okay, I understand. I don't wan to bother you too much knowing that. If this is not really posible at this time could you consider at least to change the default controls for Classic Controller as:
A: y
B: b
C: a
START: +
X : x
Y: R
Z : ZR
MODE: L or - (I don't remember where is set in the actual configuration, but the - would work as it is a button that is not used for nothing important).

This way the 3 button pad still has the right buttons but the Y and Z buttons are in the right place to be pressed with the right hand. I think this way is more confortable to use, what do you think?

Thanks for all.
