### ISSUE TITLE
Wii port - Sega CD files option enhancement

### ISSUE THREAD

**Issue by SieKensou** [ekeeke/Genesis-Plus-GX#225]
Well, as you can see, I'm testing GenPlus GX a lot these days with Sega CD games. Would be possible to add an option to hide the bin files in the games list and show only the cue? This would make the game list cleaner. Maybe someone still wants to load directly a bin file, so that's why I ask for an option to "show only cue files in Sega CD games". It's nothing major, but it would be a good point.

**Comment by ekeeke** [comment]
BIN is a valid ROM file extension so I don't want to hide it. I also don't really want to modify the browser code or make it too complicated or configurable.

**Comment by SieKensou** [comment]
It could work as it works now, you only will have to create a new setting like this:
SHOW ONLY CUE FOR MEGA CD/SEGA CD GAMES: NO/YES
This would work just when you select LOAD SEGA CD GAME (because I know some people can be using .bin for Mega Drive roms).

**Comment by ekeeke** [comment]
Obviously, but my point is that the code modification to do this is not trivial and I prefer spending the limited time I have available to work on this emulator on more interesting things.

**Comment by SieKensou** [comment]
Okay, that is very understandable. It would be great if I could help more. I understand the free time is very limited and I really apprecciate your replies. Maybe you can take note of this for a future?

**Comment by SieKensou** [comment]
@ekeeke
Hi, sorry to back to this but I wanted to tell you how Krizz did this in his new cartridge with Sega CD support. It doesn't show the .cue files in the game list but when you load the .bin file it really checks and load the .cue. I don't know if this would be easy to add but will be awesome to not see all Sega CD games with 2 files. Thank you.
