### ISSUE TITLE
Wii port - GameCube various controller enhancements

### ISSUE THREAD

**Issue by SieKensou** [ekeeke/Genesis-Plus-GX#226]
I hope this was easy to add. The problem with the GameCube controller is that you have to fully press the L and R triggers to make the button work. As you know, GameCube controller triggers works when you half press the triggers, so it would be great if these buttons works even if you press them just a bit and not just when you press them fully.

The other thing is the yellow c stick, I would like to have the posibillity of add this as button when you are customizing the controls to use it as it is originally to enter in the emulator menu. If I edit the controls of the GameCube controller, I can't set the c stick to one direction to enter in the menu as it is originally and  I have to use a different button and then I haven't a button available to use for the MODE button...

**Comment by ekeeke** [comment]
>The problem with the GameCube controller is that you have to fully press the L and R triggers to make the button work. As you know, GameCube controller triggers works when you half press the triggers, so it would be great if these buttons works even if you press them just a bit and not just when you press them fully.

This is already the case. The emulator uses PAD_TRIGGER_L and PAD_TRIGGER_R input masks which are set by libogc when the analog trigger is 2/3 pressed . Maybe your controller is less sensitive or you want the trigger to be more sensitive but there is no way to change the threshold value which is hard-coded in libogc and personally, I never had any problem with it (also it's first time someone reports this as an issue).

>The other thing is the yellow c stick, I would like to have the posibillity of add this as button when you are customizing the controls to use it as it is originally to enter in the emulator menu. If I edit the controls of the GameCube controller, I can't set the c stick to one direction to enter in the menu as it is originally 

The yellow c-stick (right analog stick) remains set as the default MENU key (when pressed right) even if you reconfigure your own MENU key. See https://github.com/ekeeke/Genesis-Plus-GX/blob/master/gx/gx_input.c#L244

> and I have to use a different button and then I haven't a button available to use for the MODE button...

You can map a key combo for the MENU key when configuring input keys: just hold the key you want to be used one after another, the key combo will be registered when there are no keys pressed left. The default MENU key combo (apart from the yellow c-stick which always remains used by default as explained above) is RIGHT+Z for example.

https://github.com/ekeeke/Genesis-Plus-GX/blob/master/gx/gx_input.c#L1353

**Comment by SieKensou** [comment]
My GameCube controllers are original from Nintendo but the triggers only take effect in the last press (when the trigger makes the "click"), I was asking for they to act as pressed before the fully pressed state because it has to be pressed a lot and breaks the experience in some games (again fighting games when trying to make combos). It's nothing major but I thought it would be possible (I really don't know how the triggers are set to work but with GameCube games they can work even if you press it a bit and not only when fully pressed them). I didn't know this was set on the library and not on the emulator... Maybe there is another way to activate the half pressed trigger to work...

About the yellow c-stick, the problem is that when setting the new button config it always ask you for the menu button and you can't leave as it is originally (if I press right in the c-stick it does nothing and I have to press a different button or combo and that's what I didn't want to change, I wanted to keep the original configuration, but I didn't knew I had to press more than a key to config the MENU key combo).
Many thanks for the explanation and I have to thank you one more time for the great job done with this emulator, it's the best one from all the Wii scene.
(I know this is not the place but I contacted time ago in the NeoGeo Pocket emulator github but never received response, is it really discontinuated? It would be great to have a good NeoGeo Pocket emulator).

**Comment by ekeeke** [comment]
>I contacted time ago in the NeoGeo Pocket emulator github but never received response, is it really discontinuated? It would be great to have a good NeoGeo Pocket emulator

I don't have time to maintain all the other GX emulators anymore, I only backed up my old googlecode repositories in my github account when googlecode was closed but I didn't touched them since. They are only there to learn anything  from them if someone is interested or eventually to fork them but that's all.

**Comment by SieKensou** [comment]
Oh, that's sad... There is no other "stand alone" NeoGeo Pocket emulator and your NeoPop has a lot of potential. The problem is that is too old and it lacks some stuff (like support for GameCube controller or moving the name of the file to show the full name as GenPlus GX does, or even a screenshot preview when selecting the games...) I would love to see an updated version but it's understandable when the free time doesn't help... It would be great if someone with good knowledge of the NeoGeo Pocket could continue the project.
