### ISSUE TITLE
SDL build

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [ekeeke/Genesis-Plus-GX#232]
Hi,

1. sdl/Makefile.sdl2 contains "-march=i686" option, but this seems unnecessary.
    The excution file built without this option seems to work great, and with this option,
    I have the error below.

cc1: error: CPU you selected does not support x86-64 instruction set

2. sdl/Makefile.sdl2 contains three "$(FLAGS)" options except for "$(CFLAGS)".
    This causes an error below.

In file included from ../core/cd_hw/libchdr/src/chd.c:45:0:
../core/../sdl/osd.h:10:10: fatal error: SDL.h: No such file or directory
 #include <SDL.h>
          ^~~~~~~

    Changing the first "$(FLAGS)" to "$(CFLAGS)" resolves this error.
    But if we change the second one too, then another error below occurs.
    I don't know the reason.

In file included from ../core/cd_hw/libchdr/deps/libFLAC/bitreader.c:42:0:
../core/cd_hw/libchdr/deps/libFLAC/bitreader.c: In function 'FLAC__bitreader_skip_bits_no_crc':
../core/cd_hw/libchdr/deps/libFLAC/include/private/macros.h:43:25: error: ISO C forbids braced-groups within expressions [-Wpedantic]
 #define MIN_IMPL(A,B,L) ({ \
                         ^
../core/cd_hw/libchdr/deps/libFLAC/include/private/macros.h:49:23: note: in expansion of macro 'MIN_IMPL'
 #define flac_min(A,B) MIN_IMPL(A,B,__COUNTER__)
                       ^~~~~~~~
../core/cd_hw/libchdr/deps/libFLAC/bitreader.c:519:8: note: in expansion of macro 'flac_min'
    m = flac_min(8-n, bits);
        ^~~~~~~~

**Comment by tokumeiwokiboushimasu** [comment]
The same applies to sdl/Makefile.sdl, too.

**Comment by ekeeke** [comment]
First issue is caused because you are trying to compile the emulator into a 64-bit application. There is probably some flags in your SDL setup that forces this by default but this is not advised as there might be portability issues, the emulator has indeed been designed for 32-bit platforms.

Second issue is because I forgot to add FLAGS definition in Makefiles when adding libchdr support. You can not use CFLAGS because libchdr source files are not strictly compatible with ANSI C.

**Comment by ekeeke** [comment]
Another solution for the 2nd issue might be to simply remove #include <SDL.h> from osd.h (not sure why exactly it was added here but it shouldn't be needed).

**Comment by noabody** [comment]
On Ubuntu 18.04 this patch is required.
```diff
diff --git a/sdl/Makefile.sdl1 b/sdl/Makefile.sdl1
index d6a81b1..f12a4cb 100644
--- a/sdl/Makefile.sdl1
+++ b/sdl/Makefile.sdl1
@@ -28,7 +28,7 @@
 NAME	  = gen_sdl
 
 CC        = gcc
-CFLAGS    = `sdl-config --cflags` -march=i686 -O6 -fomit-frame-pointer -Wall -Wno-strict-aliasing -ansi -std=c99 -pedantic-errors
+CFLAGS    = `sdl-config --cflags` -O6 -fomit-frame-pointer -Wall -Wno-strict-aliasing -ansi -std=c99 -pedantic-errors
 #-g -ggdb -pg
 #-fomit-frame-pointer
 #LDFLAGS   = -pg
diff --git a/sdl/Makefile.sdl2 b/sdl/Makefile.sdl2
index 557e59c..dede4e8 100644
--- a/sdl/Makefile.sdl2
+++ b/sdl/Makefile.sdl2
@@ -28,7 +28,7 @@
 NAME	  = gen_sdl2
 
 CC        = gcc
-CFLAGS    = `sdl2-config --cflags` -march=i686 -O6 -fomit-frame-pointer -Wall -Wno-strict-aliasing -ansi -std=c99 -pedantic-errors
+CFLAGS    = `sdl2-config --cflags` -O6 -fomit-frame-pointer -Wall -Wno-strict-aliasing -ansi -std=c99 -pedantic-errors
 #-g -ggdb -pg
 #-fomit-frame-pointer
 #LDFLAGS   = -pg
diff --git a/sdl/osd.h b/sdl/osd.h
index f22ddb6..ca2e426 100644
--- a/sdl/osd.h
+++ b/sdl/osd.h
@@ -7,7 +7,6 @@
 #include <stdarg.h>
 #include <time.h>
 
-#include <SDL.h>
 #include <stdlib.h>
 
 #include "main.h"
```

**Comment by ekeeke** [comment]
Replacing -march=i686 by -march=native might be better as it will optimize the generated code for the target cpu and use instruction set of target cpu. Please test and submit a pull request if it works.

**Comment by tokumeiwokiboushimasu** [comment]
Ok, I submitted a pull request.  Thank you.
