### ISSUE TITLE
[GG] Magic Knight Rayearth - Controls partially not working

### ISSUE THREAD

**Issue by Pat86** [ekeeke/Genesis-Plus-GX#240]
Due to the recently released  full english translation for Magic Knight Rayearth on the Game Gear, i wanted to give it a try. Unfortuantely it's not playable. Controls seems to be partially broken. i cant move the cursor in menus, the character goes in a specific direction only etc. Tried the latest version via Retroarch.

**Comment by ekeeke** [comment]
Working fine on my side (tested on both standalone and some old version of retroarch for win32 I have with the latest genesis-plus-gx core) so it's likely an issue on your side (wrong input settings or wrongly applied patch).
