### ISSUE TITLE
broken appveyor release builds?

### ISSUE THREAD

**Issue by truidic** [ekeeke/Genesis-Plus-GX#244]
Hi, when I use the desktop appveyor dll builds, games don't run at all (black screen) but using your pre-built builds they work okay.

ex.
- fork project
- go to ci.appveyor.com; log in using github account button
- create new GPGX project; new build; wait for green lights
- choose windows_msvc2017_desktop_x86 or windows_msvc2017_desktop_x64; click artifacts tab

https://ci.appveyor.com/project/truidic/genesis-plus-gx/build/job/mh83h54yxgibl7f0/artifacts
- download 'genesis_plus_gx_libretro.dll' and run in Retroarch (this is appveyor build); run any game; black screen
- download 'builds\genesis_plus_gx_libretro.dll' and run in Retroarch (this is your build); run same games; sega logo and playable

**Comment by ekeeke** [comment]
I don't maintain libretro builds and don't know anything about that appveyor thing, this was not added by me so you will have to ask libretro devs.

**Comment by truidic** [comment]
Opened an issue downstream and asking for a fix there. Thanks!


Follow-up thread
https://github.com/libretro/Genesis-Plus-GX/issues/152
