### ISSUE TITLE
Use on the upcoming Atgames Genesis Flashback console

### ISSUE THREAD

**Issue by alex-theman** [ekeeke/Genesis-Plus-GX#249]
According to the [FCC filed manual](https://fccid.io/2AMTQ3680SEGA18/Users-Manual/User-manual-3952641), the refreshed HD Genesis Flashback console is using Genesis Plus GX via a written agreement with Charles Macdonald and you. For future reference, can you confirm that this agreement took place? (you don't have to disclose anything regarding the agreement or its requirements)

**Comment by ekeeke** [comment]
>For future reference, can you confirm that this agreement took place?
We indeed signed an agreement with Atgames to grant them commercial use of Genesis Plus GX code for which we fully own the rights. It does not cover any MAME, libretro or other external code though.

>you don't have to disclose anything regarding the agreement or its requirements

Off course we don't, as this is none of your business anyway.
