### ISSUE TITLE
Audio not accurate in Phantasy Star IV (RetroArch)

### ISSUE THREAD

**Issue by Gokuroro** [ekeeke/Genesis-Plus-GX#250]
Build: RetroArch 1.7.4 7856b72 (Linux)
Game: Phantasy Star - The End of the Millennium

When getting to the Tonoe village (3rd-6th town in the game, depending on how it is counted), the background sound has some dog barks every so often in it which is replaced by a buzz noise when playing in the emulator.

Edit: sure this is a very small issue, considering it was found in one village of one game, but it may be a broader audio accuracy issue across other titles.

**Comment by ekeeke** [comment]
Can you give the core settings you are using (especially sound related settings like low-pass filter and ym2612/ym3438 selected core) ?

Also, providing a SRM file for this place would be quite helpful to reproduce (and eventually fix) the issue.

**Comment by Gokuroro** [comment]
[This save file](https://ufile.io/ob0so) should be inside the said village.

After some more tests, I found some points of interest that may help you:
1) it is not actually the dog bark that was replaced, but it is so low compared to that buzz that I thought it was being replaced by that;
2) after the first loop, the buzz becomes a little less noticeable (it seems the note is a little higher and ends up mixing up better or something);
3) for some strange reason this happens when I'm playing on my TV, through HDMI but not through my laptop speakers. Even changing the sound to the TV when I'm inside the village won't have that issue, but as soon as go to the RetroArch menu and back to the game, the buzz will come back.

**Comment by ekeeke** [comment]
>for some strange reason this happens when I'm playing on my TV, through HDMI but not through my laptop speakers. Even changing the sound to the TV when I'm inside the village won't have that issue, but as soon as go to the RetroArch menu and back to the game, the buzz will come back.

I didn't had the time to look to your issue and save file yet but the fact switching in/out from Retroarch makes the issue appear or that it only occurs with some hardware seems like it's more either a frontend issue or an issue with your setup than really an emulation (core) issue.

>genesis_plus_gx_audio_filter = "disabled"
Out of curiosity, could you try with that option enabled and see if your issue still happens  (under the same conditions you described) ?

>genesis_plus_gx_ym2612 = "mame (ym2612)"
Similarly, could you try the other settings for that option and see if one of them fix your issue ?

**Comment by ekeeke** [comment]
I tested with latest core in latest Retroarch (1.7.4 for windows 32-bit) and standalone SDL version but I can not reproduce your issue so this is quite likely something on your end as suspetcted, not an emulation issue.

Here is an audio record of Tonoe Village music as played in Retroarch.
[phantasy-star-iv.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/2403350/phantasy-star-iv.zip)
