### ISSUE TITLE
Packaging....

### ISSUE THREAD

**Issue by johnny-mac** [ekeeke/Genesis-Plus-GX#253]
Hi, I'd like to package this emulator on the Linux distro I use, Void MUSL. 
Does this emulator work stand-alone / without a front-end? And if so, how do I get it to compile? I don't recognize how this source-code is supposed to be built, sorry.

**Comment by ekeeke** [comment]
There is no standalone linux port, you will need to use retroarch frontend and compile the libretro port. I do not provide support for this, sorry.
