### ISSUE TITLE
[libretro] Can't use XE-1 AP in Genesis Plus GX core

### ISSUE THREAD

**Issue by litaniast** [ekeeke/Genesis-Plus-GX#254]
When I select the joypad XE-1 AP, I can't input anything because Genesis Plus GX couldn't got any analog input. (XE-1 AP is an analog stick. can be used in some games like After Burner 2, Space Harrier 32X)

**Comment by ekeeke** [comment]
Genesis Plus GX supports XE-1AP controller just fine (tested on standalone Wii and SDL ports) and although I could never test it in Retroarch  (as I don't own an analog device), it is simply implemented in libretro port through RETRO_DEVICE_ANALOG libretro device (with RETRO_DEVICE_INDEX_ANALOG_LEFT corresponding to the left analog stick and RETRO_DEVICE_INDEX_ANALOG_RIGHT corresponding to the right uni-directional throttle )

See https://github.com/ekeeke/Genesis-Plus-GX/blob/master/libretro/libretro.c#L474 to see interface between Genesis Plus GX core emulation and libretro.

Considering how basic the interface is with libretro API, if the emulator can not get any analog inputs, it's quite unlikely a fault of the emulator but rather a problem with the frontend (retroarch) or with the input driver used in retroarch that does not properly handle RETRO_DEVICE_INDEX_ANALOG_RIGHT and RETRO_DEVICE_INDEX_ANALOG_LEFT inputs. I am afraid I  can not help you with retroarch support as, agin, I never used analog input device with it.
