### ISSUE TITLE
Game Genie (Rev A)

### ISSUE THREAD

**Issue by LodanZark** [ekeeke/Genesis-Plus-GX#257]
According with libretro .dat file, the genesis gx plus uses the follow Game Genie ROM:

> ggenie.bin  crc:5f293e4c md5:b5d5ff1147036b06944b4d2cac2dd1e1 sha1:ea4b0418d90bc47996f6788ad455391d07cad6cc

And that hash's reflect the "Game Genie (USA, Europe) (Program)" according to the no-intro database:
http://datomatic.no-intro.org/?page=show_record&s=32&n=0024

And since there it's an updated version named "Game Genie (USA, Europe) (Rev A) (Program)" (http://datomatic.no-intro.org/?page=show_record&s=32&n=0025), I'm wonder if i can rename this version to "ggenie.bin" it will work, or if has hash validation.

**Comment by ekeeke** [comment]
There is no CRC vérification, the emulator should work with any ROM version, providing it is named as expected and in expected location (same goes for all 'needed' ROM files like BIOS, S&K, etc... for which libretro arbitrarly picked a specific version)
