### ISSUE TITLE
Correct colors option?

### ISSUE THREAD

**Issue by fryshopper** [ekeeke/Genesis-Plus-GX#259]
Hi. TmEE posted a writeup about MD VDP DACs with a table of the true values of each output level.
http://forums.nesdev.com/viewtopic.php?f=23&t=18403

Could we have an option for color correction? Like "Off" vs "Hardware"?

**Comment by ekeeke** [comment]
I already tried to add original RGB levels/scale years ago (based on same researches made on spritesmind forums) but this didn't gave any noticeable differences so I dropped it. Truth is the level differences are too minor for you to notice any color 'corrections' but I guess this could still be added for 'purists'.

**Comment by fryshopper** [comment]
Not interested anymore.
