### ISSUE TITLE
update to lastest Nuked OPN2 (YM2612) core (v1.0.9)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [ekeeke/Genesis-Plus-GX#265]
https://github.com/nukeykt/Nuked-OPN2/commits/master

**Comment by ekeeke** [comment]
From a quick look, the changes compared to version we use (1.0.8) are quite limited (only some register addressing quirk) and probably have no noticeable effect for users but you can make a proper  pull request (like this one https://github.com/ekeeke/Genesis-Plus-GX/pull/211) if you really want this to be merged.
