### ISSUE TITLE
Small typo on the GC/Wii menu

### ISSUE THREAD

**Issue by SuperrSonic** [ekeeke/Genesis-Plus-GX#269]
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/gx/gui/menu.c#L435

"Enable/Disable Wii remote automatic shutodwn"

**Comment by ekeeke** [comment]
Fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/6466994353856da5046940f5cd67fc453abdfd7c

Thanks for the notice
