### ISSUE TITLE
System BootROM enabled causes GG roms to boot to black screen

### ISSUE THREAD

**Issue by klepp0906** [ekeeke/Genesis-Plus-GX#272]
Was tearing my hair out trying to figure this out.  Running the newest nightly w cores updated fwiw.

I have system bootrom on (or did) due to being a sucker for as much authenticity as possible.  That being said, while working fine for genesis games, game gear simply booted to a black screen.  Toggling that off fixes the issue.

**Comment by ekeeke** [comment]
Do you have run-ahead feature enabled in Retroarch ? If yes, can you try with it disabled ? It could be related to this issue : https://github.com/libretro/RetroArch/issues/8402

It was fixed in my repository but it does not seem like the latest commits were actually backported in libretro repository so I doubt nightlies have the fix.

**Comment by klepp0906** [comment]
I do not.  I glanced at it, but a quick google indicated it was tied to save state support, and I want the most universal/set it and forget it type set up.   

that means if not everything is going to support it, not gonna bother.  Especially since input lag isnt an issue for me, and Id rather not muck around with anything that potentially alters its authenticism so to speak ;p

I could be completely off base on how it functions, but regardless - no its not enabled :)

**Comment by ekeeke** [comment]
Do you havd BIOS.gg file in system directory (same place where TMSS bootrom i.e BIOS_MD.bin is stored) ? If yes, are you sure it is valid Game Gear Boot ROM (CRC32 should be 0EBEA9D4) ?

**Comment by klepp0906** [comment]
Yes to the aforementioned, but I did check the hash on the gg bios and sure as shit, it was incorrect.   Makes me wonder about other bios' going forward.   I guess i'll know if i run into problems lol.

sorry for wasting your time and thank you.  Unlikely i woulda stumbed upon that for a goood while :)
