### ISSUE TITLE
(libretro) How to get SMS 3D games to emulate original behavior?

### ISSUE THREAD

**Issue by bakuDD** [ekeeke/Genesis-Plus-GX#277]
Most emulators flicker between l/r frames for 3d sms games, this one defaults to not doing that but I'm assuming there's an option to change to the correct behavior, I don't see it in core options though. As of now there doesn't seem to be a core with both correct 3D emulation _and_ FM sound.

**Comment by ekeeke** [comment]
You can't replicate 3D behavior without 3D-capable hardware. It might be possible to simulate it using current 3D technologies but this would be platform specific (requires specific TV and glasses, as well as specific resolutions available) but therefore out of the scope of emulation core.

**Comment by bakuDD** [comment]
Be that as it may, the current rendering is still a hack which is not accurate to the original hardware.

**Comment by ekeeke** [comment]
Yes, never claimed it was 'accurate'.
But considering the 'accurate' way is unusable without original Sega 3D glasses, I prefer that to people complaining the 3D games are not playable and emulation is buggy because it 'flickers a lot'.
