### ISSUE TITLE
Wii Audio issues

### ISSUE THREAD

**Issue by SieKensou** [ekeeke/Genesis-Plus-GX#281]
Hi,
I noticed recently some audio issues. For example, in Sonic 1 and Sonic 3, when you pause the game, the music should stop completely, but sometimes you can hear some note before fully stops.... I don't know if more games are affected but I noticed in this Sonic games. I tried other emulators and real hardware and I didn't noticed this issue.

**Comment by ekeeke** [comment]
On which port of the emulator and which platdorm did  you noticed this ? Can you record it ?

**Comment by SieKensou** [comment]
I noticed on the Wii standalone version. I'm using the last built available in the builds folder of this github. I said "recently" because I didn't noticed it before because I didn't try this games deeply (but the problem could, and probably, be already there) so I don't know when this started to happen. The settings are unchanged and I think everything is as default. I could try to record the bug, but I'm not sure when because I'm not at home right now, but you should be able to reproduce it. In Sonic 1 in Green Hill or Spring Yard Zone is very noticeable. In Sonic 3 in Angel Island too.

**Comment by ekeeke** [comment]
Sorry but I can not reproduce your issue with latest build (or former build either): I tried first level in Sonic 1 and the music stops immediately when game is paused so I'm not sure what cause the problem on your end. I really doubt this is an emulation bug anyway as it would have been reported by others on other platforms, especially with games that are that much popular. Unless it's a very rare and hardly reproductible issue off course, in which case this could as well happen randomly on real hardware.
