### ISSUE TITLE
Mouse motion is not properly emulated

### ISSUE THREAD

**Issue by Novedicus** [ekeeke/Genesis-Plus-GX#282]
Looking through the code, I noticed that the mouse X and Y values are treated as an absolute position on screen (at least in the SDL builds for PC. It also seems to affect BizHawk, too). In actuality, it's absolute value of the distance it has traveled. Also, the Y axis is flipped.

**Comment by ekeeke** [comment]
Hmm, not sure what code you are referring to but that's not true:
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/sdl/sdl1/main.c#L546

`       /* get mouse (relative values) */
      int x,y;
      int state = SDL_GetRelativeMouseState   `

As far as I am concerned, Sega Mouse is correctly emulated and works in games that support it, assuming the frontend is correctly providing x,y relative mouse values with x positive corresponding to right movement and y positive corresponding to up movement. I am not responsible for frontend code so you will have to ask bizhawk team if you have problems with mouse input.

**Comment by Novedicus** [comment]
Ah, I was looking at the wrong code. My bad. Sorry for wasting your time.
