### ISSUE TITLE
Build for GameShell?

### ISSUE THREAD

**Issue by Atnik** [ekeeke/Genesis-Plus-GX#283]
Hi there,
this is not so much an issue, but as you wrote in the ReadMe to contact you if help is needed, I wanted to ask what kind of customisations are needed to create a standalone build (containing a frontend) for the ClockworkPI GameShell, a small linux handheld. I'm pretty inexperienced in that field, but if you could give me some directions, I could try to make it work. 
Best regards,
Atnik

**Comment by ekeeke** [comment]
I can answer specific questions about how to use Genesis Plus GX functions or interfaces if you have ones but I am afraid cannot help you making a standalone port for a machine I know nothing about, especially if you don't know yourself where to start. My best advice would be to first try to write a simple app which deal with audio/video/input hardware on that machine (there are likely examples and tutorials for that) then when you are familiar with that host platform, look at genesis plus gx sdl port sourcecode or come back with specific and precise questions.
