### ISSUE TITLE
Composite core option makes transparencies flicker

### ISSUE THREAD

**Issue by Tasosgemah** [ekeeke/Genesis-Plus-GX#287]
As most know, the Mega Drive uses the blending of dithering+composite to create fake transparencies and extra colors. However, the composite core option seems broken since whenever there's a transparency on screen (like the waterfalls in Sonic 1 that are created by this blending) they flicker whenever you scroll.

Tried any combination with other core options but they still flicker. Not sure if this happens in other games buy it does in Sonic.

Using the Windows build.

**Comment by ekeeke** [comment]
Yes, this is problem with original NTSC H40 filter from Shai Green, afaik the version he released was only a beta version and he never released a final version. Unfortunately, what this filter is doing is out of my league so I am afraid you will have to live with these filter artefacts or use NTSC shaders instead (if you are using the core in Retroarch).
