### ISSUE TITLE
No support for ISO+WAV Mega CD games

### ISSUE THREAD

**Issue by ToruTheRedFox** [ekeeke/Genesis-Plus-GX#292]
I use ISO+WAV for testing my Mega CD hack before mastering it to a BIN/CUE. It works fine in Fusion, but not here.

**Comment by ekeeke** [comment]
How are the filed (ISO and WAV files) named ? What "does not work" (iso does not boot ? boots bu without

**Comment by ekeeke** [comment]
1) How are the filed (ISO and WAV files) named ? There is naming convention for the emulator to detect audio files (WAV or OGG) when an ISO file os loaded. It should be similar to the one used in Fusion but maybe it's an odd case.

2) What "does not work" exactly ? iso does not boot ? iso boots but without audio ? how many tracks are detected in cd audio player if you enter it on boot ?

3) what tool did you use to make the wav file ? I know some tools add unneccesary info or junk chunks between the wav header and expected wave data chunk identifier and the emulator has some issue detecting this kind of wav files. Can you upload one of your sav file somewhere ?

**Comment by ToruTheRedFox** [comment]
ISO boots without audio, and I haven't checked how many tracks are detected in CD player because BIOS boots into game instead of CD player

**Comment by ToruTheRedFox** [comment]
ok just checked and the CD player detects 99 tracks when there should be 20

**Comment by ToruTheRedFox** [comment]
1. the ISO is called out.iso
3. the wav is a rip of the Sonic CD soundtrack from the CD made by Windows Media Player.
[02 Palmtree Panic- Present.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/3800706/02.Palmtree.Panic-.Present.zip)
oh and also, here's the CUE file
[cuefile.txt](https://github.com/ekeeke/Genesis-Plus-GX/files/3800710/cuefile.txt)
(renamed it to cuefile.txt because GitHub doesn't like the cue extension lol)

**Comment by ekeeke** [comment]
Looking at the wave file, there is indeed some metadata chunk before expected wave data which was  not supported by my wav detection code.

I improved the code to be compatible with any wav file so it should work better know (I tested your wav file with a self-made cue file and it is now detected and played file in boot ROM CD player interface).

Fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/0e8ac65dc470372b145b5d6c5dcbceebe43668f3
