### ISSUE TITLE
multitrack audio BIN loads as one massive track

### ISSUE THREAD

**Issue by ToruTheRedFox** [ekeeke/Genesis-Plus-GX#293]
I have two files set up with my hack: the main ISO file, and a BIN file with the CDDA audio with the CUE file splitting it into multiple tracks (21 to be exact)
Kega Fusion reads it as it should, with the 21 tracks, while GPGX does load the audio, and it can be played fine, but it loads the whole BIN as a single track (which is obviously not good for games)

**Comment by ToruTheRedFox** [comment]
same applies when a standard WAV file is used instead of the raw binary

**Comment by ToruTheRedFox** [comment]
ok I've changed the cue file as literally nothing but Fusion would read it, but it made GPGXs reaction to it even worse:
now it won't boot at all (literally, not even BIOS shows up)

**Comment by ekeeke** [comment]
The first case is probably an edge case that is not correctly handled by my cue parser (as all game images I know either put all tracks including data track in a single bin file or each track in separated files but not data track in one file and all audio tracks in 
another) but I would need to see the cue file to be sure.

2nd case is too vague and unclear to guess anything but it's probably related to your other issue (missing support for wav files with unusual metadata).

As for the last case, it's obviously impossible for me to know what is wrong without knowing exactly what you did to 'fix' your cue file but if the game does not boot it means there is something wrong with the first track description.

**Comment by ToruTheRedFox** [comment]
I changed track indexes to 'fix' it

**Comment by ekeeke** [comment]
Found the issue with your edge case: the CUE file parser assumed by default that if a single file was used for multiple tracks, it was always the first file found in the CUE description (ISO file in your case), which is wrong in your case.

This is now fixed by https://github.com/ekeeke/Genesis-Plus-GX/commit/e455861255f023386f5417d68c3242807513bd1d
