### ISSUE TITLE
Pitch of samples too high in Xeno Crisis

### ISSUE THREAD

**Issue by bryc** [ekeeke/Genesis-Plus-GX#294]
Compared to PC/Switch and BlastEm the pitch is too high in GenPlusGX. Specifically on the voice samples and menu navigation sounds. Xeno Crisis is a new homebrew game: https://shop.bitmapbureau.com/products/xeno-crisis-sega-mega-drive-genesis-rom-download

**Comment by ekeeke** [comment]
Please give more details about emulator configuration: is it in retroarch or standalone version ? on what platform ? what settings (especially audio and region related ones) are you using ?

Also providing recording of the differences source could help figuring your issue

**Comment by bryc** [comment]
I am using RetroArch 1.7.8 under Windows 7.  The core version is 0e4357b.


Here is some audio that shows 4 recordings (NS, PC, BlastEm, GenPlusGX in that order):
https://www.mboxdrive.com/XENOCRISIS.mp3

**Comment by ekeeke** [comment]
Sorry but I barely hear any difference between these sound records. What exactly  am I supposed to listen more carefuly ?

**Comment by bryc** [comment]
Yeah it's a bit hard just by listening I guess.

![image](https://user-images.githubusercontent.com/1408749/69752098-84078d80-111e-11ea-8fd3-892ce5609fdf.png)


Top: BlastEm, Bottom: GenesisPlusGX

It is playing the sample back faster which results at a higher pitch. This graph shows that the length of the sample is not the same. Over time, the distances become further.

![image](https://user-images.githubusercontent.com/1408749/69752407-19a31d00-111f-11ea-9784-1bf54d64baf8.png)

Top: Nintendo Switch, Bottom: PC

These play at the same rate and so can be aligned perfectly.

By layering the two sounds, you can hopefully see what's going on:
https://www.mboxdrive.com/XENOCRISIS2.mp3

The first two play almost perfectly in sync, while the second shows one playing back faster than the other.

Essentially the playback rate is higher than normal.

**Comment by bryc** [comment]
This should show the difference in sample playback rate with less ambiguity:
https://www.mboxdrive.com/xenoblink.mp3

I cut both recordings of GenPlusGX and BlastEm at the exact start and end sample and looped them. Over time, the difference in timing accumulates to such a point that the playback is clearly out of sync, just like turn signals in two different cars going in and out phase. If the timing was exact, this should not happen.

This does not seem to affect the YM2612 output, they seem to still be in sync.

**Comment by ekeeke** [comment]
How much difference (in Hz or ms) are we talking about ? This seems really unsignificant, especially when it's not hearable unless you mix sound from different sources and loop them multiple times or you have to rely on visual graphs to start noticing it...

The fact that different emulators are not perfectly in sync over extended period of time is also unavoidable, no emulators are likely perfectly in sync with real hardware (i.e real Genesis) either.

Now, I don't know how this game sound engine syncs digital voice samples generation (which btw are also coming from YM2612, it's just a specific channel out of 6 that can be turned into dac mode) but maybe it'd related to emulated CPU timing being slightly off (I know Blastem emulates bus refresh and z80/68k buses sharing delays so both CPUs are running slightly slower than in Genesis Plus GX). However, the difference is so minimal and unnoticeable by hears in real gameplay that it's hard to consider this as a real issue.

**Comment by bryc** [comment]
It is entirely hearable, which is why I opened the issue in the first place. I wasn't sure which was correct, BlastEm or GenPlusGX and it turns out GenPlusGX is not correct in this case.

I can't say what the Hz is, but its about half a semitone (music note), or roughly ~68 cents. Not sure how to convert that to Hz, but [according to this](https://music.stackexchange.com/questions/17566/how-to-calculate-the-difference-in-cents-between-a-note-and-an-arbitrary-frequen), "440 Hz is about 39 cents below 450 Hz"

So we are not talking about an extremely small difference. I have to pitch down the output of GenPlusGX essentially **half a note** to match its correct frequency, found across all platforms: PC, Switch, etc.

**Comment by ekeeke** [comment]
Well, it's unhearable to me in your two first records (it is in the third one off course but it's only because it was constructed to accumulate the sound delay to make it noticeable) hence why I am saying the pitch difference is likely very little and this is not really not that much an issue.

There is no 'excuse' to give, I have no clear idea what could be the cause of these little differences but if you are saying Kega has same pitch as Blastem then it's likely not an accuracy issue within the core but more lije a frontend issue, i.e how core audio/video frame rendering is synced with host hardware. It could also be related to libretro port forcing core to output to 32kHz (resampled from original ym2612 'samplerate') then retroarch resampling up to your audio driver output rate (48kHz usually) which affects audio playback. In both cases, nothing I can do about from core side (if you have a modded Wii, you could try standalone version of genesis plus gx to see if it sounds different).

It could also be the fact vsync is emulated at exactly 60hz in Blastem and Fusion, while Genesis Plus GX libretro port reports exact original console frequency to retroarch. It would be interesting to have a comparison not with emulators or native (Switch/PC) versions running on different hardware but with real Genesis hardware.

**Comment by bryc** [comment]
I used BlastEm in the same RetroArch setup as GensPlusGX. I was swapping between the two unsure of which was the correct behavior and checked against the PC/Switch footage on YT.

I do have a modded Wii I can test with though, if that would help?

> It would be interesting to have a comparison not with emulators or native (Switch/PC) versions running on different hardware but with real Genesis hardware.

 I agree, I couldn't find one on YT that is recorded off hardware. I don't own a flashcart or Model 1 to test with though, so someone else would have to do it.

**Comment by bryc** [comment]
[This video from GameSack](https://www.youtube.com/watch?v=lnGfhwyFKZY) here has a clear section of the sample in question played back on real hardware (Model 1).  The speed and pitch of the voice sample is equivalent to BlastEm.

>  I have no clear idea what could be the cause of these little differences but if you are saying Kega has same pitch as Blastem then it's likely not an accuracy issue within the core but more like a frontend issue, i.e how core audio/video frame rendering is synced with host hardware.

That was a fair suggestion, but if it were true, it would also alter the speed (beats per minute) and pitch of the YM2612 output, which doesn't seem to be happening. It's just **sample playback** that is affected. And since there are no standalone versions, I am only able to use RetroArch to test with.

Visually, it is clear to see that the frequency (or clockrate) of the sample playback is too high. Maybe this diagram explains it a bit more easily:

![image](https://user-images.githubusercontent.com/1408749/80928847-61d10600-8d75-11ea-88b0-61ab3455872c.png)

The "Xeno Crisis" speech sample is sped up slightly and as a result, is higher pitched.

Here is another audio sample that compares all three (order: Hardware, Blastem, GenPlusGX): [xenocrisis_audio_bug.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/4572298/xenocrisis_audio_bug.zip). I've slightly exaggerated GenPlusGX so the effect is more obvious.

**Comment by coolstory2048** [comment]
Can confirm the issue, pitch plays too high in Genesis Plus GX, but plays fine in Kega Fusion, which is deeply disappointing, to say the least.

**Comment by ekeeke** [comment]
>It's only sample playback that is affected.

The thing is, samples are still played from one of the six YM2612 channels and the output  frequency of each channel is the same. The only difference when channel 6 is set into 'sample playback' mode is that samples must be feeded in by CPU writes and timed correctly. I'm 100% confident the emulated YM2612 output frequency is correct so a possible issue could be that the samples are written slightly too fast by the emulated CPU (not sure if Xeno Crisis sound engine uses 68k or Z80 CPU for sample playback as I don't have that game).

Have you tried with a more recent version of the libretro core ? I commited some fixes related to YM2612 sync end of last year that I think were backported in libretro repository in february. I know this affected music playback in some demo so maybe it's related to your issue.

You could also try the latest libretro build in my repository as it also has additional fixes related to Z80 timings when reading data from cartridge ROM which slightly slowdowns Z80 processing speed and was required to get another demo's sound engine working properly. It is available under https://github.com/ekeeke/Genesis-Plus-GX/tree/master/builds (this a 32-bit window build so you will need 32-bit windows version of Retroarch).

**Comment by ekeeke** [comment]
>Can confirm the issue, pitch plays too high in Genesis Plus GX, but plays fine in Kega Fusion, which is deeply disappointing, to say the least.

Yeah, sure it is, must really be hard for you, LOL.

**Comment by bryc** [comment]
Hi, TL;DR the 32-bit master build you linked (non-RetroArch) seems to fix it.

I was still using a build from November in my tests, so I updated the 64-bit version of GenPlusGX; no change.

I downloaded a fresh 32-bit RetroArch and the results were surprising.

I first tested the RetroArch build **Genesis Plus GX (v1.7.4 5055106)** which I had to manually download the 32-bit version for it to work here: http://buildbot.libretro.com/nightly/windows/x86/latest/genesis_plus_gx_libretro.dll.zip. The issue occurs in this build as well.

Then I tested the build you suggested here: https://github.com/ekeeke/Genesis-Plus-GX/blob/master/builds/genesis_plus_gx_libretro.dll. This custom build reports version **Genesis Plus GX (v1.7.4 a83de70)**, and it appears to solve the issue! The pitch of the samples match that of BlastEm and Hardware.

Here's another audio comparison (highlights a separate timing issue):

![image](https://user-images.githubusercontent.com/1408749/81015494-cf8c3900-8e2c-11ea-81c3-ebe2171322c2.png)

Whatever fixed the pitch of the sample in this new build, is independent of a separate timing timing issue. Basically GenPlusGX is playing the titlescreen "Xeno Crisis" sound too soon (Maybe it loads it too fast). The waveform for "Hardware" doesn't look like it matches, but it lines up with BlastEm (its a pretty bad audio recording from https://youtu.be/_zXxR2B-IJc?t=40).

But yeah, whatever change is in that build but not the latest nightly in RetroArch, fixed it.

**Comment by coolstory2048** [comment]
> 
> 
> > Can confirm the issue, pitch plays too high in Genesis Plus GX, but plays fine in Kega Fusion, which is deeply disappointing, to say the least.
> 
> Yeah, sure it is, must really be hard for you, LOL.

If you think insulting users is a way to gain respect from the community, be my guest.

**Comment by ekeeke** [comment]
>Whatever fixed the pitch of the sample in this new build, is independent of a separate timing issue. 
Basically GenPlusGX is playing the titlescreen "Xeno Crisis" sound too soon

It's probably related to the emulated 68k CPU being a little bit faster than it really is on real hardware because Genesis Plus GX does not emulate periodical wait states that occur because of bus refresh (those are emulated by Blastem though). But again, it's probably only a few ms difference (maybe even less) and is very likely unnoticeable by ears so I don't consider this to be a major issue.

>If you think insulting users is a way to gain respect from the community, be my guest.

There was no insult on my side, only sarcasm. That pitch difference is barely hearable in the provided records and you have to resort to audio tools to compare recorded waveforms or remix/loop recorded sounds to be able to notice it, so when someone pops out of nowhere in an issue closed 6 months ago to 'confirm' the issue and say it is a major disappointment to him, I am a little bit amused by the disproportional reaction and by the timing, yes :-)

**Comment by bryc** [comment]
> But again, it's probably only a few ms difference (maybe even less) and is very likely unnoticeable by ears so I don't consider this to be a major issue.

Yeah, I would have never have noticed if a game I was playing was 2ms too fast and whether an update fixed it or not. These types of desyncs probably exist in tons of emulators. Makes me wonder how TAS-verified stuff can even work.

> when someone pops out of nowhere in an issue closed 6 months ago to 'confirm' the issue and say it is a major disappointment to him

That person is just some individual from discord where I posted the link, don't mind them. I was asking others if they could notice a difference or if I was crazy. Most people couldn't hear the difference unless the effect was exaggerated, then were able to go back and notice the difference.

In any case, will this change be merged to the RA buildbot at some point? I'm guessing its the Popful Mail fix but I'm not sure. It's actually amazing that build fixed it, since you wontfix'd this issue within 16 hours and never got a chance to realize this game was related as well. So consider yourself a miracle worker; fixing bugs you didn't even know existed. ;)

I guess we can consider this issue doubleplusclosed. Cheers
