### ISSUE TITLE
[GC] SD2SP2 directory support?

### ISSUE THREAD

**Issue by GB-CG** [ekeeke/Genesis-Plus-GX#296]
Now that Swiss supports [SD2SP2](https://github.com/citrus3000psi/SD2SP2), any chance of adding a directory for that in the ROM Load Device setting? ~~And for convenience's sake, directory support for Slot B would be nice too.~~

**Comment by ekeeke** [comment]
Adding support for SD2SP2 is just a matter of compiling the current sourcecode with latest libogc and libfat that added automatic support for that SD device and the emulator will automatically use this device by default when loading ROMs from SD if it is found.

As for adding support for browsing different SD slots (Slot B is currently only accessible if there is nothing in Slot A as Slot A is libfat default device for SD access), it requires heavy modifications to the file browser / menu settings and I'm not convinced this is really worth it, as a single SD device should be more than capable  to hold all the games you need.
