### ISSUE TITLE
Urban Strike bug with 6-Buttons controller ?

### ISSUE THREAD

**Issue by jerkstore369** [ekeeke/Genesis-Plus-GX#299]
Not sure if it's a bug or not but when I was playing Urban Strike for Genesis and change the controls to 6 button controller the game seems to bug out. It may be like that originally in the rom itself but that doesn't seem likely. To test this, right at the beginning of the first mission, the very west part of the beach (fly north west to get there), there will be a green friendly you can rescue by flying over him. After killing whatever is around and rescuing him, you're supposed to be able to press start to see a message. The message only appears for like 1 second and the game goes back to the main combat screen. Also the post-mission score screen only shows for 1 second then goes away. This only happens when controller is set to 6 buttons in the game options. Very weird. It happens in OpenEmu which uses Genesis Plus GX so I figured I'd tell you about it. Thanks.

**Comment by ekeeke** [comment]
According to these postd, this occurs on real hardware when activating 6-button mode in the game so it seems to be a bug in the game:

http://www.sega-16.com/forum/showthread.php?6890-6-button-controller-incompatibility&p=811149

http://www.sega-16.com/forum/showthread.php?6890-6-button-controller-incompatibility&p=811187
