### ISSUE TITLE
Sega CD overclocking support

### ISSUE THREAD

**Issue by FeRcHuLeS** [ekeeke/Genesis-Plus-GX#305]
This feature was implemented for systems like Genesis/Mega Drive and can be apreciated on games like the scaler ones Road Rash series, Duke Nukem 3D and so on, in which games the frame rate improves, tested on systems like Master System and Game Gear in games like Phantasy Star's dungeons, Altered Beast with more fluid or even faster graphics animation. 

On the other hand the Sega CD seems to lack this feature the game tested is Road Rash (Sega CD), no value improves the frame rate and this game seems to use Road Rash 3's game engine for the Genesis/Mega Drive and every game of Road Rash series improve frame rate by overclocking.

**Comment by ekeeke** [comment]
Both 68k cpus (MAIN an SUB-CPU) get overclocked by the same ratio when emulating Sega CD so overclocking is definitively not disabled for Sega CD games.

The fact Road Rash CD looks similar to Genesis version does not necessarely mean it uses exact same engine. There are obviously some differences to deal with the fact graphic data are stored in word-ram on sega cd side (shared between the two cpus) instead of cartridge rom and it's quite possible the game actually uses sega cd graphics processing for sprites scaling, in which case CPU overclock will have no effect.

**Comment by FeRcHuLeS** [comment]
What is exposed sounds pretty interesting, the game maybe it is using the hardware scaling since I noticed the game is a bit smoother than Road Rash 3 (similar engine). Is there a way to measure the FPS by using the method: "Main background field refresh rate per second" using third party software? and Does the Sega CD overclock affect both scaling and rotation by hardware?

**Comment by ekeeke** [comment]
>What is exposed sounds pretty interesting, the game maybe it is using the hardware scaling since I noticed the game is a bit smoother than Road Rash 3 (similar engine). 

No, I verified and it does not use scaling hardware.

>  Is there a way to measure the FPS by using the method: "Main background field refresh rate per second" using third party software?

This is very game-dependent and it woukd require analyzing every VDP writes to know when frame rendering starts and when it ends so no, there is no 'third party software' that do this.

>Does the Sega CD overclock affect both scaling and rotation by hardware?

No, CPU overclock only affect Main and Sub 68K CPUs, gfx operation speed is not affected.

**Comment by FeRcHuLeS** [comment]
It took time and verified by playing another games and the overclocking has no effect, for example in Road Rash CD when there are several bikes near then the game slowsdown heavily, what made me figure out the overclocking should at least eliminate that slowdown like it does on another Genesis/MD games where they have capped frame rate.

It seems the Sega CD overclocking is useless, the reasons are maybe the forced need of a BIOS for the Sega CD, or maybe there is no syncronization of the overclocked processors, or maybe the CD read should speed up and btw there aren't any kind of comparisons through the internet of modded consoles or emulators of Sega CD games overclocked vs not overclocked evidence is not properly implemented yet.
