### ISSUE TITLE
USB mouse support?

### ISSUE THREAD

**Issue by runtoyourdream** [ekeeke/Genesis-Plus-GX#306]
Hi there,

playing mouse supported games with the Wiimote's IR sensor is a pain, would be great to have support for USB mice instead, like many of the computer emulators on Wii do.

Thx

**Comment by ekeeke** [comment]
It is already supported, see the code here that set emulated mouse inputs using USB mouse if it is found:
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/gx/gx_input.c#L1043

Make sure you have Sega mouse enabled on the right port (usually port B for most games) in emulator controller settings and that USB mouse is connected in the right USB port (not sure which one is required by libogc) when emulator is started.

I remember trying it years ago and it was working.
