### ISSUE TITLE
SDL makefiles: missing `opll.o` entry in OBJECTS

### ISSUE THREAD

**Issue by wyatt8740** [ekeeke/Genesis-Plus-GX#313]
You need to add `$(OBJDIR)/opll.o` to your list of objects in the SDL makefiles or the final linking will fail.

Also, it might need a rule to create the `.o` file itself.

**Comment by ekeeke** [comment]
Fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/9d288726bf472a06fd96476f2ee570ed5d1e7890

A general rule already exists for all .c files in /core/sound

Thanks for the report.
