### ISSUE TITLE
Increasing the ROM images file size?

### ISSUE THREAD

**Issue by Grey-Outline** [ekeeke/Genesis-Plus-GX#315]
Hi there, I don't think this is an issue per say but a suggestion, is it possible to increase the ROM images files on the emulation greater than 10 MB for the Wii/Wii U Genesis-plus-GX ? While I could use other emulations that support that image file size on computers, I like to play my roms on consoles for the authentic(ish) feeling. If it's not possible then I understand but I would like to hear why it isn't possible if you want to explain the reason.

Thank you for reading this and have a good one

**Comment by ekeeke** [comment]
Why would you want more than 10 MB? I don't know any game larger than that, includin ROM hacks.

Also keep in mind available RAM is quite limited on Gamecube and Wii: I don't remember how much is left once Genesis Plus GX is loaded with a game (you can see it in exit menu normally, although it can vary for Sega CD games which might require keeping multiple files opened in memory, especially with compressed files) but Gamecube is limited to 24 MB and Wii is limited to 24 MB + 64 MB = 88 MB, with some MB reserved for system operation.
