### ISSUE TITLE
PAL game running at NTSC framerate

### ISSUE THREAD

**Issue by gplaysrv** [ekeeke/Genesis-Plus-GX#316]
PAL game "Micro Machines 2 - Turbo Tournament (Europe) (J-Cart)" is running at 60 fps instead of 50 fps

Rom checksums:
[sha1] ab29077a6a5c2ccc777b0bf22f4d5908401f4d47
[md5] a145194b26c433c8a7159a00bafaba06

Genesis-Plus-GX version tested (as Retroarch core):
1.7.4-5055106

Platforms tested:
- Android 7 (32 bit Arm)
- Arch Linux (AMD64 / x64)

**Comment by ekeeke** [comment]
When console region is set to AUTO, it will default to NTSC (60Hz) unless the loaded ROM header region field indicates the game is only compatible with PAL region consoles. This is simply not this case for this game, also it is perfectly compatible with NTSC consoles despite being released for PAL market only, so there is no real reason to force emulated console region to PAL for this game.

If you want to force emulated console region to PAL, you just need to set the console region setting to PAL in core settings.
