### ISSUE TITLE
[Wii] Not working as a plugin in Wiiflow

### ISSUE THREAD

**Issue by chibidavidkun** [ekeeke/Genesis-Plus-GX#317]
The "game auto-load support through DOL args" feature is not working in Wiiflow Lite 5.4 (any of the builds of genplus_wii.dol from 2019-03-23 to 2020-04-14). The latest working build is the one from 2019-01-26.

**Comment by ekeeke** [comment]
Nothing changed in the code regarding ROM autoload from DOL callback arguments, the only things that changed between these two builds that could have an impact is that I updated libogc and devkitPPC versions used to build the executable so there was likely an issue introduced in one of those external library/toolkit regarding argc/argv handling. 
Are there any other homebrew affected ?
