### ISSUE TITLE
QSound emulation

### ISSUE THREAD

**Issue by Dogway** [ekeeke/Genesis-Plus-GX#322]
Last year MAME [implemented ](https://github.com/vgmrips/vgmplay/issues/51#issuecomment-459873091)correct QSound decoding, I was wondering if this wouldn't be hard to implement as FBNeo also did. More info on [Sega Retro](https://segaretro.org/QSound). And [source ](https://github.com/ValleyBell/libvgm/blob/master/emu/cores/qsound_ctr.c)[code](https://github.com/ValleyBell/libvgm/blob/master/emu/cores/qsound_mame.c).

**Comment by ekeeke** [comment]
Unlike Capcom Arcade hardware, neither Mega Drive or Mega CD has Q-sound decoding or encoding hardware so that code has no use here. The audio output is limited to stereo so Q-Sound encoding is likely either done by software or already encoded in the CD audio tracks for the very few games that supposedly used that technology, and therefore it's already there in emulator produced stereo output.  Q-sound decoding was done by audio equipement so it's not within the scope of this emulator, but rather a frontend thing (if that's even possible)

**Comment by Dogway** [comment]
A few notes, it's virtual stereo, meaning phase encoded channels are extracted and downmixed on the stereo track as a mean to virtualize surround channels on stereo speakers. 

If you mean upmixing (which QSound wasn't designed for but could be possible) you can use a Dolby Surround upmixer or even a Quadraphonic upmixing matrix like the one [I did](https://github.com/Dogway/emulation-random/blob/master/EqualizerAPO/Surround/Quadraphonic_Sound_(5.1_augmented).txt) for EAPO.

**Comment by ekeeke** [comment]
Maybe. Still my point is that QSound encoding in Mega CD games is something that was pre-recorded in the redbook audio so there is nothing that can be added or is missing for 'QSound emulation' in emulator core, the QSound encoded audio stream is already there in the mixed stereo stream output by the emulator, just like when using Mega CD stereo output.

**Comment by Dogway** [comment]
Yes, thanks for the info, if it didn't have a chip that would be the obvious (and performance saving) choice.

**Comment by getdls** [comment]
Draw distance and widescreen mods are roughly the same thing

**Reconnaissance**
Start with simple things: scan through the binaries, read config files, decompile the binary.
Look for patterns that stand out
For widescreen: 1/720, 0.75, etc. 
For LOD/draw distance: Clusters of ramping values that don’t fit matrix/gfx operations and are usually not powers of 2: 200 -> 500 -> 1000, etc.

**Minimize the attack area**
Do the same thing as widescreen: run values at 0.5 in the debugger or basic graphic pack.
See what breaks and what doesn’t. Binary partition to reduce problematic value clusters.

**Analysis / Iterate**
Start tracing promising values back to actual jumps/functions.
Nab new values around that area, go back to recon... iterate.

```
[XCXDrawV102U]
moduleMatches = 0x30B6E091

;Partial LOD ml::CDrMan::CDrMan((ml::CScn *))
0x101156C4 =  .float 0.30000001 * 4.0
0x101156C8 =  .float 600.0      * 4.0
0x101156CC =  .float 2300.0     * 4.0
0x101156D0 =  .float 1100.0     * 4.0
0x101156D4 =  .float 4000.0     * 4.0
0x101156D8 =  .float 5000.0     * 4.0

;Grass  ChagPoliCalcRange__Q2_2ml16CDrMdoCtlMpfAutoFPQ2_2ml5CVec3iT2fRCQ2_2ml5CVec3
0x10116544 =   .float 200.0		* 3.0
0x10116548 =   .float 30.0      * 3.0
0x1011654C =   .float 70.0      * 3.0
0x10116550 =   .float 100.0     * 3.0
0x10116558 =   .float 40.0      * 3.0
0x1011655C =   .float 20.0      * 3.0

;LookupTable smt  ->indirect enemy lod scaling <1 ml::CDrMdoMat::setupAvatarTbl((ml::_MdsMatTopHeader const *))
0x1011642C =   .float 0.5       * 1.5     
```

These are the raw values, i.e., before being traced back. If you start a new game and stand at the top of the hill after the cut-scene, there should be some extra islands in the sky way back. Grass clusters are denser. And if you run a 0.5 multiplier, it's the opposite...

Happy Holidays everyone :)
