### ISSUE TITLE
[Request] Support more Radica Genesis plug & play games

### ISSUE THREAD

**Issue by litaniast** [ekeeke/Genesis-Plus-GX#324]
Currently, Genesis Plus GX can play Radica Genesis Collection Volume 1.
(Arcade Legends Sensible Soccer Plus can run menu, but can't ingame now)

Recently some other roms of those series were dumped (Genesis Collection Volume 2, Super Sonic Gold (Radica Plug & Play), Arcade Legends Street Fighter II: Special Champion Edition) These would be playable on next MAME (0.222)

But they aren't playable in Genesis Plus GX now. I think these use their special mapper.

Those compilations have per one .bin rom, so If it would be playable in Genesis Plus GX, it would be good.

Reference: https://github.com/mamedev/mame/blob/master/src/mame/drivers/megadriv_rad.cpp

Edit: PAL version of Arcade Legends Street Fighter II: Special Champion Edition is playable, but NTSC-U version is dumped recently and not playable yet

**Comment by ekeeke** [comment]
The mapper is already emulated, it's just a matter of adding those new dumps in the internal database to activate the mapper when they are loaded.

See https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/cart_hw/md_cart.c#L106

So all I need is a way to identify these new dumps (the emulator uses ROMinternal header checksum and ROM real computed checksum to identify games with special mappers but maybe Radica dumps share some unique identifier that could be used instead) however I don't know where to find these new dumps...

**Comment by litaniast** [comment]
>however I don't know where to find these new dumps...

Find somewhere says 'MAME 0.222 ROMs sooner'. 
rad_gen2, rad_sonic, rad_sf2 are these. (and rad_ssoc is currently only menu run)
rad_sf2p(formerly rad_sf) works already fine.

**Comment by litaniast** [comment]
Finally MAME 0.222 released that supports them. You can find them in MAME update roms.

**Comment by ekeeke** [comment]
Added in https://github.com/ekeeke/Genesis-Plus-GX/commit/17027ad6c4246b6c0fc5fdbdc6e2b4f6362f7494

**Comment by litaniast** [comment]
Thanks! They work well.
