### ISSUE TITLE
How to check for VBLANK during cpu hook

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#327]
I'm creating a debugger, based on GX and I want to detect execution of VLBANK code during HOOK_CPU (to skip entering VBLANK for `mov sr` instructions). Is it possible? Which flag identifies it?

**Comment by ekeeke** [comment]
You can check VDP status bit 3 which is set to 1 when entering VBLANK (usually start of line 224) and cleared at the start of last line (line 261, which is usually the last line before line 0).

https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/system.c#L424

**Comment by lab313ru** [comment]
I need this to not break into VBLANK code while stepping instruction by instruction in other code.
But with this solution (checking the status flag) is it possible to debug non-vblank code, while vblank is active? As I understand, your cpu code switches between vblank and non-vblank code with some frequency, right? So, the situation when vblank flag is set while executing non-vblank code is possible?

**Comment by lab313ru** [comment]
Seems, I need to skip not only VBLANK, but every interrupt, while stepping.

**Comment by ekeeke** [comment]
If you mean detection of code executed by vertical interrupt (int6), there is no "flag" indicating it and VDP status flags are no use for that (as stated above, VBLANK flag only indicates lines during VBLANK but interrupt routine is called slightly after the start of VBLANK and does not execute during whole VBLANK usually).

A way to detect interrupt processing code could be to first detect when PC is changed to 0x78 (which is the address where level 6 interrupt vector is fetched) then detect whe  "RTE" instruction is executed (which indicates end of interrupt processing)
