### ISSUE TITLE
Krizz modified md+ patchs (for mode 1) dont work in genesis plus gx

### ISSUE THREAD

**Issue by pepodmc** [ekeeke/Genesis-Plus-GX#329]
Krizz had modified mega sd patches to work using mode 1, but i cant make them work in Genesis plus GX (doesnt load new tracks)

Rock and roll racing mode 1 hack and Top Gear 2 mode 1 hack (released before this) works in genesis plus GX.

https://github.com/krikzz/msu-md/tree/master/ips

**Comment by ekeeke** [comment]
Not sure what exactly is not working for you but I quickly tried Golden Axe, Moonwalker and Ys III patched ROMs with CUE/WAV files provided on zeldix forum and it worked fine for me (tested in basic sdl/win32 build that I use for debugging, compiled from latest github sources)

You need to make sure that the CUE file is in same directory as the ROM file you are loading and that both are sharing the same basename (for example "Ys III (USA).cue" and "Ys III (USA).md").

You can also verify the CUE file is detected as a valid audio CD by loading it in the emulator and see if it boots to CD player and plays audio tracks correctly (you will need BIOS_CD_U.bin, BIOS_CD_J.bin and BIOS_CD_E.bin in the usual place).
