### ISSUE TITLE
[libretro] Cheats automatically load and are 'enabled' if left on previously, regardless of settings

### ISSUE THREAD

**Issue by prataczak** [ekeeke/Genesis-Plus-GX#331]
If you load a cheat file for a game (I tested with Mortal Kombat) and enable a cheat, and end the game without toggling it back off, the game will auto load the cheats as 'enabled' the next time you play, without respect to the settings in retroarch.cfg. The two settings in particular are:

apply_cheats_after_load = "false"
apply_cheats_after_toggle = "true"

These are the settings I use, and in most cores (Final Burn Neo being the other one I've found with this problem), the cheats do not auto load when I start a game, but rather, after going into the quick menu/cheats and toggling one of them on or off. This is the way it is supposed to work, but with Genesis Plus GX (and FBNeo), if you left one of the cheats toggled 'on' when you exited the game, the next time you load it, a 'Successfully started cheat search' message appears as soon as the game is loaded.

This is not ideal, because now if you want to use cheats from time to time, you feel obligated to go back into the menu and toggle every single one of them off before you quit playing.

**Comment by ekeeke** [comment]
The core enables/disables cheat entries upon request from the frontend (retroarch)

**Comment by prataczak** [comment]
Sorry, could you clarify? Are you saying you updated the core? Or, are you saying that you can toggle cheats from the frontend? If it is the latter, that is not the issue I am presenting here.

**Comment by prataczak** [comment]
In this core, and a few others, toggles STAY on the next time you play if you toggled them on previously, and that is not how it is supposed to work.

**Comment by ekeeke** [comment]
See my edited response above, I initially pushed the submit button before finishing it.
