### ISSUE TITLE
Support for the CD soundtrack in Tro-Now (homebrew)

### ISSUE THREAD

**Issue by vaguerant** [ekeeke/Genesis-Plus-GX#339]
The free homebrew game Tro-Now by [1985 Alternativo](https://fasebonus.net/1985alternativo/) is designed to be played with the CD soundtrack to *TRON: Legacy* inserted in a Mega-CD simultaneously with Tro-Now in the cartridge port, but I have been unsuccessful in getting this setup to work under RetroArch for Wii U or the native Wii versions of Genesis Plus GX.

On startup, Tro-Now states whether it has detected a Mega-CD, and I always get the answer NO. I have the `cue` file in the directory with the homebrew with the same name, and I'm trying to use `FLAC` audio (is this valid? I didn't find any documentation about it, but libflac seems to be used so I am just assuming). I have tried launching both the homebrew itself (= no CD audio) as well as launching the `cue` file directly (simply crashes).

The RetroArch log appears to have no helpful information; there's nothing related to the Mega-CD appearing in them at all, and since RA crashes when I load the `cue` directly, I don't get a log at all.

Direct link to the Tro-Now download:
https://fasebonus.net/1985alternativo/downloads/tronow.zip

**EDIT:** I see now the libflac code is specifically part of the CHD reading code, so I presumably can't just use loose FLACs with GPGX. Re-encoding as Ogg Vorbis currently and will update with results.

**EDIT2:** Still no luck getting Tro-Now to play with CD audio, but I can at least confirm that the new `ogg`/`cue` encode plays in the Wii version's Mega-CD BIOS CD player when loaded directly. However, exactly the same files loaded on RetroArch for Wii U crashes the console (may not be genplus-gx's issue, RetroArch on Wii U has always been unstable).

So, results at this point:
- RetroArch Wii U with Tro-Now & `ogg`/`cue`: **no CD audio**
- RetroArch Wii U with `ogg`/`cue`: **crash**
- native Wii version with Tro-Now & `ogg`/`cue`: **no CD audio**
- native Wii version with `ogg`/`cue`: **plays CD audio**

**Comment by ekeeke** [comment]
It's possible OGG support (through core internal libtremor or external libvorbis) is not enabled in Wii U libretro port (it must be enabled at compile time in Makefile).

I will look why that homebrew does not detect Mega CD hardware (it should be activated automatically when loading a ROM file with a CUE file with same basename in same directory) but make sure you are using the latest standalone Wii build available from https://github.com/ekeeke/Genesis-Plus-GX/tree/master/builds as I fixed some CD mode 1inaccuracies (for MSU-MD patched games) two months ago.

**Comment by vaguerant** [comment]
> It's possible OGG support (through core internal libtremor or external libvorbis) is not enabled in Wii U libretro port (it must be enabled at compile time in Makefile).

Looks like this is it; ripping again to WAV, the CD can be played in the Mega-CD BIOS.

> make sure you are using the latest standalone Wii build

Yep, I'm on the latest build straight from there.

> either look for such information from the developers

The readme included with the download above seems to be all the documentation there is, and doesn't mention any specific BIOS revision compatibility. You are supposed to be able to override Mega-CD detection, although the instructions are pretty vague:
> - Better MegaCD detection, you can override it pressing A+C in pad 1 during this screen.

I assume "this screen" means the self-test/diagnostic screen on start-up, but I've pressed, held, mashed and done just about all else I can think of with the A+C buttons without ever getting any different behavior.

> or try with different BIOS (MCD1, MCD2, etc)...

Will do.

**Comment by ekeeke** [comment]
Most likely it was only tested on Mega CD 2 hardware because it is more common. There is another homebrew game with similar CD audio support (Escape 2042) which crashes when using model 1 BIOS.

According to sourcecode, it looks for BIOS identification string at arbitrary fixed locations and it also use BIOS commands by jumping to fixed memory locatiob, so CD audio support seems to be hard-coded for later models BIOS.

https://github.com/bitbitjam/bbj2/blob/e505b880f9c684bf9f7e10fc1f462f378a34952e/%5BMD%5D%20Tro-Now/src/engine/title.c#L316
