### ISSUE TITLE
(libretro) Enhanced CD audio support

### ISSUE THREAD

**Issue by fr500** [ekeeke/Genesis-Plus-GX#34]
Is this implemented somehow? I was trying some roms+iso files I found (I had never played Pier Solar on genesis!) and got curious about this.

Is it possible to load a cue+bin image of the enhanced soundtrack and get it detected?

**Comment by sergiobenrocha2** [comment]
This feature only work in RA if you change the extension of the unzipped file from .md to .bin (and I have the same name for both rom and iso files). Does someone have an idea why it happens?

**Comment by fr500** [comment]
that's the way the developer intended it to work, it's not libretro related
it's the same on the Wii IIRC

**Comment by ekeeke** [comment]
Hum, no, the extension of ROM file should not matter, it is indeed a bug in loadrom.c where it assumes the ROM extension is always 3 characters

**Comment by ekeeke** [comment]
This was fixed by https://github.com/ekeeke/Genesis-Plus-GX/commit/bb538929561eb1f82d52ea71d5a41ac3ce6bceb4

**Comment by fr500** [comment]
There is some oddity with this. I'm testing on windows 64bit.
I load retroarch like this:
retroarch --menu --verbose -c configs/andres.cfg

And it doesn't work even though the config only has this:
libretro_directory = ":\libretro"
libretro_info_path = ":\libretro"

If I just load retroarch with no arguments and the same config file in retroarch's location then it works
Again, for testing purposes the config only has this:
libretro_directory = ":\libretro"
libretro_info_path = ":\libretro"

**Comment by fr500** [comment]
Found the issue, this functionality doesn't like relative paths for the rom location

**Comment by ekeeke** [comment]
Indeed, the code now looks for the first occurence of '.' character to detect where the file extension starts, instead of just replacing the last 3 characters like it did before (which didn't work for .md files). So if the romfile path starts with "../" or "./", it won't work.

I had assumed the frontend would always pass the full path or that there can't be '.' character in directory names, which is a little bit unsafe. This can easily be fixed though.

**Comment by fr500** [comment]
Cool, wouldn't it be better to look for the last "."?

**Comment by ekeeke** [comment]
Should be better in https://github.com/ekeeke/Genesis-Plus-GX/commit/935a1f68dc73f2fa5454336b5c6760d3502d770b
