### ISSUE TITLE
standalone version for linux armhf/aarch64

### ISSUE THREAD

**Issue by ghost** [ekeeke/Genesis-Plus-GX#342]
Hi, I would like to have the option to compile this emulator with his intended UI for gc/wii on my arm linux devices, but sadly this seems not available right now, can this be include later on?? thanks

**Comment by ekeeke** [comment]
The GC/Wii standalone UI code is exclusively for the GC/Wii standalone version, it's not portable so  it would need to be done from scratch for other platforms. I don't use ARM linux device (RPI like I guess) and have no plan neither time to work on standalone versions for other platfotms, sorry.

That said, UI assets and code for the GC/Wii version are freely available in this repository (under /gx directory) so anyone with appropriate skills and motivation (it's not an easy task though) could try to port it to another platform I guess.

**Comment by Askmewho** [comment]
thabks for responding so nicely.
