### ISSUE TITLE
Wonder Boy in Monster Land (SMS) is not playable

### ISSUE THREAD

**Issue by rtomasa** [ekeeke/Genesis-Plus-GX#347]
Hi,

Recently I've found out that Wonder Boy in Monster Land is not playable. Immediately, when the game starts, the player glitches in all directions and if you press start button, the player flies in loop. You can see the issue in action here: https://youtu.be/B623N11VURQ

I'm running the retroarch version of Genesis Plus GX (v1.7.4 e8be314) in a Raspberry Pi. Not sure if retroarch is reporting the version correctly but the core is the latest pre-compiled binary available from retropie-setup from November. Also Retroarch is 1.9.0.

BR

**Comment by rtomasa** [comment]
OK I found out that the issue was caused due to Retroarch controller type = Megadrive. After setting to Auto Joy it is working fine, so closing the issue now.

**Comment by SopTheSop2022** [comment]
It Requires A 6-Button DISABLED. 6-button On Master System Have A Glitch Players On Some Games. It Means Pressing Start Button On Master System Mode For GG2SMS Hack (Mega Man,

**Comment by SuperMarioFan2007** [comment]
Use Disable Genesis 6-button Pad
