### ISSUE TITLE
Micro Machines (USA) not working when TMSS boot ROM is enabled 

### ISSUE THREAD

**Issue by gplaysrv** [ekeeke/Genesis-Plus-GX#350]
"Micro Machines (USA).md" (from No-Intro set) not working on Genesis-Plus-GX (RetroArch core, last version)
MD5:       ee7375a2a9e37f8b509a89a6bc894376
SHA1:     39b25dbfa7a80aebdefc19ac2df4bc75b934bbda
SHA256: a670509c7a4feef122d8cbb2f09f9a45789b27cfd3f2f3ef967cc1378daf75da

After starting:
- it show black screen (RetroArch integrated fps counter show normal fps as it was normally playing). 
- no sound / music is played
- it is possible to return to RetroArch (it is not freezed)

Tested on RetroArch 32/64bit, x86/ARM, Linux/Android, Vulkan/OpenGL

**Comment by ekeeke** [comment]
I quickly tested this ROM file with the latest libretro build available in this repository and it worked fine so it is either an issue with your setup  or with the specific libretro build you are using.

Some things you might try:
- if you are loading a zipped rom, try load it unzipped as the zip file I found online had a text file with the .md file and it seems it confused retroarch when I tried to load the archive
- if you have 'Use Boot ROM' setting enabled in core settings, disable it as, for some reason, this ROM dump (which seems quite recent as there were only PAL version dumps in no-intro database last time I checked) does not have a valid SEGA header and will fail to boot on consoles with TMSS boot ROM (genesis models that shows SEGA licensing screen on startup).

**Comment by ekeeke** [comment]
Some more info about this game, looking at the PCB scan available from no-intro database (https://datomatic.no-intro.org/sources%20media/Sega%20-%20Mega%20Drive%20-%20Genesis/20190206_193653_2389_pcb_front.jpg):

It appears the US release of this game has an additional chip (16S25HBA1 PAL chip) on the cartridge PCB which seems to be used to bypass the TMSS boot ROM protection by forcing a soft-reset (asserting /VRES signal on cartridge port) when it detects the boot ROM writes to the console bank-shift register (at address A14101h) to enable access to cartridge ROM before checking the SEGA header.

This will make the game booting fine on TMSS console, despite not having a valid SEGA header (maybe done on purpose to avoid SEGA trademark infringement ?).

I guess this could easily be emulated by forcing a soft-reset for this game specifically after 0x01 is written to 0xA14101.

NB:

The cartridge PCB uses the following signals
- VD15:VD0 (to set/get 16-bit data read/written by CPU)
- VA18:VA1 (to decode up to 512KB address range)
- /CE0 and /CAS0 (to detect CPU read access to cartridge memory)
- /AS (to detect CPU access outside of cartridge memory)
- VCLK (to get CPU clock cycle counter)
- /LWR (to detect CPU byte write access),
- /VRES (to forces CPU soft-reset),

so, most likely, the PAL chip (which is a 20-pin chip, with 2 pins reserved for GND and VCC) asserts /VRES after a few VCLK cycles ( to wait for cartridge ROM bank-switching to become effective on console side) when:
/CE0 = 1
/AS = 0
VA17:VA8 = 0101000001 (just enough to distinguish bank-shift register access at A14101h from other memory accesses to TMSS lockout register at A1400xh or RAM at FFxxxxh)
/LWR = 0
VD0 = 1

**Comment by ekeeke** [comment]
Fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/bc8d1ae2b28c28a633a491cf67824c31f0a4cdc2
