### ISSUE TITLE
Black screen with zipped ROMs

### ISSUE THREAD

**Issue by lonegamer88** [ekeeke/Genesis-Plus-GX#354]
I'm using Retroarch in my Genesis Mini and I'm trying to load zipped ROMs with Gnesis Plus GX. I've tried to load the ROM from playlist and the load content feature, but I always get a black screen. The ROM in the zip must have an especific name/extension? PicoDrive loads zipped ROMs just fine, but maybe I'm doing something wrong.

**Comment by KMFDManic** [comment]
@lonegamer88 Unfortunately, posting an issue here won't really help (for the mini classics), since there are other factors involved with running games on those platforms.  First of all, WHICH modification are you using, hakchi, project lunar?  Note, loading zipped roms works absolutely fine.  So, it is more than likely you have another conflict going on.

**Comment by ekeeke** [comment]
Indeed, zip support in Genesis Plus GX libretro port is managed by Retroarch so this should be reported to the people developing Retroarch (if this issue also occurs with other Retroarch ports than the Mini one) or to the people responsible for the Mini builds. From my experience, loading zop file in PC Retroarch with  this core  works fine so it's probably the latter that you should do.

In any cases, this is not an emulation issue so there is nothing I can do myself.

**Comment by lonegamer88** [comment]
> 
> 
> @lonegamer88 Unfortunately, posting an issue here won't really help (for the mini classics), since there are other factors involved with running games on those platforms. First of all, WHICH modification are you using, hakchi, project lunar? Note, loading zipped roms works absolutely fine. So, it is more than likely you have another conflict going on.

I'm using Project Lunar and I'm using Retroarch directly. I don't use the default menu.

**Comment by KMFDManic** [comment]
@lonegamer88 With hakchi, retroarch I post, Genesis Plus GX, I post, "direct zip" loading functions absolutely fine, without zero issues, whatsoever.  We directly handled any caveats and issues with the custom kernel implementation.  That is where things are fixed to correctly load the zips, as "retroarch" is supposed to.
