### ISSUE TITLE
Double Dragon II the revenge megadrive question/issue

### ISSUE THREAD

**Issue by joepogo** [ekeeke/Genesis-Plus-GX#356]
Hi Eke, been a while and i hope you are well. I recently started playing through the Double Dragon games on megadrive again and ran across some weird issue with the second game on Genesis Plus GX and i thoroughly tested this against all versions and cores and it does the same on all. 

Double Dragon II has always been notoriously bad for being coded poorly to begin with, but the behavior i'm seeing does not match any other emulator i have tested this with. 

The game seems to be lagging and stuttering VERY poorly and almost to the point of unplayable and seems to be in some weird sort of "slideshow mode" where it's stuttering every 1-2 seconds. While it does do this somewhat on other emulators, it's nowhere near as bad. 

I tested many emulators and they all seem to have the same behavior except on Genesis-Plus GX it seems to be a step behind. I am not sure whether to ask if this is a bug ot a question, as something is def off. If you test a few against this version, you will see what i mean.

**Comment by joepogo** [comment]
For some reason, i cannot edit so i had to make another post. For what it's worth, the other Double Dragons play just fine. 1 and 3 are OK.

**Comment by ekeeke** [comment]
Hi, I have no access to a computer for testing right now but I remember fixing this issue a very long time ago (actually when I started working on Genesis Plus compatibility issues in the Gamecube port) and it was related  to HINT/VINT or HBLANK timings I think (there is still some mention about it being fixed in HISTORY.txt) so it's possible this  got broken at some point later and it went under the radar.

**Comment by joepogo** [comment]
No problem. As much work as you have done to the core to increase accuracy and other things, it's most likely something might have been broken across all the changes and no one has managed to see it until now. It's actually the recent released romhack of double dragon II recolored that led me to this finding. I had to test the original as well to make sure it wasn't just something off with the hack.  

Thank you for all that you do once again Eke! It's good to see that i can manage to still find the oddball issues after all these years! :P  I hope you and your family are doing well through all the craziness in this world right now. :)

**Comment by ekeeke** [comment]
Finally got some time to test that game on real hardware (PAL 60hz-modded MD1) and I can confirm the game lags just the same on real hardware as it does in Genesis Plus GX (verified at the start of first level). Looking at the game code, this seems like a bug in the VINT handler which can cause some frame rendering to be missed, thus causing visible frameskipping.
