### ISSUE TITLE
[SMD] [Gamebreking] Jurassic Park: Raptor cannot open the doors

### ISSUE THREAD

**Issue by XargonWan** [ekeeke/Genesis-Plus-GX#362]
I am playing as Raptor in Jurassic Park for Sega MegaDrive and Raptor cannot open the doors in the fifth level. 

Is it possible to fix?
This is a gamebreaking bug. 

Thanks in advance.

**Comment by ekeeke** [comment]
I  quickly tried this game level using a password and it appears you have to press UP in front of doors to open them with Raptor character. It does the same in other emulators so I assume it's not a bug but a game design choice.

**Comment by glebec** [comment]
> I assume it's not a bug but a game design choice

Indeed, it was a deliberately obfuscated mechanic. The player was supposed to be like the raptors from the movie, having to figure out how to open doors independently. The manual doesn't explain it.
