### ISSUE TITLE
Widescreen (16: 9)

### ISSUE THREAD

**Issue by Edu789** [ekeeke/Genesis-Plus-GX#363]
Is it possible to implement the widescreen (16: 9) you have in the Genesis Plus GX Wide from Retroarch?
https://www.youtube.com/watch?v=U4-RHoymtSg

**Comment by ekeeke** [comment]
I am not interested, no. Maybe if it was done in a cleaner way that does not hack  so much the VDP rendering code and does not break other (non libretro) ports but I do not have time or motivation to do this myself and think it is better if kept as a separate fork anyway. AlsoI do not see much use for this outside of retroarch  as other standalone ports are for platforms with limited resolutions.
