### ISSUE TITLE
[libretro] Not triggering a RETRO_ENVIRONMENT_SET_GEOMETRY on resolution change

### ISSUE THREAD

**Issue by substring** [ekeeke/Genesis-Plus-GX#364]
Hi,

If I'm not mistaken, GPGX doesn't fire a RETRO_ENVIRONMENT_SET_GEOMETRY when switching to interlace. Shouldn't geometry change from 320x224 to 320x448 ?

**Comment by ekeeke** [comment]
Interlaced mode 2 outputs 320x248 (or 256x448) only if config.render = 1 in emulator core settings, which should correspond to "Interlaced mode 2 output" option set to "double field" in libretro port.

If that does not work, it is a libretro-specific issue and you should report it in libretro fork repository as I don't maintain the libretro port myself.
