### ISSUE TITLE
Jerky scrolling on some Master System games with Audio Sync On

### ISSUE THREAD

**Issue by pegonma** [ekeeke/Genesis-Plus-GX#366]
I have been trying to play Sonic 2 (8bits) on the Master System, but scrolling is not smooth at all when playing (just move for 2 seconds in the first level to see it), when audio sync is on. This is not due to the original limitations of the hardware (overclocking the processor to 200% fixes the slowdowns in the game, but does not solve the jerky scrolling). Disabling Audio Sync makes the scrolling perfectly smooth, however then the sound is just awful... There must be a way to have smooth scrolling and somewhat fine audio playback : it works fine on Sonic 1.

**Comment by ekeeke** [comment]
I assume you are talking about some Retroarch version as the standalone Wii version does not have CPU overclock or Audio Sync settings. I am afraid you will have to seek support from Retroarch/Libretro devs as I cannot help you with audio/video sync issues in a frontend I don't maintain myself.

**Comment by pegonma** [comment]
Doesn't this retro contain the libretro core for genesis-plus-gx? I just cloned this, built the core and ran it with retroarch...

**Comment by ekeeke** [comment]
Yes, but your issue is a frontend issue, not a core issue. Audio/Video sync is handled by Retroarch  not the core.
