### ISSUE TITLE
Darius has strange sound?

### ISSUE THREAD

**Issue by ketburai** [ekeeke/Genesis-Plus-GX#367]
Hi there, thank you for this great emulator. Noticed something odd about this particular title. Some instruments/sound effects seem to be playing at a higher pitch than is expected. I personally am experiencing this in BizHawk, and I believe [this](https://www.youtube.com/watch?v=o1cEVHBdW4U) is a video of someone using Retroarch getting the same result.

I have no idea what this might sound like on a regular Mega Drive, but it's definitely not how the Mega Drive Mini sounds, as shown [here](https://www.youtube.com/watch?v=YLDy_QpPxks) and [here](https://www.youtube.com/watch?v=QQh2armyVuw). The Mega Drive Mini also sounds more like the arcade original, which it's supposed to be a semi-port of ("semi" as in obviously you can't feasibly do three screens on a Mega Drive). Additionally, the sound seems to match the Mega Drive Mini when I attempt to play the game in Fusion. I figured it'd be the other way around, honestly.

I decided to have a look at other emulators...
- Gens _does_ have the higher pitch.
- Regen also _does_ have the higher pitch.
- BlastEm does _not_ have the higher pitch.
- Exodus also does _not_ have the higher pitch.
- Last but not least, MAME _does_ have the higher pitch.

As you can see, this doesn't seem like a regression. I also do not have a way of testing Genesis Plus at the moment, unfortunately.

Of course, I have each emulator set to an NTSC device, and since I play a lot of Japanese games each emulator was set to default to Japan NTSC whenever possible (Darius is set to be multi-region and I don't think there are any region differences, not even text? Darius has pretty sparse endings). In fact, setting any emulator to use PAL doesn't seem to do anything different in this specific case.

I am assuming this is some extremely specific quirk that the Darius port has. To be honest, to my untrained ears, it sounds as if the lower pitch is something the game is _applying_ to what is "normally" higher pitched sounds/instruments, but I truly have no idea.

I also have not been able to see the version that was released in Darius Cozmic Revelation (which I think is a Japan-exclusive Amazon preorder bonus unfortunately), so I have no idea what's going on there either.

edit: Never mind, just tried regular old GC/Wii Genesis Plus GX. This issue does not seem to occur there. Is this something I should talk to the developers of the libretro port about? If so, I apologize for opening this.

**Comment by ekeeke** [comment]
The first video sounds like someone did not enabled the low-pass filter. I don't know about Bizhawk but there is a core setting for Genesis Plus GX that let you enable and configure audio filtering like on a real condole and make high-frequency sounds less harsh.

**Comment by ketburai** [comment]
Oh, well, this doesn't seem to be an issue with harshness of a given sound, just that some sounds are at a higher pitch than they're supposed to be. I also noticed that the sounds in question are playing slightly faster than they should. For what it's worth, I just tried turning the low-pass filter on and off in the offending emulators and it doesn't seem to change anything either.

However, I just tried a not-libretro version of Genesis Plus GX, and it sounds more like Fusion, BlastEm, Exodus, etc. I think it may be an issue for that port specifically, and thus I believe I have wasted your time, I am sorry.

**Comment by ekeeke** [comment]
Why do you think it is an issue with libretro port ? There is no proof that the video you linked is played in Retroarch and you said you experienced the issue in Bizhawk, which is a completely different frontend so why not post an issue on bizhawk github ?

Anyway, this could maybe caused by emulated CPU being overclocked but this definitively sounds more like high frequencies are not correctly filtered. On real hardware, anything above ~3.6kHz is getting attenuated by analog output circuitry.

**Comment by ekeeke** [comment]
I tried quickly the game in Retroarch and didn't notice anything wrong

without low-pass filter:
https://user-images.githubusercontent.com/717091/118538769-e9a26c00-b74e-11eb-9b27-7a6304cd86e4.mp4

with low-pass filter:
https://user-images.githubusercontent.com/717091/118538891-0b035800-b74f-11eb-8a92-27501cabb3a6.mp4

The latest sounds like your linked videos that supposedly come from Mega Drive Mini. Also sound the same in Kega FUsion with filter option enabled.

**Comment by ketburai** [comment]
Yes, I see that Retroarch is seemingly working, which throws a big question mark on whatever that person is using, and on whatever BizHawk is doing.

I had specifically decided to take the issue outside of BizHawk because, as a multiemulator using cores from various other emulators, issues are often beyond their control. As far as I know, BizHawk uses the libretro core, but I guess this is somehow an issue within their domain.

**Comment by ekeeke** [comment]
I am pretty sure Bizhawk does not use the libretro core at all, it's a completely different emulator that developed its own interfaces with emulators.

You should therefore probably close that issue in libretro repository since you didn't even experienced that issue with Retroarch in the first place... Also, looking how the other reported issues are mostly ignored, I doubt it will get any attention ftom any retroarch/libretro dev.
