### ISSUE TITLE
suggestion : add new accurate mame YM cores

### ISSUE THREAD

**Issue by bigboo3000** [ekeeke/Genesis-Plus-GX#368]
Hi

Mame have new and more accurate YM cores:
https://github.com/aaronsgiles/ymfm

Would it be possible to add them to Genesis-Plus-GX?

**Comment by ekeeke** [comment]
I don't see any reason to switch to these new cores, as there is no known issue with the current one. Also, looking at the code, those new ones do not look particularely more accurate that the one we use, and also, being new, they likely have a few compatibility issues that I certainly have no desire to deal with.
