### ISSUE TITLE
Genesis game crashes exclusively within libretro core emulation

### ISSUE THREAD

**Issue by ner00** [ekeeke/Genesis-Plus-GX#370]
I recently patched a Genesis ROM which alters the movement of the player, a QoL improvement. The patch seems to work completely fine in every emulator (and hardware) except for Genesis libretro cores. While ROM hacking and patching can be considered inherently unstable, I am still curious why this particular patch only seems to have issues with libretro cores, like Genesis Plus GX, but not their standalone counterparts.

Before going further, I have tested the patched ROM successfully in the following standalone emulators: Genesis Plus GX 1.6, Bizhawk 2.6.2, Gens r7, Kega Fusion 3.64. I have tested and confirmed the issue happening in latest versions of these libretro (RA) cores: Genesis Plus GX, PicoDrive, BlastEm.

To be more precise, the actual game is `Landstalker (USA)`, ROM crc32 `FBBB5B97`, and the applied patch is the following: https://www.romhacking.net/hacks/5495/

Landstalker is an isometric game, it originally requires the player to press a diagonal direction on the D-Pad to set and toggle the horizontal/vertical axis directions in which the character will move along; if you press diagonally up+right, or the opposite, down+left then it will set D-up to move diagonally up, D-right to also move diagonally up, D-down to move diagonally down, D-left to also move diagonally down. What the patch does, in practice, is to enforce vertical and horizontal inputs directly into their respective directions for the character in relation to the isometric world plane without the explicit usage of diagonals.

In order to crash the (patched) game on any Genesis libretro core I have to simply do the following:
- Boot and start the game
- (assuming new game) wait for the intro to play out (or fast-forward it)
- Once the intro is done and you have control to move the character, quickly press: up, down, up, down.
- The game should have glitched and frozen

For reference, here's a screenshot of the glitch: 

![Landstalker (USA) control patch libretro glitch](https://i.imgur.com/PPSGejH.png)

This is not actually an issue exclusive of this particular emulator since its implementation in standalones works perfectly fine, as is the case with Bizhawk. Also, the fact that it works fine in every standalone emulator but causes issue exclusively within libretro cores points towards an influence external to the core. Unfortunately I do not have the technical expertise to speculate on why that might be the case, let alone debug it or provide more helpful insight on the matter.

This isolated case is nothing too serious, but I assume that it may encompass other minor misbehaviors that may have other vectors negatively impact this and/or other cores running in libretro. I'll be more than happy to close/move this issue to another repo if deemd more appropriate - at this point I just don't know where to place the issue beside the repo of the most popular Genesis emulator on the block.

**Comment by ekeeke** [comment]
>This is not actually an issue exclusive of this particular emulator since its implementation in standalones works perfectly fine, as is the case with Bizhawk. Also, the fact that it works fine in every standalone emulator but causes issue exclusively within libretro cores points towards an influence external to the core. Unfortunately I do not have the technical expertise to speculate on why that might be the case, let alone debug it or provide more helpful insight on the matter.

Sorry but this repository is not affiliated to libretro and I am not part of libretro support team  so I am not going to spend my time investigating an issue that is, as you describe it, not a core issue but apparently caused by either libretro implementations or frontend (retroarch). You should report this issue to retroarch developers, which are the ones that should investigate it and provide support for the cores they are compiling/publishing, not core developers.

**Comment by ner00** [comment]
Yeah, smooth, thanks.
