### ISSUE TITLE
PAL Overscan

### ISSUE THREAD

**Issue by getCursorsExe** [ekeeke/Genesis-Plus-GX#372]
PAL Overscan is something that _any_ emulator can do, so it is possible to implement this here.

**Comment by ekeeke** [comment]
What do you mean exactly ? There is an option (in both standalone and libretro ports) to show the colored borders (on either sides) or remove them from the rendered video output. And when PAL region console is emulated, those colored borders are larger on top/bottom sides.

**Comment by getCursorsExe** [comment]
Only one frontend, BizHawk is missing overscan borders.
