### ISSUE TITLE
You can port some stuff from blastem/libretro, as it is written in the same language.

### ISSUE THREAD

**Issue by getCursorsExe** [ekeeke/Genesis-Plus-GX#373]
It is possible to port some stuff from blastem/libretro, it is written in the same language. You don't want to do this, right?

**Comment by ekeeke** [comment]
No.
First, I have no idea what 'stuff' you are talking about and second, those are two whole different projects codebase so chances are things are not as simply 'portable' between the two as you think they are.

If you are talking about stuff that are emulated in Blastem but not Genesis Plus GX (like obscure and not offîcialy documented VDP features only used in Titan's Overdrive 2 demo or a few other tech demos), they will eventually get added some day when me or someone else get the motivation and time for it but it's really not high priority, and issue report (or enhancement request) already exist here anyway.
