### ISSUE TITLE
Set "Wiz 'n' Liz" as a PAL game

### ISSUE THREAD

**Issue by anewuser** [ekeeke/Genesis-Plus-GX#384]
Even the European ROM is still running at 60fps, but:

>Wiz 'n' Liz appears to be optimized for PAL systems both in terms of gameplay speed and music speed. As a consequence, the game runs uncontrollably fast when played on an NTSC system. 

https://segaretro.org/Wiz_%27n%27_Liz#Versions

**Comment by ekeeke** [comment]
Fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/e17a5248b1f5cbd4e8fd0df576613e91c9529448
