### ISSUE TITLE
5 Arcade Games in 1

### ISSUE THREAD

**Issue by telanus** [ekeeke/Genesis-Plus-GX#385]
This was recently dumped, and boot's with Genesis Plus GX (Retroarch) but gets stuck at the menu screen

**Comment by ekeeke** [comment]
Looking at this video https://www.youtube.com/watch?v=XauQV3GZyQ4 , this game compilation apparently only works on At Games consoles and  seems to rely on RedKid chip extra features (additional colors, VRAM, layers, etc) so technically it is not really a Genesis game and therefore can not be emulated in Genesis Plus GX

Also, please do not share links to copyrighted ROMs here, this is not the place for that.
