### ISSUE TITLE
Background glitches in Earthworm Jim at Andy Asteroids levels

### ISSUE THREAD

**Issue by Iceman128** [ekeeke/Genesis-Plus-GX#391]
Hi!

I've noted background image glitches in Earthworm Jim (for Genesis/MegaDrive) at Andy Asteroids level. It appears with the background image of space in the left corner and looks like incorrect picture shear, or something like it. For better visibility attaching pictures of that:
![Earthworm Jim-210921-203127_r](https://user-images.githubusercontent.com/62449235/134232791-0d25acd3-f7d3-46b8-a62b-b0d2eab0dae8.png)
![Earthworm Jim-210921-203115](https://user-images.githubusercontent.com/62449235/134232850-46d66796-6dbc-4a6a-8859-dccab241888e.png)

The problem was detected on Genesis-Plus-GX Libretro core in latest builds and far away: it was confirmed on my 2016 year's `genesis_plus_gx_libretro.dll` slice as well.
On other emulators, like PicoDrive or Kega Fusion, Andy Asteroids works fine, which made me think that this is an issue of emulation. However, this comparison might be wrong (moving towards accuracy sometimes show seemed glitches are the same as in real H/W). If so, please close the issue.

Thanks!

**Comment by ekeeke** [comment]
It took me some time (I eventually figured that level could be played by waiting for the demo levels to be all played at title screen) but I verified this also happens on real hardware (MD1 PAL VA4 and MD2 PAL VA0).

That level actually uses 2-cell vertical scrolling mode combined with horizontal scrolling and there is a known bug in original VDP hardware in this mode when the horizontal scroll offset is not a multiple of 16 pixels as this requires an extra 2-cell (16 pixels) column to be partially rendered while the VDP only has room for 20 entries in its internal VSRAM (Vertical Scroll RAM) so an undetermined vertical scroll offset value is applied to the left-most column.

The same bug occurs in one of the level of Gynoug and is even briefly described in one of the official Genesis Software Manual

![image](https://user-images.githubusercontent.com/717091/134434914-38359834-d85f-45c3-a49c-8f81e1399e9c.png)

**Comment by Iceman128** [comment]
It definitely makes sense. Thanks again for the analysis and detailed explanation!
