### ISSUE TITLE
Custom SSF2 Mapper with SRAM Support.

### ISSUE THREAD

**Issue by BillyTimeGames** [ekeeke/Genesis-Plus-GX#392]
Hi everyone! My name Is BillyTime! Games and I make SRAM Hacks.

Today I created a patch to save High Scores in Super Street Fighter 2.  From what I understand, SSF2 uses a custom mapper which disables SRAM. While this patch works in other older emulators, It is currently Incompatible with Everdrives and Genesis Plus GX.

Any way to resolve this issue in Genesis Plus GX will be greatly appreciated. :D 

IPS File:
https://drive.google.com/file/d/11Z9QuAm4xIVig4I5_I29eUPD0WzS1BRb/view

**Comment by ekeeke** [comment]
There is no much way to accurately detect/emulate custom mappers without an internal game database actually, which obviously becomes problematic when it comes to game hacks considering there could always be new hacks coming that want to use some specific mapper,even if it did not exist in original game cartridge.

Genesis Plus GX detects SSF2 mapper using the ROM domestic name, see https://github.com/ekeeke/Genesis-Plus-GX/blob/master/core/cart_hw/md_cart.c#L537 and indeed SSF2 cartridge hardware did not have SRAM support so SRAM is disabled when this game is detected as it is the accurate cartridge hardware behavior

In the mean time, if the game is unknown, the emulator will emulate a default mapper with is "official" SRAM bankswitching mapper (used in some 3MB games like Phantasy Star IV, Beyond Oasis,...) combined with SSF2-like banswitching (for access to ROM larger than 4MB).

If you want to use this default mapper (like a few recent hacks or unofficial games seem to do), the easiest solution is to change the ROM domestic name so it does not match the existing game name.
