### ISSUE TITLE
Support for Mega SD MD+ zipped

### ISSUE THREAD

**Issue by bebess** [ekeeke/Genesis-Plus-GX#393]
Are there any plans to support zipped format for MEGA SD MD+ ?

like:
rom in .zip format and cue+bin in another .zip format (or maybe a renamed .zip file like .mdplus)

example :
SONC.ZIP (contain the zipped .MD file of the game)
SONIC.MDPLUS (contain the zipped .CUE and .BIN files of the game)

**Comment by ekeeke** [comment]
No, support for zipped CD image is not possible.

You can however load zipped ROM file and have cue/wav converted to cue/bin (using some CD tools) then chd (using CHDMAN).

**Comment by bebess** [comment]
@ekeeke  hmm the .chd format dont work for the SD MDR+
the rom dont recognize the format

i use the same chdman as my cd games that work great
i have 2 files : rom.zip (with the .md) and rom.chd (the cue+bin compressed with chdman)

am i doing something wrong ?

**Comment by ekeeke** [comment]
Hmm, my bad... it indeed won't automatically try to load  associated chd file when loading a ROM file, this only works for cue files.

I guess this could be added with very little modification to rom loading function.

**Comment by bebess** [comment]
that would be great :)
should i open a new issue?
