### ISSUE TITLE
[libretro] Dpad doesn't work well on some SMS games

### ISSUE THREAD

**Issue by litaniast** [ekeeke/Genesis-Plus-GX#395]
I played MSX to SMS converted roms by XELA (can google it from youtube), many of them work well but some of them (like Galaga, Zanac) don't work D-pad on libretro Genesis Plus GX core now.

They tested real device (with EverDrive) and Kega Fusion, it worked well.

And I played SMS multicart called "Hi-Com 8-in-1 The Best Game Collection B" but direction moves automatically on menu.

I installed latest RetroArch 1.9.10 and latest built core from libretro.

**Comment by ekeeke** [comment]
I quickly tried the games you mentioned with latest libretro core from here (in Retroarch 1.8.5) and there was no issue with controls so it's likely an issue on your end or with your Retroarch settings (for example, make sure the device type in control port #1 is set to AUTO and not MD JOYPAD 6B as some Master System gamess or hacks might not be compatible with MD control pad).

**Comment by litaniast** [comment]
Strangely, When I change control once (Auto to SMS pad and vice versa) it works well but when I quit RetroArch and restart with saved setting, it doesn't work again. I'm using Windows 10 x64.

I think recent RetroArch changed something for input system.

**Comment by litaniast** [comment]
Oops. sorry. never mind, It's my fault of input remap setting. After I deleted input remap file, works well.
