### ISSUE TITLE
Add these Game Gear prototype games to database

### ISSUE THREAD

**Issue by frafes** [ekeeke/Genesis-Plus-GX#396]
The following Game Gear proto games have to be loaded in Master System compatibility mode (korean mapper?) to work properly:

**Cave Dude (USA) (Proto)**      [CRC32:	CC521975](https://datomatic.no-intro.org/index.php?page=show_record&s=25&n=0503) 
**Street Battle (USA) (Proto) (Unl)**       [CRC32:01A2D595](https://datomatic.no-intro.org/index.php?page=show_record&s=25&n=0506) 

Thanks!

**Comment by ekeeke** [comment]
Where do these proto come from? Master System compatibility mode should not be required to get games working so it's most likely a mapper issue but since there are several different korean mappers or it could be a new one, I need more info about these dumps.

**Comment by ekeeke** [comment]
Street Battle indeed needs to be added in game database as it uses same custom mapper as some other Korean SMS-GG games.

Cave Dude however does not seem to need any mapper (according to meka.nam) and works fine in Genesis Plus GX. What is not working properly with this game exactly ?

**Comment by ekeeke** [comment]
Fixed by https://github.com/ekeeke/Genesis-Plus-GX/commit/b82b02bae7714b9a4a45a2be9a565c0c7c64f121

**Comment by frafes** [comment]
> Street Battle indeed needs to be added in game database as it uses same custom mapper as some other Korean SMS-GG games.
> 
> Cave Dude however does not seem to need any mapper (according to [meka.nam](https://github.com/ocornut/meka/blob/master/meka/meka.nam)) and works fine in Genesis Plus GX without needing specific entry in database.

Cave Dude actually doesn't boot if the options  (Retroarch) "System Hardware = Auto" and "System Boot ROM  = ON". Genesis Plus GX is loading the ROM as a Master System game when it it should  be a Game Gear ROM.

**Comment by ekeeke** [comment]
>Genesis Plus GX is loading the ROM as a Master System game when it should be a Game Gear ROM.

No, all these games run fine as Master System games (which they are actually, just put into a Game Gear cartridge) but indeed, most of these Korean/proto games are not compatible with US/PAL Master System BIOS as it checks if the game has a valid header, which they usually don't have. Forcing the region to Japan or disabling System Boot ROM will make this game runs just fine.

**Comment by frafes** [comment]
Game Gear games like "Castle of Illusion Starring Mickey Mouse (USA, Europe, Brazil)", "Rastan Saga (Japan)", "Chase H.Q. (USA)" and some others with .sms extension also don't boot with US/PAL Master System BIOS, but they work with "System Hardware=Auto" or "System Hardware= Mark III".

I made a test with Cave dude Rom adding this line:

`  {0xCC521975, 0, 0, 0,  MAPPER_SEGA, SYSTEM_GGMS,        REGION_USA}, /* Cave Dude [Proto] [SMS-GG] (US) */`

and it did work fine here.

**Comment by ekeeke** [comment]
Do you have the Game Gear BIOS ROM (BIOS.gg) file ? If not, it is as if you have System Boot ROM option forced disabled when Game Gear or GGMS hardware is emulated.

Again, the only reason this game does not boot is because of System Boot ROM option. If you disable it, it runs fine in Master System mode (with System set to AUTO).

**Comment by frafes** [comment]
Yes, I have BIOS.gg file.

**Comment by ekeeke** [comment]
Actually I was wrong, this game actually has a valid TMS header so it is compatible with Game Gear BIOS. But it likely has a bad checksum or size value in its header, which makes it fail with US/European Master System BIOSes as those verify ROM checksum (contrary to other BIOSes, cf. https://www.smspower.org/Development/BIOSes).

So forcing Game Gear hardware (in MS compatibility mode) is likely the correct solution here (although Mark-III or Japanese Master System  would also work fine).

**Comment by ekeeke** [comment]
Added Cave Dude (Proto) and a few other Taiwanese games incompatible with EU/US Master System BIOS to GG-MS game database in https://github.com/ekeeke/Genesis-Plus-GX/commit/485358ed09b3352e95ffa983d89607e9a555a697

**Comment by frafes** [comment]
It's perfect. Thank you.

**Comment by frafes** [comment]
Hi @ekeeke 

I don't know if I should open a new issue but there is one more Game Gear taiwanese game that could be added to the SMS compatibility mode in the database:

[Lord of Sword [CRC32: 7eaed675]](https://github.com/ocornut/meka/blob/master/meka/meka.nam#L405)

Thanks.

**Comment by ekeeke** [comment]
Added missing GG-MS games (according to latest meka.nam) in https://github.com/ekeeke/Genesis-Plus-GX/commit/24b71ab2c284641755bf42f2a1f809eea0c5da12

**Comment by frafes** [comment]
Thank you for add it.
It seems the following games are imcompatible with SMS mode because they don't boot with Game Gear BIOS:

[Argos no Juujiken [HTH] [SMS-GG]  [CRC32: 5e4b454e]](https://github.com/ocornut/meka/blob/master/meka/meka.nam#L125)
[Doki Doki Penguin Land - Uchuu-Daibouken [HTH] [SMS-GG] (TW) [CRC32: fb163003]](https://github.com/ocornut/meka/blob/master/meka/meka.nam#L224)
[Seishun Scandal [HTH] [SMS-GG] (TW) [CRC32: d0263024]](https://github.com/ocornut/meka/blob/master/meka/meka.nam#L553)

**Comment by ekeeke** [comment]
It does not mean they are incompatible with SMS mode but that they are incompatible with Game Gear models that use a TMSS boot ROM. Afaik, the only Game Gear models with a TMSS boot ROM are later models released by Majesco (in Europe and Brazil only ?)
.
