### ISSUE TITLE
Sega CD sub CPU address error emulation is disabled

### ISSUE THREAD

**Issue by Ralakimus** [ekeeke/Genesis-Plus-GX#397]

**Comment by ekeeke** [comment]
I added compiler-define options to enable SUB-CPU address error exceptions emulation in https://github.com/ekeeke/Genesis-Plus-GX/commit/c6d1e5ac38ec768fcf4a93e37dd44088473f5001 

Currently, it's only enabled for libretro & SDL windows ports.

>but were there any other changes that you made to prevent address errors that I wasn't noticing? I tried to compile my own build with the flag enabled in s68kconf.h, but it didn't appear to do anything.
Address error emulation is also configurable from emulator settings (config_add.addr_error) and this needs to be forwarded to SUB-CPU core like it was done to MAIN-CPU. This is addressed by https://github.com/ekeeke/Genesis-Plus-GX/commit/068769a02e52d3e69048d71a3c82c00867c65422
