### ISSUE TITLE
256x192 on Game Gear games.

### ISSUE THREAD

**Issue by toniosj** [ekeeke/Genesis-Plus-GX#402]
Example: Castle of Illusion.

The game is using Master System resolution incorrectly. I've tried to force GameGear hardware on Core options, but it doesn't work. 

The game should be run at 160 × 144

**Comment by ekeeke** [comment]
That game should be automatically recognized as a SMS-GG game even if it has a .gg extension when system hardware is set to auto.

If it isn't, it's possible it is a hacked or patched version then all you have to do is to either change file extension to .sms or force system hardware to Master System 1 or 2.
