### ISSUE TITLE
Setting audio channels FM and PSG mess with the menus

### ISSUE THREAD

**Issue by aorin1** [ekeeke/Genesis-Plus-GX#403]
Using the latest Retroarch and Genesis Plus GX core, it's been a while since every time I change any value to the FM and PSG sound channels, it will hide the option and can only be set again if I restart the application.

**Comment by ekeeke** [comment]
This should be reported to libretro repository (https://github.com/libretro/Genesis-Plus-GX) where hopefully a retroarch developer will look at it. I am not responsible of Genesis Plus GX libretro port and have no time or interest in looking into bugs or regression introduced by other people.

**Comment by aorin1** [comment]
Makes sense, thanks and sorry to bother!
I`ll report it on Libretro.
