### ISSUE TITLE
[GameCube] GCLoader Support

### ISSUE THREAD

**Issue by Bartman3010** [ekeeke/Genesis-Plus-GX#405]
Would it be possible to add support to read and write to the GCLoader? It replaces the entire DVD drive and is capable of reading and writing to SD cards. As far as I'm aware, Swiss is the only homebrew app that currently supports reading and writing to the GCLoader.

Attempting to load any ROMs or ISOs shows an error "Unable to open directory !" when launched from Swiss via the GC Loader.

**Comment by ekeeke** [comment]
Sorry but it won't happen unless a gc-loader driver is added in libogc/libfat first. Swiss most likely use his own custom drivers and specific low level code but I personally have neither time or motivation to do this. Pull requests are welcome though so anyone really wanting this could submit the required code changes and I would merge it implented properly.
