### ISSUE TITLE
Sound totally garbled in Master System games when restoring a save state using fm sound with nuked core

### ISSUE THREAD

**Issue by spikemorrissey** [ekeeke/Genesis-Plus-GX#410]
I can save and restore snapshots with no problems on games that do not have the FM sound upgrades such as Alex Kidd in Miracle World, Choplifter

However I have totally garbled sound problems when restoring snapshots on all games in a new game session that utilise the FM sound upgrades such as Wonderboy in Monster Land and Fantasy Zone II. There are quite a lot of games on the Master System that make use of FM sound and the difference in quality is amazing!

All games run perfectly with perfect sound in the initial game session - this issue is only reproduced when restoring a snapshot in a new game session so a serious issue

In the retroarch options I have Master system FM set to auto and Master System core set to Nuked.

Please can you advise
Using a raspberry pi 4 RetroPie Version Used : 4.7.1

**Comment by ekeeke** [comment]
I don't have this issue when testing with standalone app or with libretro core compiled from this repository in Retroarcg so it's either an issue with the libretro fork modifications (I know they modified some stuff in sound savestates to support run-ahead for example) or an issue on your side (for example if you changed the Master System core setting between saving and loading the state).

**Comment by spikemorrissey** [comment]
Thank you for the reply. I don't have run ahead enabled and the game speed and sound is perfect in the first game session.
At no point have I changed the core settings. This is a specific issue when restoring a snapshot from games that utilize the FM sound option under Nuked such as Wonderboy in Monster Land and Fantasy zone 2

**Comment by ekeeke** [comment]
Yes, I got it but as I said, I cannot reproduce this issue on my side so this is likely caused by some changes done to savestates in the libretro fork, for which I am not responsible, so it should rather be reported to libretro team so than they can try to reproduce it and eventually fix it.
