### ISSUE TITLE
(Genesis Plus GX 1.7.6) Request: Add SG-1000 Color Palette (For SG-1000, Mark III, Master System, Master System II Mode)

### ISSUE THREAD

**Issue by ghost** [ekeeke/Genesis-Plus-GX#413]
Can You Please Add A SG-1000 Color Palette (For SG-1000, Mark III, Master System, Master System II Mode Emulation):

SG-1000 (Original Color)
Master System (Dark Color)

Also Add SG-1000 Mapper, Master System Mapper Mode

**Comment by SopTheSop2022** [comment]
O

**Comment by SuperMarioFan2007** [comment]
Stop Repeating
