### ISSUE TITLE
(Genesis Plus GX 1.7.6) Request: Add SG-1000 Color Palette

### ISSUE THREAD

**Issue by ghost** [ekeeke/Genesis-Plus-GX#414]
Can You Please Add A SG-1000 Color Palette (For SG-1000, Mark III, Master System, Master System II Mode Emulation):

SG-1000 (Original Color)
Master System (Dark Color)

Also Add SG-1000 Mapper, Master System Mapper Mode

Also Add Support For SC-3000, SF-7000, Sega 32X, Sega CD 32X (BIOS Required)

![Screenshot_20220303-205603~2](https://user-images.githubusercontent.com/99989661/156643381-ae66d8e6-2980-4100-afad-4cfd3efdfc82.jpg)
![Screenshot_20220303-205609~2](https://user-images.githubusercontent.com/99989661/156643399-fc65ea24-c6b8-472c-949b-895d14ff3d47.jpg)

**Comment by SopTheSop2022** [comment]
O
