### ISSUE TITLE
(Genesis Plus GX 1.7.6) Request:

### ISSUE THREAD

**Issue by ghost** [ekeeke/Genesis-Plus-GX#415]
Add A SG-1000 Color Palette (For SG-1000, Mark III, Master System, Master System II Mode Emulation):

SG-1000 (Original Color)
Master System (Dark Color)

Also Add SG-1000 Mapper, Master System Mapper Mode

Also Add Support For SC-3000, SF-7000, Sega 32X, Sega CD 32X (BIOS Required)
![Screenshot_20220303-205603~2](https://user-images.githubusercontent.com/99989661/156643778-6fc32fb3-45f9-4ce2-898e-ddb89be517dc.jpg)
![Screenshot_20220303-205609~2](https://user-images.githubusercontent.com/99989661/156643789-ad2ecbab-0b1b-4389-b6ec-e52f09520f53.jpg)

**Comment by ekeeke** [comment]
>Add A SG-1000 Color Palette (For SG-1000, Mark III, Master System, Master System II Mode Emulation)

TMS VDP original palette is already emulated when emulating SG-1000 hardware, which is the case when emulating SG-1000 games. 

>Also Add SG-1000 Mapper, Master System Mapper Mode

No idea what you mean by that. All known mappers should already be emulated.

>Also Add Support For SC-3000, SF-7000, Sega 32X, Sega CD 32X (BIOS Required)

I have no plan to emulate Sega computers. For 32x, there is already a request for that.

**Comment by DVDVIDE** [comment]
@SopTheSop2022 You Saw Gearsystem's Or PicoDrive's Or KEGA Fusion's Features About Mappers Option In Settings: SEGA, SG-1000, MSX, Korea MSX.

**Comment by SuperMarioFan2007** [comment]
@SopTheSop2022 Master System Uses Dark Color On SG-1000 Games. Master System's CPU Is Z80 And Sprite Color Is 12. SG-1000 Is Backward Compatible With Mark III / Master System / Master System II.

Is Black Screen With Audio Used On Sega Genesis On SG-1000 Games?
