### ISSUE TITLE
Genesis Plus GX 1.7.6 Request: Fix Bug On Some MSX Conversation Games On SG-1000.

### ISSUE THREAD

**Issue by ghost** [ekeeke/Genesis-Plus-GX#419]
It's Not Correct When Some MSX Conversation Games Bug On SG-1000 Emulation. I Know That MSX Conversation Games Works On SG-1000 Hardware. Also Works On Gearsystem Core. Try To Use Gearsystem Core And Update SG-1000's Emulation To Gearsystem Core's SG-1000 Emulation. I'm NOT Spamming. Do NOT Dislike That Issue.
https://www.emutopia.com/index.php/emulators/item/264-sega-gamegear/2114-gearsystem
![156840091-ae84839e-089f-474c-a453-f24df0ba0239](https://user-images.githubusercontent.com/101115623/157041625-9a1faa5b-aa03-4446-b244-5cdfaea6052c.jpg)
![156840105-b869a04f-74a2-4486-a377-ed362dc25dd3](https://user-images.githubusercontent.com/101115623/157041655-d94bdc9f-0766-46a6-8b3a-2e9888f74ee2.jpg)
![156840122-647f9344-1a5c-4852-b25b-75d8b2ce365e](https://user-images.githubusercontent.com/101115623/157041668-908cc989-d5ae-4ce5-b491-bf12b9cc4453.jpg)
![156840129-4a87bf25-63b8-4a0f-8b05-fe7f59d46cd1](https://user-images.githubusercontent.com/101115623/157041684-5c82932c-a7c7-4d14-99b7-6427e7b72433.jpg)
![156840133-ec7822c4-e0f4-4c82-b3a3-33396583dcd3](https://user-images.githubusercontent.com/101115623/157041694-19d08aad-5895-414a-816d-e7bd751d150a.jpg)
![156840140-560f34d4-bcb1-46e3-aadf-395b2e4400d9](https://user-images.githubusercontent.com/101115623/157041703-68db7fbd-8b1d-40a1-837e-9c63c836fe98.jpg)

**Comment by birdybro** [comment]
It sure looks like you are spamming to me. And you have fired up 3 different accounts apparently. No means no buddy.

![image](https://user-images.githubusercontent.com/16388068/157063365-f8154148-4a9b-40d5-b6be-10f1baa9d1e2.png)

**Comment by ekeeke** [comment]
I already answered these issues report:
- those games do NOT work on stock SG-1000 hardware because they need more RAM than the SG-1000 has (afaik, MSX has more RAM than SG-1000)
- the colors look wrong but that is how they look on Master System hardware

The solution to your problem is to run these games on SG-1000 hardware with RAM extension cartridge, which is not possible yet in this emulator but you are free to use another emulator if it works for you... just stop spamming the issue report.

**Comment by HaroldSlikk** [comment]
I'm Using MD.emu For Android. I Need To Get Support For SG-1000 With Gearsystem Core, Game Gear With Genesis Plus GX Core. Master System, Genesis, Sega CD To Be Updated Core To Genesis Plus GX. Got It. 

I Need 8GB RAM Phones Running On Android 11 To Download More Emulators. Google Pixel 5.

**Comment by HaroldSlikk** [comment]
Harold Slikk Who Destroys Computer At Work

**Comment by DVDVIDE** [comment]
@HaroldSlikk You Must Stop Spamming. You Have To Read Community Guidelines. You're Not Allowed To Spam. It's Illegal. Also About Community Guidelines Strike, Copyright Strike
