### ISSUE TITLE
[Feature Request] Optional bios in libretro

### ISSUE THREAD

**Issue by sergiobenrocha2** [ekeeke/Genesis-Plus-GX#42]
Hi, optional bios support (master system, genesis and game gear) in libretro is not working. Is it possible to implement it?

**Comment by ekeeke** [comment]
added in https://github.com/ekeeke/Genesis-Plus-GX/commit/9310dcf92c958f5e5f2a04c17b2118565ee38640

**Comment by sergiobenrocha2** [comment]
Thank you very much!!!
