### ISSUE TITLE
Genesis Plus GX 1.7.6 Request: You Must Fix Bugs On Super Boy I. Super Boy II. Super Boy III. On SG-1000 & SG-1000 II Emulation

### ISSUE THREAD

**Issue by ghost** [ekeeke/Genesis-Plus-GX#420]
You MUST Fix Bug On Super Boy I. Super Boy II. Super Boy III. On SG-1000 & SG-1000 II Emulation. If You Refuse To Fix That Bug, You Will Be Grounded For 2 Weeks!
See That:

Super Boy I. On SG-1000:
Glitch Bug (Genesis Plus GX 1.7.4):
![157041625-9a1faa5b-aa03-4446-b244-5cdfaea6052c](https://user-images.githubusercontent.com/101215826/157318414-47e36ade-a179-4d4e-a283-05fd36a63c6c.jpg)
Fixed (Gearsystem 3.4.1) (SG-1000 Emulation)
![157041655-d94bdc9f-0766-46a6-8b3a-2e9888f74ee2](https://user-images.githubusercontent.com/101215826/157318446-537a3934-201d-4c59-80d9-e6c35fecf812.jpg)

Super Boy II. On SG-1000:
Glitch Bug (Genesis Plus GX 1.7.4):
![157041668-908cc989-d5ae-4ce5-b491-bf12b9cc4453](https://user-images.githubusercontent.com/101215826/157318708-4a391196-cf11-4a50-aa35-9179128295bd.jpg)
Fixed (Gearsystem 3.4.1):
![157041684-5c82932c-a7c7-4d14-99b7-6427e7b72433](https://user-images.githubusercontent.com/101215826/157318800-af477498-726d-49d6-8746-b16086e98f80.jpg)

Super Boy III. On SG-1000:
Glitch Bug (Genesis Plus GX 1.7.4):
![157041694-19d08aad-5895-414a-816d-e7bd751d150a](https://user-images.githubusercontent.com/101215826/157318890-bd8a1ef8-0136-4510-885b-43036be104ea.jpg)
Fixed (Gearsystem 3.4.1):
![157041703-68db7fbd-8b1d-40a1-837e-9c63c836fe98](https://user-images.githubusercontent.com/101215826/157318975-91784d1d-3c61-4e77-bc7f-8a26eff623d1.jpg)

Thanks To See

I'm Patrick Star From SpongeBob SquarePants
©ViacomCBS & Nickelodeon 1999
©Paramount Pictures 2007
©SEGA 2020 (Sonic The Hedgehog Movie 2020)

**Comment by SopTheSop29** [comment]
This Issue Contains Copyrighted Logo. DMCA. Stop Spamming The Same Request. ****DO NOT REMOVE THAT COMMENT****
