### ISSUE TITLE
Option to disable seek time (Msu-md patches)

### ISSUE THREAD

**Issue by pepodmc3** [ekeeke/Genesis-Plus-GX#421]
Hello, can you add an option to disable Seek time on this emulator, please? because with msu-md patches , depending of the minutes of each track, if you are playing the first stage and the death track music is at the end of the tracklist, there will be a delay until the track starts, caused by the seek time.

For example , An user of Zeldix "Void" made a msu-md patch for the game "Castlevania Bloodlines", and im making a music pack for it, this is the cue:

FILE "01 - Konami Logo.wav" WAVE
  TRACK 01 AUDIO
    INDEX 01 00:00:00
FILE "02 - The Beating in Darkness (Title Theme).wav" WAVE
  TRACK 02 AUDIO
    INDEX 01 00:00:00
FILE "03 - A Vision of Dark Secrets (Opening Theme).wav" WAVE
  TRACK 03 AUDIO
    INDEX 01 00:00:00
FILE "04 - Bonds of Brave Men (Character Selection).wav" WAVE
  TRACK 04 AUDIO
    INDEX 01 00:00:00
FILE "05 - Arduous Journey (Map Theme).wav" WAVE
  TRACK 05 AUDIO
    INDEX 01 00:00:00
FILE "06 - Mysterious Curse (Password).wav" WAVE
  TRACK 06 AUDIO
    INDEX 01 00:00:00
FILE "07 - Reincarnated Soul, Part 1 (Introduction).wav" WAVE
  TRACK 07 AUDIO
    INDEX 01 00:00:00
FILE "08 - Reincarnated Soul, Part 2 (Stage 1).wav" WAVE
  TRACK 08 AUDIO
    INDEX 01 00:00:00
FILE "09 - Reincarnated Soul, Part 2 (Stage 1) 2nd section.wav" WAVE
  TRACK 09 AUDIO
    INDEX 01 00:00:00
FILE "10 - The Sinking Old Sanctuary (Stage 2).wav" WAVE
  TRACK 10 AUDIO
    INDEX 01 00:00:00
FILE "11 - The Sinking Old Sanctuary (Stage 2) 2nd section.wav" WAVE
  TRACK 11 AUDIO
    INDEX 01 00:00:00
FILE "12 - The Discolored Wall (Stage 3).wav" WAVE
  TRACK 12 AUDIO
    INDEX 01 00:00:00
FILE "13 - The Discolored Wall (Stage 3) 2nd section.wav" WAVE
  TRACK 13 AUDIO
    INDEX 01 00:00:00
FILE "14 - Iron-Blue Intention (Stage 4).wav" WAVE
  TRACK 14 AUDIO
    INDEX 01 00:00:00
FILE "15 - Iron-Blue Intention (Stage 4) 2nd section.wav" WAVE
  TRACK 15 AUDIO
    INDEX 01 00:00:00
FILE "16 - The Prayer of a Tragic Queen (Stage 5).wav" WAVE
  TRACK 16 AUDIO
    INDEX 01 00:00:00
FILE "17 - The Prayer of a Tragic Queen (Stage 5) 2nd section.wav" WAVE
  TRACK 17 AUDIO
    INDEX 01 00:00:00
FILE "18 - Calling From Heaven (Stage 6).wav" WAVE
  TRACK 18 AUDIO
    INDEX 01 00:00:00
FILE "19 - Calling From Heaven (Stage 6) 2nd section.wav" WAVE
  TRACK 19 AUDIO
    INDEX 01 00:00:00
FILE "20 - Pressure (Invincibility).wav" WAVE
  TRACK 20 AUDIO
    INDEX 01 00:00:00
FILE "21 - Beginning (Classic Tune 1).wav" WAVE
  TRACK 21 AUDIO
    INDEX 01 00:00:00
FILE "22 - Bloody Tears (Classic Tune 2).wav" WAVE
  TRACK 22 AUDIO
    INDEX 01 00:00:00
FILE "23 - Vampire Killer (Classic Tune 3).wav" WAVE
  TRACK 23 AUDIO
    INDEX 01 00:00:00
FILE "24 - Nothing to Lose (Stage 1D).wav" WAVE
  TRACK 24 AUDIO
    INDEX 01 00:00:00
FILE "25 - Messenger From Devil (Area Boss Theme).wav" WAVE
  TRACK 25 AUDIO
    INDEX 01 00:00:00
FILE "26 - The Six Servants of the Devil (Stage Boss Theme).wav" WAVE
  TRACK 26 AUDIO
    INDEX 01 00:00:00
FILE "27 - Theme of Simon (Classic Tune 4).wav" WAVE
  TRACK 27 AUDIO
    INDEX 01 00:00:00
FILE "28- The Vampire's Stomach (Final Boss Theme).wav" WAVE
  TRACK 28 AUDIO
    INDEX 01 00:00:00
FILE "29 - Orb.wav" WAVE
  TRACK 29 AUDIO
    INDEX 01 00:00:00
FILE "30 - Energy Orb.wav" WAVE
  TRACK 30 AUDIO
    INDEX 01 00:00:00
FILE "31 - Stage Clear.wav" WAVE
  TRACK 31 AUDIO
    INDEX 01 00:00:00
FILE "32 - Dracula Orb.wav" WAVE
  TRACK 32 AUDIO
    INDEX 01 00:00:00
FILE "33 - All Clear.wav" WAVE
  TRACK 33 AUDIO
    INDEX 01 00:00:00
FILE "34 - Together Forever (Ending Theme).wav" WAVE
  TRACK 34 AUDIO
    INDEX 01 00:00:00
FILE "35 - Requiem for the Nameless Victims (Staff Roll).wav" WAVE
  TRACK 35 AUDIO
    INDEX 01 00:00:00
FILE "36- death.wav" WAVE
  TRACK 36 AUDIO
    INDEX 01 00:00:00
FILE "37- After the Good Fight (Game Over).wav" WAVE
  TRACK 37 AUDIO
    INDEX 01 00:00:00

As you can see , there will be always a delay to start some tracks if there is a lot of minutes between point A to Point B, but disabling seek time (Everdrive Pro has that feature) this would be fixed

**Comment by ekeeke** [comment]
Added in https://github.com/ekeeke/Genesis-Plus-GX/commit/e366ca817f5b750ad06a8e2c5976d79b3758ea0a
