### ISSUE TITLE
Genesis Plus GX For Android

### ISSUE THREAD

**Issue by LeopoldSlikk06** [ekeeke/Genesis-Plus-GX#422]
Is It Possible To Make A Genesis Plus GX For Android: Touch Phones & Tablets Needs A Viurtal Controller (overlays128.png) 
![overlays128](https://user-images.githubusercontent.com/102609736/160648343-f7f1e13e-8b35-4195-9b96-671c372f64f7.png)

**Comment by ekeeke** [comment]
Surely this is possible as peopke has done it before but I have no plan to do it myself as I am not an android developer and do not like using emulators on touch screen.
