### ISSUE TITLE
188-in-1 SMS mapper support

### ISSUE THREAD

**Issue by litaniast** [ekeeke/Genesis-Plus-GX#424]
https://www.smspower.org/

According to SMS Power!, they dumped new Korean SMS multicart 188-in-1, only the conversion of MSX games.
It has the mapper that previously unknown, so it needs to support it in emulator.

**Comment by ekeeke** [comment]
added in https://github.com/ekeeke/Genesis-Plus-GX/commit/f43a4a7312579bbb9d3048e20d03c9faf9400347
