### ISSUE TITLE
Issue: Bugs on some SG-1000 games on SG-1000 & SG-1000 II emulation Problem

### ISSUE THREAD

**Issue by DiamondCraft27** [ekeeke/Genesis-Plus-GX#426]
I Found Bugs On Some SG-1000 Games On SG-1000 & SG-1000 II Emulation Including **F-16 Fighting Falcon, Super Boy I. (Korea) (Unl), Super Boy II. (Korea) (Unl), Super Boy 3 (Korea) (Unl), Dr. Hello (Korea) (Unl), SG-1000BomberDemo (Homebrew)** Game.

But It's Working On *Mark III, Master System, Master System II, Game Gear, Genesis/MegaDrive* But On Mark III/Master System/Master System II Uses **Dark Colors,** Game Gear/Genesis/MegaDrive Uses **Black Display Screen With Audio Sound.**

I Renamed **.sms** File Extension To **.sg** File Extension To Get TMS9918. It's May Be With *RAM.* SG-1000 Has 1KB or 2KB of Internal RAM. Master System Has 24KB RAM. MSX Has 8KB RAM than SG-1000.

See:
**F-16 Fighting Falcon (SG-1000/SMS)**
![F-16 Fighting Falcon (USA) On SG-1000 Genesis Plus GX](https://user-images.githubusercontent.com/104630031/166105158-672f3807-e71a-4f0d-9380-8d25320759ba.png)

**Super Boy I. (Korea) (Unl) (SG-1000)**
![Super Boy I (Korea) (Unl) SG-1000 GenPlusGX](https://user-images.githubusercontent.com/104630031/166105220-bc63be04-52d9-4551-b873-7c168d9190ba.png)

**Super Boy II. (Korea) (Unl) (SG-1000)**
![Super Boy II (Korea) (Unl) SG-1000 GenPlusGX](https://user-images.githubusercontent.com/104630031/166105237-c7163c8c-3941-415a-8af7-2b2864f6383b.png)

**Super Boy 3 (Korea) (Unl) (SG-1000)**
![Super Boy 3 (Korea) (Unl) SG-1000 GenPlusGX](https://user-images.githubusercontent.com/104630031/166105252-2836420c-31fa-4863-a4dc-70b0299f08ba.png)

**Dr. Hello (Korea) (Unl) (SG-1000)**

https://user-images.githubusercontent.com/104630031/166105409-f78c53e5-0b1c-4bad-b886-1bd2ce27b0f4.mp4

**SG-1000BomberDemo (SG-1000 Homebrew Game)**

https://user-images.githubusercontent.com/104630031/166105442-b9ebc6d1-028b-4fe7-8aa2-554b2baf3d01.mp4

*WORKING: (NO GLITCH, NO BUGS)*

**F-16 Fighting Falcon (SG-1000/SMS)**
![F-16 Fighting Falcon (USA) On SG-1000 Gearsystem](https://user-images.githubusercontent.com/104630031/166105487-92a61503-ce80-4eeb-acd6-6a0c79caec36.png)

**Super Boy I. (Korea) (Unl) (SG-1000)**
![Super Boy I (Korea) (Unl) SG-1000 Gearsystem](https://user-images.githubusercontent.com/104630031/166105552-887f4d04-7dd5-455e-88e1-0e1cce9ba801.png)

**Super Boy II. (Korea) (Unl) (SG-1000)**
![Super Boy II (Korea) (Unl) (SG-1000) Gearsystem](https://user-images.githubusercontent.com/104630031/166105574-d8ed28cd-76b4-42c6-bdcc-0b7683d0df1e.png)

**Super Boy 3 (Korea) (Unl) (SG-1000)**
![Super Boy 3 (Korea) (Unl) SG-1000 Gearsystem](https://user-images.githubusercontent.com/104630031/166105593-728a7245-2312-4ac2-aaf9-f6805964a4a9.png)

**Dr. Hello (Korea) (Unl) (SG-1000)**

https://user-images.githubusercontent.com/104630031/166105613-91faa787-60f6-40ba-94e9-4c3b7ae396bb.mp4

**SG-1000BomberDemo (SG-1000 Homebrew Game)**

https://user-images.githubusercontent.com/104630031/166105669-17996f28-ae9b-4b8d-835c-a257ff41493d.mp4

It's Fine On Other Emulators.

But you need to add a **Mapper (Restart)** Feature: *Auto, ROM, SEGA, Codemasters, Korean, MSX, Janggun, SG-1000*

**NOTE: I BLOCKED AND REPORTED** @ekeeke

NOTE: I'm **NOT** spamming. I Requesting For Genesis Plus GX For **Libretro**

**Comment by ekeeke** [comment]
For the 100x time, those are NOT SG-1000 games, those are Master System games. Emulating SG-1000 hardware with these games will make them crash as they need 8KB RAM while SG-1000 only has 1KB or 2KB of RAM

Stop requesting the same thing again and again, I will NOT do what you are requesting so you can go bug some other emulator and leave this place. Thank you in advance.
