### ISSUE TITLE
L+R+START Menu Combination (SNES Classic Controller)

### ISSUE THREAD

**Issue by C1fer** [ekeeke/Genesis-Plus-GX#429]
Having the ability to bring up the menu using a button combination on the SFC/SNES mini controllers would be very useful.

**Comment by KMFDManic** [comment]
@C1fer this issue has absolutely nothing to do with the genesis plus gx core.  The menu shortcut only works when using retroarch, and is already set as select+start. This wont work on any default games that use Canoe emulator on the SNES Mini.  You would need to install retroarch and and SNES Core, such as SNES9x.  Then, the shortcut would work.

**Comment by C1fer** [comment]
Sorry if I worded the request incorrectly. I was talking about the snes classic controllers on the wii build. Since they don't have a home button, you need to press the home button on the wiimote itself to enter the menu. A button combination would solve this.

**Comment by KMFDManic** [comment]
Select+Start, as previously mentioned, is already this shortcut (to access retroarch menu).  Once you get into retroarch menu, you can simply exit it from there, if u do not have a home button. 
 Genesis Plus GX doesn't have anything to do with this scenario. This would entirely be RetroArch, which already has established shortcut support to open its menu.

**Comment by C1fer** [comment]
As I said in my previous comment, I'm refering to the wii version, not the RA core

**Comment by ekeeke** [comment]
He is talking about the Wii standalone version, which has nothing to do with Retroarch.

Yes, this is possible, there is already a configurable menu key combo for the gamzcube controller,  this can easily be added for classic controllers in general (there is no way to identify snes classic controller from other vlassic controllers connected to wiimote).

**Comment by KMFDManic** [comment]
@ekeeke @C1fer I apologize for misinterpreting standalone versus the retroarch usage:)

**Comment by ekeeke** [comment]
Configurable menu key combo added in https://github.com/ekeeke/Genesis-Plus-GX/commit/5ca459d53fd8f88ed01432410b4212c9835410f6
