### ISSUE TITLE
A

### ISSUE THREAD

**Issue by MrKrabs07** [ekeeke/Genesis-Plus-GX#432]
A

**Comment by KMFDManic** [comment]
@MrKrabs07 you do realize that @ekeeke has spent hundreds upon hundreds of hours shaping and making this emulator better for everyone? What you are currently doing is online bullying, which can lead to mental duress for all involved.  I

There is still a lot of potential for many more great things to be added in the future.  But, do you really want to harass someone so much, that they lose all interest in developing for the emulator? 

You have obviously enjoyed additions added to this emulator, in the past.  Is it fair to kick the gift horse in the mouth, of whom has given you such a treasure to enjoy?

@ekeeke Just keep on doing what you do.  One day, @MrKrabs07 may hopefully realize that "crying wolf" may lead to any and all potential serious requests being ignored.  There could very well be something substantial they discover at one point.  But, "crying wolf", now...will inevitably ensure that never gets taking seriously.

For now, just enjoy your day!
