### ISSUE TITLE
Fix bugs on Korean MSX Conversion To SMS games On SG-1000 Mode Emulation

### ISSUE THREAD

**Issue by ghost** [ekeeke/Genesis-Plus-GX#433]
Bug:

![168464399-a712258c-27ab-4230-9cfd-a425e3252b97](https://user-images.githubusercontent.com/105680411/168690273-57fdd1a7-6d0e-47ab-9be3-d43a1a3bbc8a.jpg)

![168464402-b21a1f4e-5013-4526-ae4f-c45072d19a2d](https://user-images.githubusercontent.com/105680411/168690300-829d0e2c-4f40-490e-bf78-ebb188396935.jpg)

![168464407-4a030fe4-b785-449b-9b7d-0ff4eee98047](https://user-images.githubusercontent.com/105680411/168690316-c12f4627-ec3e-44c5-930c-9c3fd280fad9.jpg)

![168464418-2abdea3a-abe9-4700-bc41-fcbfb7e0cbb8](https://user-images.githubusercontent.com/105680411/168690339-26bd2343-ba08-4231-ac72-3f6c9b80c71c.jpg)

![168464420-c8611e39-898a-4a8a-ba9a-63c89240f793](https://user-images.githubusercontent.com/105680411/168690361-652cd5b4-1f20-41c2-bd15-d9e7dba7abdf.jpg)

![168464422-5f70b7be-9000-4903-a68a-3b00d021a256](https://user-images.githubusercontent.com/105680411/168690378-851f4ff1-e7f0-4e13-a3a9-f924e8933b30.jpg)

You must add Feature of RAM

SG-1000/SG-1000 41% II RAM:

    1KB

    2KB

    4KB

    8KB

    16KB

    32KB

    64KB

    128KB

    256KB

    512KB

    1MB

    2MB

    4MB

    8MB

    16MB

    32MB

    64MB

Master System/Mark III/Master System II RAM:

    1KB

    2KB

    4KB

    8KB

    16KB

    32KB

    64KB

    128KB

    256KB

    512KB

    1MB

    2MB

    4MB

    8MB

    16MB

    32MB

    64MB

Game Gear RAM:

    1KB

    2KB

    4KB

    8KB

    16KB

    32KB

    64KB

    128KB

    256KB

    512KB

    1MB

    2MB

    4MB

    8MB

    16MB

    32MB

    64MB

Genesis / Mega Drive / CD RAM:

    1KB

    2KB

    4KB

    8KB

    16KB

    32KB

    64KB

    128KB

    256KB

    512KB

    1MB

    2MB

    4MB

    8MB

    16MB

    32MB

    64MB

**Comment by GerbilSoft** [comment]
I filed a GitHub abuse report with a fairly comprehensive list of several known alternate accounts and spam issues. Everyone else who's annoyed by this guy should do that too.

**Comment by ekeeke** [comment]
I already reported him multiple times but this has no effect as they don't do IP ban apparently so he will continue to create new accounts until he get bored, reach a more mature age or develop some brain cells, which could take a while.

The saddest thing (for him) is that I could have added what he is asking now (sg1000 model with extended RAM) but everytime he spams a new issue with non sense , this get delayed by six months :-)

**Comment by KMFDManic** [comment]
@ekeeke unfortunately, at this point, updating RAM perimeters would enable a certain someone to have their way.  And, then, they'd likely put pressure on something else they wanted added.  It all could have started with a simple "Could you please add RAM perimeters to the Core, for games that may benefit from it!?" Instead, it became 2 months of nonsense, hehe.  I definitely wouldn't be in any rush to add it, anytime soon.  Hell, I almost want to add it to my own repo and just do a video showcase of it in action, with an ETA release of 2023:)
