### ISSUE TITLE
[Nintendo Wii] Core freezes console

### ISSUE THREAD

**Issue by eku** [ekeeke/Genesis-Plus-GX#435]
If you start the Genesis Plus GX, the screen goes black and the console freezes. Only a power cycle helps. The Genesis-Plus-GX-Wide, on the other hand, works. Also happens with a clean configuration i.e. first run.

Version: RA nightly
Start: through HBC

According to [gbatemp](https://gbatemp.net/threads/the-great-quest-for-wiiflow-plugins-tm-a-call-for-adventurers.563575/post-9831262), 1.8.8. last worked correctly. Since then only degradations in emulation.

If more information is needed or you want me to test something, please feel free.

**Comment by ekeeke** [comment]
You will have to ask Retroarch development team as I am not responsible for their work.
As an alternative, you could also use the standalone Genesis Plus GX application for Wii which I regularely maintain and should be working without issues (see https://github.com/ekeeke/Genesis-Plus-GX/blob/master/builds/genplus_wii.dol and https://github.com/ekeeke/Genesis-Plus-GX/blob/master/gx/docs/README.pdf)
