### ISSUE TITLE
[Sega CD] Special effects are glitchy in Chuck Rock II: Son of Chuck

### ISSUE THREAD

**Issue by jmaneyrol69** [ekeeke/Genesis-Plus-GX#436]
**Description**

**Chuck Rock II: Son of Chuck** mega cd/sega cd version uses special effects specific to the SCD/MCD which are not rendered properly. This affects all rolling boulders, but also sprites such as the giant bird in Stage 2.

This bug is also present in other emulators/cores: lr-picodrive, pemu, Kega Fusion (Windows) and md.emu (Android)

**Game versions**

- Sega CD, US [!] (cue, bin)

**Screens**

| Giant Bird | Boulders | Boulder |
|---|---|---|
| ![Chuck Rock II - Son Of Chuck (u)-220516-102808](https://user-images.githubusercontent.com/45173285/168561362-d9fc13c6-2834-4c96-878b-22a4878cca9d.png) | ![Chuck Rock II - Son Of Chuck (u)-220516-103021](https://user-images.githubusercontent.com/45173285/168561363-51c99f89-39b4-44f2-92e3-2afe405778eb.png) | ![Chuck Rock II - Son Of Chuck (u)-220516-103042](https://user-images.githubusercontent.com/45173285/168561366-daa16686-e3fb-4e2b-8f7b-bab53316f59a.png) |

**Environment**

Version: Genesis Plus GX v1.7.4
Environment: Windows/Linux/Android

**Notes**

- This issue is a duplicate of https://github.com/libretro/Genesis-Plus-GX/issues/298
- The bug also happen with the EU version of the game.
- After further testing, I have found that the [ares emulator](https://ares-emu.net/) renders those effects correctly (the US version does not boot, but the EU version works as expected).

**Comment by ekeeke** [comment]
Thanks for adding mention to Ares emulator: the fact it works fine only in this emulator might be an indication that this is caused by some sync issue between emulated components

**Comment by birdybro** [comment]
I don't see these present in the [MegaCD_MiSTer](https://github.com/MiSTer-devel/MegaCD_MiSTer) core either. I also suspect it is related to inter-system timings.

**Comment by ekeeke** [comment]
This was actually a bug in mega-cd graphics processor implementation. For the technical record, I was assuming games that use 32x32 pixels stamp would always set the two lower bits of stamp index to 0 as required in Mega-CD hardware manual but it appears this game does not and those bits are actually masked by hardware instead.

@birdybro: there is another mega-cd bug occurring in all existing software emulators (including Ares this time), see #290
