### ISSUE TITLE
SG-1000 mode with extended RAM

### ISSUE THREAD

**Issue by ghost** [ekeeke/Genesis-Plus-GX#437]
Is it possible to add feature **SG-1000 mode with extended RAM**

SG-1000 mode with extended RAM is about Master System TMS9918-based games (such as: **MSX2SMS** Hack games).

SG-1000 & SG-1000 II uses original TMS9918

**Comment by ekeeke** [comment]
I am leaving this one open as it is expressed - for once - in a more reasonable and intelligible way (only removed the links to previously spammed issues as this is not needed).
