### ISSUE TITLE
[Wii] Sega CD Compatibility Broken

### ISSUE THREAD

**Issue by Sowden** [ekeeke/Genesis-Plus-GX#438]
Hey guys. I just hooked up my Wii U for the first time in a while, and I wanted to update my apps. I opened Homebrew Browser and downloaded the latest Genesis Plus GX that they had, ran it and it worked great. But I wanted to get the latest build off of the github as I was pretty sure that it wasn't up on the Homebrew Browser server. Downloaded it, put it on my SDcard. But when I went to load a Sega CD game, the BIOS would boot but it didn't detect a CD. I hit reset, so that it thought the CD tray was ejected, hit start to pop it back in, and it still didn't detect a CD. My Road Rash .CUE and .BIN worked #on the last version that Homebrew Browser had. I posted about it on the GBAtemp forms and someone else confirmed it.  Could anyone take a look at this?  Thanks.

**Comment by saulfabregwiivc** [comment]
A small info: it last worked on 1.7.5RC1 r24-10-2021 build but i can't recall in what exact build or commit caused this issue.

**Comment by ekeeke** [comment]
Try to delete your config.ini file (in sd:/genplus) and see if it solves the problem.

I added a new setting recently to enanle/disable CD access time emulation and it's possible your config did not reset to default as it should when switching to last version and this setting is being loaded with an invalid value (it should be 0 or 1 but any  other value could indeed break CD compatibility).

**Comment by Sowden** [comment]
Sure enough.  Deleting my config.ini file did the trick.  Thanks for your help.

**Comment by ekeeke** [comment]
Thanks for the report, I still need to add some code robustness to prevent this.

**Comment by saulfabregwiivc** [comment]
I will try your suggestion, @ekeeke 

Anyways, even when this can be fixed temporally it needs a permanent fix :P

**Comment by ekeeke** [comment]
Yes, that's exactly what I said just above and the reason why I reopened this

**Comment by ekeeke** [comment]
This commit https://github.com/ekeeke/Genesis-Plus-GX/commit/e2fd222349772194dc15eb71ba021dad077812a7 bumps up config file version and will force config reset when loading older config file
