### ISSUE TITLE
[Wii] Request for UStealth Support

### ISSUE THREAD

**Issue by Sowden** [ekeeke/Genesis-Plus-GX#439]
Hey guys.  I have found some old compiles from like, 5 years ago with UStealth support, but I've found that it's not currently in the latest build.  Is it possible to add this for the versions going forward?

**Comment by ekeeke** [comment]
I have no idea what is UStealth support and nothing was ever added or removed in this emulator regarding this: it's probably something supported by libogc (or hacked versions of it ?) so there is nothing I can do on emulator side about it.

**Comment by Sowden** [comment]
Sorry if I wasn't clear enough.  UStealth is a program on Windows and Wii Homebrew.  Usually, if the Wii U senses a NTFS or Fat32 partition it will ask if you want to format it at every boot.  UStealth "hides" the drive from being detected so you don't get that nagging message.  There are other uses for it too, but the point is that UStealth hides the hard drive from being seen.  So multiple different apps add support for UStealth so that it can see a hard drive, even if it is hidden.  More can be read about it at the link below, including some threads talking about it, a compile of Genesis Plus GX from 2015, and an example of it being added to Not64.  Maybe this clairafies a few things?

https://gbatemp.net/threads/ustealth-wii-u-format-disk-nag-workaround.352786/
https://github.com/rudism/ustealth.sh/blob/master/README.md
https://github.com/extremscorner/libfat/commit/ed80203824de3ae6bf118bdd654cbcf0a66ab658

**Comment by saulfabregwiivc** [comment]
i've made a PR to main libfat for add UStealth support (https://github.com/devkitPro/libfat/pulls)
I hope this can be merged :)

So most Wii homebrew can have UStealth support :)

**Comment by Sowden** [comment]
Thanks guys, you all are the best.

**Comment by saulfabregwiivc** [comment]
@ekeeke @Sowden 

I don't know if you want to make and publish a test build of GPGX but with my custom libFAT with the latest commits from SVN and the UStealth support but this could help for this request?: https://github.com/saulfabregwiivc/libfat/releases/tag/v1.1.5-SVN-27062020-UStealth

**Comment by Sowden** [comment]
Thanks @saulfabregwiivc , I could take that file you made and make a private compile.  But I'd rather have @ekeeke implament it to the public daily so that it can be implamented going forward.  That way everyone can enjoy it.

**Comment by ekeeke** [comment]
New builds are now done using libfat 1.1.5 patched with UStealth Mod from this commit https://github.com/ekeeke/Genesis-Plus-GX/commit/e2fd222349772194dc15eb71ba021dad077812a7

**Comment by Sowden** [comment]
Fantastic, it works!  Thanks guys.

**Comment by saulfabregwiivc** [comment]
@ekeeke 

I saw in some code of my libFAT mod with UStealth but some homebrew have problems with it, so i've modified it again and i published again the libfat 1.1.5 with UStealth support.

https://github.com/saulfabregwiivc/libfat/releases/tag/v1.1.5-other-vers-UStealth

Since you're using latest stable libFAT 1.1.5 with my UStealth, please replace your old libfat with the new one.
It was tested and working properly on most homebrew apps.

**Comment by ekeeke** [comment]
Not sure what you are referring to but I am not using your modded library, I am patching and compiling libfat 1.1.5 myself.
