### ISSUE TITLE
RA Wii Genesis-Plus-GX

### ISSUE THREAD

**Issue by RunningSnakes73** [ekeeke/Genesis-Plus-GX#441]
RA Wii has been unplayable since 1.9.0. It is impossible to even load the Genesis-Plus-GX, resulting in black screen freeze and hard reset is required. The Wide core does work but many use the original RA core as Wiiflow Lite plugin. Hopefully this issue can be resolved soon.

**Comment by ekeeke** [comment]
I am not responsible of Retroarch Wii port or libretro port of this emulator so you will have to deal with retroarch developers.

**Comment by RunningSnakes73** [comment]
Thanks for your response.
