### ISSUE TITLE
"Unable to open directory !" error on Gamecube

### ISSUE THREAD

**Issue by NSilky** [ekeeke/Genesis-Plus-GX#442]
I downloaded the latest version of Genesis Plus GX on my Gamecube and tried several ways but i cannot play any files. When I first open the .dol i read that it should create a genplus folder to the root, but it doesn't. I tried downloading this collection (https://mega.nz/file/g8JkHITQ#kvBfIhfwm3a-BeiyEEgsalosQdNpsCFGXnyCdf5e38Y) based on this recommendation (https://www.youtube.com/watch?v=_rYVWzjVWmw&t=676s) and followed all of his steps. I got all the other systems to work but the Sega emulator. I could sure use some help, my wife really needs to play the Ninja on the Master emulator.

**Comment by ekeeke** [comment]
What device do you use to insert a SD card ? SD Gecko adapter or something else ?
It is possible the emulator version in that pack is outdated: try using the latest genplus_cube.dol from https://github.com/ekeeke/Genesis-Plus-GX/tree/master/builds

It is also possible your SD card is write-protected so the emulator indeed cannot create the /genplus directory and fail to open the file browser when you try to load a game as it tries to open /genplus directory by default and browse from here: try creating this directory manually on your PC and copy your ROM files in there (you can use subdirectories).

**Comment by NSilky** [comment]
Thank you so much for replying, that new file fixed it. That was my fault
entirely, i thought i had the latest but i am completely new to github and
only created an account to mod my old gamecube. My next question (and maybe
this isn't doable otherwise it would have been done already) but is there a
way to add your Genesis Plus GX logo to the .dol program so it would show
up in my swiss menu? Again forgive my ignorance but this is all new to me.
If there isn't, thank you anyway, I got my wife's old games to play and
that's what i needed.

**Comment by ekeeke** [comment]
> is there a way to add your Genesis Plus GX logo to the .dol program so it would show up in my swiss menu? 

You will need to ask the developers of Swiss application if it is able to display associated png files when browsing dol files, in which case you could simply reuse rhe png logo that comes with the wii dol (for wii homebrew channel). 
It is afaik not possible to embedd a banner in dol files like it is done in official gamecube games as those are different file formats.
