### ISSUE TITLE
Is it possible to implement .32x, .pco, .sc, .sf7, .rom, .mv to possible ROM file extension

### ISSUE THREAD

**Issue by CraftFan23** [ekeeke/Genesis-Plus-GX#443]
@ekeeke is it possible to implement .32x, .pco, .sc, .sf7, .rom, .mv to possible ROM file extension

.32x - Sega 32x

.pco - Sega Pico

.sc - Sega SC-3000

.sf7 - Sega SF-7000

.rom

.mv - MV

**Comment by ekeeke** [comment]
No, support for these system is not planned

**Comment by CraftFan23** [comment]
Edit: 32x, Pico, SC-3000, SF-7000, MV are not planned
