### ISSUE TITLE
Bomber (R) (MD) doesn't work

### ISSUE THREAD

**Issue by ghost** [ekeeke/Genesis-Plus-GX#444]
I found issue on Genesis Plus GX: Bomber (R) (MD) doesn't work on Genesis Plus GX. It fine works on other Emulators. Is it possible to fix Issue on Bomber (R) (MD).

NOT WORKING:
![Bomber (R)-220715-225455](https://user-images.githubusercontent.com/106222943/179310792-88bdaf91-de47-4332-b72f-9b66af74708f.png)

WORKING:
![Bomber (R)-220715-225515](https://user-images.githubusercontent.com/106222943/179310819-c1645655-c21f-4014-9503-5dbceeda7ec4.png)
![Bomber (R)-220715-225533](https://user-images.githubusercontent.com/106222943/179310826-be5ca864-e0d6-4d62-9abb-8a52a8167f68.png)

**Comment by birdybro** [comment]
I'm confused why it has a (R) at the end, isn't this a Brazilian clone of Bomberman?

**Comment by ekeeke** [comment]
I removed the link as I doubt that person actually reads/understands what other writes.

Anyway, this game works fine in current emulator version (tested with private windows/sdl build and with retroarch win32 + libretro core available [here](https://github.com/ekeeke/Genesis-Plus-GX/blob/master/builds/genesis_plus_gx_libretro.dll)) so you are either using an outdated/modified version of the emulator or there is a problem with your settings.

**Comment by CraftFan23** [comment]
I'm NOT using outdated/modified version of the Emulator. I'm using current Emulator version

https://user-images.githubusercontent.com/106222943/179469151-943c8799-b2d4-4030-bb75-f8e5fb6e2ee7.mp4

**Comment by ekeeke** [comment]
Then it is either a problem specific to the version distributed by retroarch (which has some modifications comparing to the version I maintain, mostly related to retroarch specific features like run-ahead or cpu overclock I think) or a problem with the core settings you are using (make sure settings like system, region, etc are set to auto).

In both cases there is nothing I can 'fix' on my side: as I said above, that game is working fine for me.
