### ISSUE TITLE
Question: where is the "Remove Per-Line Sprite Limit" option located in the libretro .dll file?

### ISSUE THREAD

**Issue by Mint128** [ekeeke/Genesis-Plus-GX#447]
Hello. That one option is disabled by default, which I assume would translate to a "00" in the libretro's .dll file. I'd like to hex edit that into "01" and then save the .dll to make the change permanent, just for personal use. But of course there are countless 00's in that file, and I don't know which is the correct one. Could anyone please point me to the right address that needs to be modified?

**Comment by ekeeke** [comment]
You should ask retroarch developers, not me as I am not part of retroarch or libretro team, but I doubt you will get any answer as there is no straight or known relation between dll file and code so you are on your own if you want to hack a dll. To me, it seems more straightforward to simply set this option as you want and save it in core default config file. Or get the code from github, modify default value in code and compile a new dll.

**Comment by Mint128** [comment]
Thanks for the answer. And sorry for posting again in an issue that was already closed, but:

> Or get the code from github, modify default value in code and compile a new dll.

I thought of doing that as well, but as stupid as it may sound, I don't know how to compile a new dll. I tried looking for some guides online but it seems very confusing for a complete newbie like me. So, I downloaded the "Genesis-Plus-GX-master" folder from here, opened the "libretro_core_options.h" file inside the libretro subfolder, used notepad to edit the appropriate sprite limit line from "disabled" to "enabled", then saved the changes. Assuming I'm on the right track so far, what do I do next? I heard that Visual Studio is involved, so I installed it but don't know what to do there exactly. I'd appreciate if you could tell what file I need to open with it and the step by step on how to compile the modified dll.

**Comment by ekeeke** [comment]
I have no idea how yo compile with Visual Studio, I personally have MSYS2 and MINGW32 installed and just run `make -f Makefile.libretro` to build the dll. Again, I am not part of libretro team, I only maintain Genesis Plus GX emulation core (which is an independent project from retroarch/libretro) so if you want support to compile libretro cores, you will have to seek help on libretro support channels.
