### ISSUE TITLE
add changing TMS color palette option

### ISSUE THREAD

**Issue by SteveCraft08** [ekeeke/Genesis-Plus-GX#451]
There are diffrence TMS palettes:

TMS9918
![Congo Bongo (SG-1000) 1](https://user-images.githubusercontent.com/110945884/183780878-bfc4a28f-8d19-41da-9f05-7b7a28a0d931.png)
![Congo Bongo (SG-1000) 2](https://user-images.githubusercontent.com/110945884/183780888-3af7b36c-339a-4a49-8d0a-ddf804c53508.png)
Sega VDP (SMS)
![Congo Bongo (SMS) 1](https://user-images.githubusercontent.com/110945884/183780892-b8addcdc-2e7f-467e-b55a-b5da419a6569.png)
![Congo Bongo (SMS) 2](https://user-images.githubusercontent.com/110945884/183780922-2c2cfd92-adf9-4386-b494-5b01c787a08d.png)
TMS9928
![Congo Bongo (GG) 1](https://user-images.githubusercontent.com/110945884/183780930-0422e4a6-cfdc-4f96-b066-9d7fed74add3.png)
![Congo Bongo (GG) 2](https://user-images.githubusercontent.com/110945884/183780935-554ec7d9-70b7-4dea-941e-887c489948c2.png)
Yamaha V9938 
![Congo Bongo (YM) 1](https://user-images.githubusercontent.com/110945884/183780953-731bcc9e-60ad-449d-97b8-48f46e38dce6.png)
![Congo Bongo (YM) 2](https://user-images.githubusercontent.com/110945884/183780962-98fb9c24-a11c-4496-afea-42ab53c04290.png)

I'm NOT Spamming

**Comment by KMFDManic** [comment]
@SteveCraft08 is there any reason u keep making fake accounts over and over and over and over and over again? You do realize you are gonna end up making him shut down ability to even create issues if u don't stop being such an rude person.  You are doing no good for this core, just annoying the one person who can make it better to the point that he will have no interest in even reading the issues anymore.  You've already made over 30 accounts and spammed the hell out of this repo.  Dont you think you've already wasted enough of his time?

**Comment by ekeeke** [comment]
Duplicate of #413, #414 and #415

**Comment by ekeeke** [comment]
For the record, I emulate the palette of the VDP used in supported hardware: SG-1000 hardware uses TMS9928 VDP so it uses TMS palette when SG-1000 hardware is emulated and Master System hardware uses Sega VDP so it uses Sega saturated palette for Master System games that use TMS legacy modes. I see no reason to support palettes of unemulated hardware.
