### ISSUE TITLE
32x, SC-3000, SF-7000 support?

### ISSUE THREAD

**Issue by MineBraktd** [ekeeke/Genesis-Plus-GX#452]
Enhancement request for Sega 32x, SC-3000 - Sega Computer, SF-7000 - Sega Super Control Station support. Is this a possibility or totally out of the question?

File extensions: .32x, .sc, .sf7

**Comment by KMFDManic** [comment]
@MineBraktd and, here you are yet again, with the 31st+ fake account.  And, you've already asked for 32x support several times and been told it would not be added to the core.  Yet, you continue to make fake accounts and create issues with unreasonable requests that aren't even going to be reasonably feasible to add.  You truly need to move on and stop harassing his repo, already.  What will you do once he locks down issues so noone can create them?

**Comment by ekeeke** [comment]
Duplicate of #415 and #443
