### ISSUE TITLE
[RetroArch PSP] Genesis Plus GX Isn't visible on RetroArch PSP

### ISSUE THREAD

**Issue by SteveCraft2244** [ekeeke/Genesis-Plus-GX#456]
Genesis Plus GX isn't visible on RetroArch for **PlayStation Portable** port

I don't know will Genesis Plus GX lag/slow down on PlayStation Portable hardware and will explode PlayStation Portable. Is Genesis Plus GX an extremely accurate

**Comment by birdybro** [comment]
Hi SteveCraft22440980982340987,

This is the wrong repository. for this issue. Please submit this to one of retroarch's repositories on github instead.

Thanks.
