### ISSUE TITLE
libretro native analog support

### ISSUE THREAD

**Issue by soundsnow** [ekeeke/Genesis-Plus-GX#458]
Sega - Mega Drive - Genesis
Paddle Fighter (Japan) (SegaNet)
Paddle Fighter (Japan) (Game no Kanzume Otokuyou)
ice hockey games

**Comment by ekeeke** [comment]
1- this is not a proper issue report, please learn to make understandable sentences to explain your  issue or request

2- this is not libretro core support repository, you will have to address this with libretro devs
