### ISSUE TITLE
Musashi incorrectly implements bra.l and bsr.l on 68000

### ISSUE THREAD

**Issue by GerbilSoft** [ekeeke/Genesis-Plus-GX#46]
While looking through the Musashi code, I noticed that it incorrectly generates opcodes for bra.l and bsr.l when targetting 68000. These instructions were introduced on 68020, and are invalid on 68000. They should act like bra.s $1, which ends up getting trapped as an Address Error.

To fix this, in m68ki_instruction_jump_table.h, change the following:

* m68k_op_bra_32 -> m68k_op_bra_8
* m68k_op_bsr_32 -> m68k_op_bsr_8
* m68k_op_bhi_32 -> m68k_op_bhi_8
* m68k_op_bls_32 -> m68k_op_bls_8
* m68k_op_bcc_32 -> m68k_op_bcc_8
* m68k_op_bcs_32 -> m68k_op_bcs_8
* m68k_op_bne_32 -> m68k_op_bne_8
* m68k_op_beq_32 -> m68k_op_beq_8
* m68k_op_bvc_32 -> m68k_op_bvc_8
* m68k_op_bvs_32 -> m68k_op_bvs_8
* m68k_op_bpl_32 -> m68k_op_bpl_8
* m68k_op_bmi_32 -> m68k_op_bmi_8
* m68k_op_bge_32 -> m68k_op_bge_8
* m68k_op_blt_32 -> m68k_op_blt_8
* m68k_op_bgt_32 -> m68k_op_bgt_8
* m68k_op_ble_32 -> m68k_op_ble_8

**Comment by ekeeke** [comment]
If you look closer to m68kop_b**_32 functions in m68kops.h, you can see it's already the case and they all behave like their 8-bit counterpart.

**Comment by GerbilSoft** [comment]
I see that now. Oops. :V
