### ISSUE TITLE
[Libretro] Multi-line cheats crash the core

### ISSUE THREAD

**Issue by ds22x** [ekeeke/Genesis-Plus-GX#468]
https://github.com/ekeeke/Genesis-Plus-GX/commit/98b5c603557f0ce3bbf347c2f75c1412288ec66c is causing crashes when enabling multi-line cheat codes in RetroArch.
Tested the commit with both the upstream and the downstream cores, and both exhibit the same issue (tested on x86-64 Windows 11).

Edit:
Seems to have already been reported here:
https://github.com/ekeeke/Genesis-Plus-GX/issues/445#issuecomment-1288135110

**Comment by ekeeke** [comment]
Indeed, looks like I completely messed up when backporting changes from the gamecube/wii port into libretro.c so that commit totally broke cheat support in the libretro core.

I will submit a fix shortly, thanks for the report

**Comment by ekeeke** [comment]
Should now be fixed after https://github.com/ekeeke/Genesis-Plus-GX/commit/90bb356a173dc1010d6694bdb470c176efd9c03b

**Comment by ds22x** [comment]
Glad to help, and thanks for the fix.
