### ISSUE TITLE
[Sega CD] 7z file extension load support

### ISSUE THREAD

**Issue by John7wg** [ekeeke/Genesis-Plus-GX#469]
Right now I have the files for the Sega CD in iso + ogg format, but some games have many files and it would be much better to have each game in a single .7z file that contains the iso file plus the multiple ogg audio tracks of the game.

**Comment by ekeeke** [comment]
That is not possible for CD games as they need to be read from disc continuously during emulation and 7zip is not a suitable format for that so it would require CD games to be fully decompressed into memory on load, which would result in much longer loading time and much larger RAM use.

I am not exactly sure why exactly having lesser files is 'better' but if you want to save space, you can convert CD games into chd files, which are single AND compressed CD image files and are supported by this emulator.
