### ISSUE TITLE
No signal detected when I unpause the game.

### ISSUE THREAD

**Issue by RyanX6969** [ekeeke/Genesis-Plus-GX#480]
I am trying to play Blockout on the emulator but when I load into the game my tv doesn't detect the signal, but when I pause the game the tv detects a signal and shows the pause menu. This is very strange, I recorded a video about the issue.

https://cdn.discordapp.com/attachments/1012178797203820596/1064301677978583150/IMG_6997.mov

**Comment by ekeeke** [comment]
Change Display setting to INTERLACED (or PROGRESSIVE if you have a component cable) in VIDEO option menu: your TV probably does not support original non-interlaced video mode.

**Comment by RyanX6969** [comment]
It works now, thank you! :)
