### ISSUE TITLE
Add option to "M3U Name" to keep Disc numbers for Game Bezel integration

### ISSUE THREAD

**Issue by mtyrealhanla** [ekeeke/Genesis-Plus-GX#481]
This is more of a feature request than an "issue", but my use case is that I use [The Bezel Project](https://github.com/thebezelproject/BezelProject) RetroArch integration. This integration requires that the content loaded in the core matches the config file in that core, which then points to a png of a bezel for that particular game. 

I can use the "Title+Version" option which keeps bezels working properly for single disc games since those game names do not have "(Disc X)" in the name of the file. But when creating the m3u file for a a multi-disc game, using "Title+Version" loses the "(Disc X)" in the m3u name, which causes a mismatch in the GameBezels name so it falls back to a default platform bezel.

Not a huge deal, but I think it would be a good option. Figured I would go ahead write this up in the case I don't get the time to crack open the code myself :) 

![image](https://user-images.githubusercontent.com/10082024/214720531-13bad965-c6a6-44ad-afaf-3b3151364f8f.png)

**Comment by ekeeke** [comment]
Sorry but I am only responsible for the emulation core and don't know much about libretro or retroarch specific options so I have no idea what this is all about. You should re-open this in libretro fork repository (https://github.com/libretro/Genesis-Plus-GX/issues) where libretro/retroarch devs can see it.

**Comment by mtyrealhanla** [comment]
apologies this somehow got linked to the incorrect repo :)
