### ISSUE TITLE
Border Left/Right, Full (256px width mode) should not be 284px width

### ISSUE THREAD

**Issue by SopTheSop25** [ekeeke/Genesis-Plus-GX#483]
@ekeeke the border left/right, full overscan area (256px width mode) should not be 284px width, it should be **280px width**
SG-1000/Master System has entire overscan of 280x240 on NTSC, 280x288 on PAL (Also on Genesis/Mega Drive with 256px width mode)
Game that has resolution of 256x192, 256x212, 256x224, 256x240 and 256x288

284px width
![284x240 Alex Kidd in Miracle World SMS](https://user-images.githubusercontent.com/123488084/218166656-a20d2755-f726-412a-9435-c0757165179c.png)
![284x240 Mega Bomberman MD](https://user-images.githubusercontent.com/123488084/218166645-e60ee112-456c-4de2-98a1-84dd090bfa2f.png)
![284x240](https://user-images.githubusercontent.com/123488084/218166649-e518076d-c5c3-4040-9466-2486a2433654.png)

280px width (real hardware)
![280x240 Alex Kidd in Miracle World SMS](https://user-images.githubusercontent.com/123488084/218166638-f845ef7d-7b85-4b60-9ab8-8728cefa94cc.png)
![280x240 Mega Bomberman MD](https://user-images.githubusercontent.com/123488084/218166651-498c2322-6ad0-4714-817d-861e83b0dece.png)
![280x240](https://user-images.githubusercontent.com/123488084/218166658-a7de746e-9772-45ad-8f34-9c3f5c650e63.png)

**Comment by ekeeke** [comment]
This is incorrect. Left and right borders are actually 15  and 13 pixels wide so 256 + 13 + 15 = 284 pixels in total. This is described precisely in TMS99xx programmer manual and has been verified to be the same with Master System and Mega Drive VDPs.
