### ISSUE TITLE
Request: Overclocking more than 200%

### ISSUE THREAD

**Issue by ivan89el** [ekeeke/Genesis-Plus-GX#485]
For some games, 200% is not enough to be smoother (Road Rash series). It would be nice to have an additional 400-800%. Sorry for my English

**Comment by ekeeke** [comment]
400% (x8) is not possible

**Comment by saulfabregwiivc** [comment]
i've opened a PR ;) https://github.com/ekeeke/Genesis-Plus-GX/pull/488
