### ISSUE TITLE
[Wii] [Feature Request] Overclock more than x3 (300%)

### ISSUE THREAD

**Issue by saulfabregwiivc** [ekeeke/Genesis-Plus-GX#489]
based on issue https://github.com/ekeeke/Genesis-Plus-GX/issues/485

Hi @ekeeke,

Overclocking functions for Sega Genesis / Mega Drive games on Genesis Plus GX (native GX port, not Libretro) are neat, but at least on the official Wii port (this one), the overclock of main Motorola M68000 chip is limited to just x3.0 (300%).

And some games (such the Road Rash trilogy) doesn't run very smoothly even when overclocked at 300%, meaning that these speeds are not enough for these and a few more games.

I would ask you if you can add more speeds to the overclocking options to the Wii port of GPGX, to the max possible speeds you told us at this post https://github.com/ekeeke/Genesis-Plus-GX/pull/488

> Increasing MAIN 68K overclock above 700% makes no sense as the limit is the master clock speed (m68k is originally 1/7 of master clock speed so overclock cannot go beyond 7x, which correspond to 53 MHz anyway, so well beyond anything realistic regarding 68k overclock). Similarely, SUB 68K overclock will be limited to 4x i e 50MHz which is Mega CD master clock speed.

Maybe for the Wii port could you increase overclock speed limits to:
Main M68K: 1x-7x (100%-700%)
Sub M68K: 1x-4x (100%-400%)

Not to mention your port runs pretty well optimized on Wii.

(PD: i'm mentioning only the Wii port because the GC is not powerful for use these overclock speeds)

Thanks a lot, @saulfabregwiivc

**Comment by ekeeke** [comment]
CPU overclock limits bumped up to maximal values in https://github.com/ekeeke/Genesis-Plus-GX/commit/a7220d2408bd377cf8224a81ba7f1c10e1c785c2
