### ISSUE TITLE
[Libretro] Lightgun Crosshair Shows Even When Set to Off

### ISSUE THREAD

**Issue by Awakened0** [ekeeke/Genesis-Plus-GX#49]
In the libretro port, I can load up Snatcher and the crosshair doesn't go away even when set to off in the core options.

**Comment by ekeeke** [comment]
Fixed along "Invert Mouse Y Axis" and "Interlaced Mode 2 output" settings in https://github.com/ekeeke/Genesis-Plus-GX/commit/8d2a466ca336b3ba7643455e460bc213c91dc02b
