### ISSUE TITLE
All the links to bitbucket.org went rancid

### ISSUE THREAD

**Issue by MayanKoyote** [ekeeke/Genesis-Plus-GX#490]
It would be nice to update the README.md.
All the links to bitbucket.org went rancid, and there are a lot of them.

**Comment by ekeeke** [comment]
Wtf. Looks like the bitbucket respository is not visible anymore or got deleted. I would prefer having it restored as it contains some other things that are not preserved locally (issues and downloads). I am not even sure those linked pages were preserved locally.

**Comment by ekeeke** [comment]
I have added the wiki pages into github repository: all links should now be fixed

**Comment by MayanKoyote** [comment]
Any information on why bitbucket.org did that? And the repository is/was just closed there or was deleted?

**Comment by ekeeke** [comment]
Apparently it was deleted for violating their TOS but I have no idea why exactly and nevetmr received any warning or deletion notice, so I asked for clarification. It is currently under investigation/analysis on their side.
