### ISSUE TITLE
RetroArch Savestates for Mega CD Game No Longer Loading

### ISSUE THREAD

**Issue by HardDiskDog** [ekeeke/Genesis-Plus-GX#491]
i've been playing sonic cd (japanese version for the soundtrack + 60hz) in retroach version e3c92b0 on windows 11 pro 22h2, and had made multiple savestates for the game. up until now i'd been playing it in multitrack bin/cue format, but today (after having added some other games) i decided to save some hard disk space by switching to a chd version of the game and deleting the old bin/cue sonic cd folder. now, none of the states i made for the bin/cue version will load

i've tried restoring the bin/cue folder to its original location from the recycling bin, deleting the chd rip entry from the mega cd playlist, having retroarch generate a subfolder for gpgx states and then moving the old states into there; no dice. the srm file is also still dated from yesterday, so i don't think that's related. i was one zone away from 100%'ing the game, so i'd like to be able to resume from there

**Comment by ekeeke** [comment]
I do not see how I could be any help. savestates are working fine however they are tied to a specific game version and core version so you should verify that:
-  state files created with current setup have same version as the state file you are trying to load (version can be seen via hex editor in the 16 first characters of the state file)
- you are respecting any restriction existing in retroarch between state filename and game filename
- the state files you are trying to load did not get overwritten when you tried to run another version of the game

It is not clear either what you exactly mean by savestate "will not load"  (does it crash the game ? or just do nothing ?) and "having retroarch generate a subfolder for gpgx states " as I am not familiar with how retroarch deals with savestates so I suggest you rather ask for support to retroarch/libretro team as this does not look like a core issue.
