### ISSUE TITLE
Enhancement: Control Menus with Second Controller

### ISSUE THREAD

**Issue by Sowden** [ekeeke/Genesis-Plus-GX#493]
Just as it says.  I'm able to map my buttons from my second controller to act as the Genesis first controller, and that works great.  But once I open the menu I have to use the first controller to navigate.  Could this be added?  Thanks.

**Comment by ekeeke** [comment]
Could you test this build and see if it works as expected (menu can be controlled by any controller port) ?
I don't have a way to test it myself.
Thanks
[genplus_wii_test_26_03_2023.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/11071423/genplus_wii_test_26_03_2023.zip)

**Comment by Sowden** [comment]
Well, I was expecting a Gamecube test, but I never specified that in my post, my bad.  However, I tested it on my vWii, and it worked like a charm.  Thanks so much for adding it.  I'll be awaiting an updated build in the nightlies.

**Comment by ekeeke** [comment]
Added in https://github.com/ekeeke/Genesis-Plus-GX/commit/94399728b80fa7e25ab99691dca3430dedfd64f1
