### ISSUE TITLE
Can Sega CD add support for pre-gap format Cue(redump)?

### ISSUE THREAD

**Issue by napdh** [ekeeke/Genesis-Plus-GX#495]
I notice there is a 1~2sec delay from redump ISOs but it is normal if you use other format ISOs.
It is because redump record pre-gap in files (for ultimately 1:1 copy).
take final fight CD for example:

# redump's cue
FILE "final fight cd (japan).bin" BINARY
TRACK 01 MODE1/2352
INDEX 01 00:00:00
TRACK 02 AUDIO
PREGAP 00:02:00
INDEX 01 02:39:69
TRACK 03 AUDIO
PREGAP 00:01:74
INDEX 01 04:49:71
TRACK 04 AUDIO
PREGAP 00:01:74
INDEX 01 07:04:65
TRACK 05 AUDIO
PREGAP 00:01:74
INDEX 01 09:14:05
TRACK 06 AUDIO
PREGAP 00:01:74
INDEX 01 11:21:47
TRACK 07 AUDIO
PREGAP 00:01:74
INDEX 01 14:35:72
TRACK 08 AUDIO
PREGAP 00:01:74
INDEX 01 16:41:53
TRACK 09 AUDIO
PREGAP 00:01:74
INDEX 01 18:38:09
TRACK 10 AUDIO
PREGAP 00:01:74
INDEX 01 20:50:74
TRACK 11 AUDIO
PREGAP 00:01:74
INDEX 01 23:01:12
TRACK 12 AUDIO
PREGAP 00:01:74
INDEX 01 25:10:53
TRACK 13 AUDIO
PREGAP 00:01:74
INDEX 01 28:01:19
TRACK 14 AUDIO
PREGAP 00:01:74
INDEX 01 28:08:73
TRACK 15 AUDIO
PREGAP 00:01:74
INDEX 01 28:18:74
TRACK 16 AUDIO
PREGAP 00:01:74
INDEX 01 28:31:57
TRACK 17 AUDIO
PREGAP 00:01:74
INDEX 01 28:40:12
TRACK 18 AUDIO
PREGAP 00:01:74
INDEX 01 30:40:62
TRACK 19 AUDIO
PREGAP 00:01:74
INDEX 01 30:54:64
TRACK 20 AUDIO
PREGAP 00:01:74
INDEX 01 31:05:64
TRACK 21 AUDIO
PREGAP 00:01:74
INDEX 01 33:08:32
TRACK 22 AUDIO
PREGAP 00:01:74
INDEX 01 33:22:08
TRACK 23 AUDIO
PREGAP 00:01:74
INDEX 01 36:36:11
TRACK 24 AUDIO
PREGAP 00:01:74
INDEX 01 38:47:20
TRACK 25 AUDIO
PREGAP 00:01:74
INDEX 01 41:07:62
TRACK 26 AUDIO
PREGAP 00:01:74
INDEX 01 41:30:36
TRACK 27 AUDIO
PREGAP 00:01:74
INDEX 01 41:54:28
TRACK 28 AUDIO
PREGAP 00:01:74
INDEX 01 42:18:09
TRACK 29 AUDIO
PREGAP 00:01:74
INDEX 01 43:08:42

# other ISO's

FILE "FINAL_FIGHT.BIN" BINARY
TRACK 01 MODE1/2352
INDEX 01 00:00:00
TRACK 02 AUDIO
PREGAP 00:02:00
INDEX 01 02:39:69
TRACK 03 AUDIO
INDEX 00 04:49:71
INDEX 01 04:51:70
TRACK 04 AUDIO
INDEX 00 07:06:64
INDEX 01 07:08:63
TRACK 05 AUDIO
INDEX 00 09:18:03
INDEX 01 09:20:02
TRACK 06 AUDIO
INDEX 00 11:27:44
INDEX 01 11:29:43
TRACK 07 AUDIO
INDEX 00 14:43:68
INDEX 01 14:45:67
TRACK 08 AUDIO
INDEX 00 16:51:48
INDEX 01 16:53:47
TRACK 09 AUDIO
INDEX 00 18:50:03
INDEX 01 18:52:02
TRACK 10 AUDIO
INDEX 00 21:04:67
INDEX 01 21:06:66
TRACK 11 AUDIO
INDEX 00 23:17:04
INDEX 01 23:19:03
TRACK 12 AUDIO
INDEX 00 25:28:44
INDEX 01 25:30:43
TRACK 13 AUDIO
INDEX 00 28:21:09
INDEX 01 28:23:08
TRACK 14 AUDIO
INDEX 00 28:30:62
INDEX 01 28:32:61
TRACK 15 AUDIO
INDEX 00 28:42:62
INDEX 01 28:44:61
TRACK 16 AUDIO
INDEX 00 28:57:44
INDEX 01 28:59:43
TRACK 17 AUDIO
INDEX 00 29:07:73
INDEX 01 29:09:72
TRACK 18 AUDIO
INDEX 00 31:10:47
INDEX 01 31:12:46
TRACK 19 AUDIO
INDEX 00 31:26:48
INDEX 01 31:28:47
TRACK 20 AUDIO
INDEX 00 31:39:47
INDEX 01 31:41:46
TRACK 21 AUDIO
INDEX 00 33:44:14
INDEX 01 33:46:13
TRACK 22 AUDIO
INDEX 00 33:59:64
INDEX 01 34:01:63
TRACK 23 AUDIO
INDEX 00 37:15:66
INDEX 01 37:17:65
TRACK 24 AUDIO
INDEX 00 39:28:74
INDEX 01 39:30:73
TRACK 25 AUDIO
INDEX 00 41:51:40
INDEX 01 41:53:39
TRACK 26 AUDIO
INDEX 00 42:16:13
INDEX 01 42:18:12
TRACK 27 AUDIO
INDEX 00 42:42:04
INDEX 01 42:44:03
TRACK 28 AUDIO
INDEX 00 43:07:59
INDEX 01 43:09:58
TRACK 29 AUDIO
INDEX 00 44:00:16
INDEX 01 44:02:15

**Comment by birdybro** [comment]
Simplified comparison side by side to show what is being described.

![image](https://user-images.githubusercontent.com/16388068/225927234-7146d5b5-5424-46ad-9aea-8dd6b3370773.png)

**Comment by ekeeke** [comment]
PREGAP command is already supported and actually indicates a pause that is NOT included in the file and must be added by emulator when replicatibg the TOC, as opposed to INDEX00 commabd which indicates a section before the track start (usually pause for Mega CD games) that is included in the file.

I just looked and Redump CUE files do not seem to use PREGAP commands (they use INDEX 00 commands instead) so it seems like you are using an invalid CUE file.

**Comment by napdh** [comment]
sorry. I found I use old chd isos from MESS and took it as newest redump's
ISOs.

杜文志 (Dou, Wen-Chih), TEL: 0911279205
東辰診所洗腎中心/亞東紀念醫院


ekeeke ***@***.***> 於 2023年3月18日 週六 上午3:38寫道：
