### ISSUE TITLE
Cannot load roms with the extension ".bin" in a zip package

### ISSUE THREAD

**Issue by crashGG** [ekeeke/Genesis-Plus-GX#496]
Platform / OS : win10 x64

Github hash: newest master

Issue:

Cannot load roms with the extension ".bin" in a zip package.
but can load roms with the extension ".md" in a zip package,and can load roms with ".bin" directly (not in a zip)

**Comment by ekeeke** [comment]
I do not provide x64 build for windows so I guess this is an issue with retroarch. You will have to ask support to retroarch/libretro devs as I am not responsible for it.

**Comment by crashGG** [comment]
Yes, this problem only occurs on 64bit builds. But I am not using libretro updated 64bit, I am using the source of your repository ,build by mingw64.
