### ISSUE TITLE
Support more mappers of Korean multicarts

### ISSUE THREAD

**Issue by litaniast** [ekeeke/Genesis-Plus-GX#500]
https://www.smspower.org/forums/19521-26thAnniversaryKoreanSMSMulticartsGalore1OngoingCompetitions

Recently, more SMS multicarts were dumped, especially, "Piguwang 7-hap" has the SMS version of Bugtris(a variation of Tetris, already dumped NES version) but they use their own mappers so emulators need to support them to play.

**Comment by ekeeke** [comment]
Added in https://github.com/ekeeke/Genesis-Plus-GX/commit/4a07f8a9f66a53aca9ba9aca188f6d70c33de425
