### ISSUE TITLE
[libretro] Some MSX2SMS hacked roms moving left continously

### ISSUE THREAD

**Issue by litaniast** [ekeeke/Genesis-Plus-GX#501]
I only used libretro, not gc/wii version yet

https://youtu.be/vCWn-vjZWXk
https://youtu.be/1dCqj26dfwA
I ran two MSX2SMS hacked roms in Genesis Plus GX libretro core, but both moves left continously even I didn't push left version.

All the input ports are same. (Auto, MD 6button, MD 3button and MS 2button)

Works well in other emulators like Gearsystem.

**Comment by ekeeke** [comment]
I cannot reproduce this issue neither in my SDL port or in my Retroarch setup with the latest .dll available on this repository so it is likely a Retroarch configuration issue or some Retrorach specific feature that causes this. Try disabling run-ahead to see if this changes something as this feature somehow hacks the input processing.

**Comment by litaniast** [comment]
When I set core option "Master System FM (YM2413)" turn to auto(default), that error isn't occur, but when I set that option to "on", that error occur.

**Comment by ekeeke** [comment]
Are these hacks compatible with Master System FM unit (or Japanese Master System with FM included) ?

If not, you should not force this option ON and leave it to AUTO (OFF by default for most games) as the FM unit is mapped in the same I/O port range as the controllers so if those hacks access controllers from one of the shared addresses, it will read FM unit state mixed with controller state, which can lead to such issue.

**Comment by litaniast** [comment]
Oops. sorry. It's the issue of those hacks, not Genesis Plus GX. They need to DETACH FM unit in Mark III(also in the real console), and no way to play in Japanese Master System(that has FM). (for emulator: need to disable Master System FM to play them) I checked SMSPower forum too lately.
