### ISSUE TITLE
Interpreting CRAM palette values

### ISSUE THREAD

**Issue by dread-pirate-johnny-spaceboots** [ekeeke/Genesis-Plus-GX#506]
I'm trying to parse the BBBGGGRRR bits from a dump of CRAM, but I'm having trouble reconciling the byte values I'm seeing with the colors being rendered.

I had assumed its 2 bytes per palette entry following the format laid out here: https://segaretro.org/Sega_Mega_Drive/Palettes_and_CRAM, but that doesn't seem to get me to the correct color values.

For example in this CRAM and palette dump-- I can't figure any way of getting from 0x00 0x19 to the second color in the first palette

[psiv-cram.ram.txt](https://github.com/ekeeke/Genesis-Plus-GX/files/11361045/psiv-cram.ram.txt)
![palette](https://user-images.githubusercontent.com/76140134/235347427-7efda995-4d2b-44c3-87b3-d2faea2b2644.png)

**Comment by ekeeke** [comment]
Sorry but I don't understand how this is related to this emulator you should probably rather seek support in MD programming forums/communities as this is not really the place for this
