### ISSUE TITLE
Astebros garbled graphics/crashing

### ISSUE THREAD

**Issue by joepogo** [ekeeke/Genesis-Plus-GX#511]
Hi eke, hope all is well with you. 

Recently a homebrew game called Astebros (of a prequel to demons of asteborg) was released in it's full version and this game exhibits many issues on GPGX. 

Tested on my Wii and latest retroarch. 

Once you load up the game the language options screen is immediately garbled and once in game when get to the map the map becomes garbled and then black screen crashes. 

The two demos work fine but the new full release does some weird bank switching as stated by the devs. 

This probably hasn't been reported yet due to the full release just coming out. 

Anyways, just putting it up here for you and thanks again for all you do!

https://www.kickstarter.com/projects/neofid-studios/astebros

**Comment by ekeeke** [comment]
Where does the ROM comes from ?
Open the ROM header in an hex editor and sees if it has "SEGA SSF" or something like that. If that's the case, changing this to "SEGA GENESIS" or "SEGA MEGADRIVE" (or "SEGA DOA" as in original Demons of Asteborg cartridge) should fix it.

**Comment by joepogo** [comment]
Hey Eke, 

Thanks so much for the response. Just took a peek at the header in a hex editor and it says:

SEGA DOA 
(C) SDGK 2023
NEOFID STUDIOS 2
023

No sign of SSF anywhere that i can see. :)

**Comment by ekeeke** [comment]
OK. What is the size of the ROM file ? Wii version has a maximal ROM size limited to 15MB currently (which was the size of their previous game) so if that game is larger, it will fail on Wii (but should work on Windows through Retroarch).

**Comment by joepogo** [comment]
The rom file is around 6mb if I remember correctly. If you need to, I can message you with what you need.

**Comment by ekeeke** [comment]
That's not a size issue, then.
Does it work in other emulators ?
I doubt they are using a new undocumented mapper since they are officially distributing ROM files for use in emulators but you never know.

**Comment by joepogo** [comment]
No, unzipped is 14.7mb. But it fails on genesis plus gx retroarch so def is not a size issue. 

I will send a message with some more info.

**Comment by ekeeke** [comment]
Found out some bug in SRAM bank-switching emulation for games that also uses ROM bank-switching (ROM banks were not preserved).
This is now fixed by https://github.com/ekeeke/Genesis-Plus-GX/commit/4bb149ba0b798294fbfc51de31a97af08c018542

**Comment by joepogo** [comment]
Great work as always eke! Thank you for all that you do!

**Comment by infval** [comment]
> Open the ROM header in an hex editor and sees if it has "SEGA SSF" or something like that. If that's the case, changing this to "SEGA GENESIS" or "SEGA MEGADRIVE" (or "SEGA DOA" as in original Demons of Asteborg cartridge) should fix it.

The updated rom from Steam has "SEGA SSF". Your advice is working.
