### ISSUE TITLE
Black screen after Astebros.bin loads

### ISSUE THREAD

**Issue by crashGG** [ekeeke/Genesis-Plus-GX#512]
Black screen after Astebros.bin loads. Build with latest master, win x64 platform,

Astebros.bin dumped from steam,size 15,466,496, CRC: F6700999

**Comment by ekeeke** [comment]
See https://github.com/ekeeke/Genesis-Plus-GX/issues/511

The Steam version of this game (and Demond of Asteborg as well afaik) has an incorrect ROM header (wrongly indicating use of Everdrive extended SSF2 mapper although it uses a different mapper which needs to be corrected (uqing an hex editor).

Replacing "SEGA SSF" by "SEGA MEGADRIVE", "SEGA GENESIS" or "SEGA DOA" (like the cartridge version) should work.

**Comment by crashGG** [comment]
Thanks a lot, this modification completely solves the problem

**Comment by ekeeke** [comment]
[This commit](https://github.com/ekeeke/Genesis-Plus-GX/commit/83ab969f293e94dcf47ec0a6db53396bd9b7405f) adds both Neofid games to internal mapper database so that ROM type field is ignored for these games so modifying Steam ROM header is not necessary anymore.
