### ISSUE TITLE
Daikoukai Jidai II Plus (Hack) (ReMake v1.9F3) keeps restarting

### ISSUE THREAD

**Issue by crashGG** [ekeeke/Genesis-Plus-GX#513]
Daikoukai Jidai II Plus (Hack) (ReMake v1.9F3) keeps restarting at sega logo
[MDDaikoukai Jidai II Plus(ReMake v1.9F3).zip](https://github.com/ekeeke/Genesis-Plus-GX/files/11830515/MDDaikoukai.Jidai.II.Plus.ReMake.v1.9F3.zip)

**Comment by ekeeke** [comment]
Tested the ROM on real Megadrive (with Mega Everdrive) and it does the same so it is probably a bug in the hack.
