### ISSUE TITLE
Sonic & Knuckles Lock On

### ISSUE THREAD

**Issue by KoyMcCloud** [ekeeke/Genesis-Plus-GX#516]
The Sonic and Knuckles Lockon function no longer works, any time I try to boot up Sonic 3 with the S&K Lock On activated, it simply starts as Sonic and Knuckles. I downloaded an earlier version of the core, and the lock on function works fine.

**Comment by ekeeke** [comment]
Indeed, there was a regression introduced by https://github.com/ekeeke/Genesis-Plus-GX/commit/4bb149ba0b798294fbfc51de31a97af08c018542

It has been fixed by https://github.com/ekeeke/Genesis-Plus-GX/commit/091b4124a8438a0420bee61595dcfa38a3471848
