### ISSUE TITLE
retro_get_memory_data returns only Genesis RAM (and not Sega CD's)

### ISSUE THREAD

**Issue by MatPoliquin** [ekeeke/Genesis-Plus-GX#518]
For some [project](https://github.com/Farama-Foundation/stable-retro) I need to access RAM data for the Sega CD.
For Genesis only games it works well but for Sega CD it doesn't so I took a look at retro_get_memory_data and it seems it only returns Genesis ram data.

I am not too familiar with Sega CD dev but looking at  the code I would guess if I return **scd.prg_ram** value instead of work_ram that would be enough?
Is there games that access both ram modules (Genesis + Sega CD) at same time?

`void *retro_get_memory_data(unsigned id)
{
   switch (id)
   {
      case RETRO_MEMORY_SAVE_RAM:
         return sram.on ? sram.sram : NULL;
      case RETRO_MEMORY_SYSTEM_RAM:
         return work_ram;
      default:
         return NULL;
   }
}`

**Comment by ekeeke** [comment]
I am not responsible of the libretro port and have no idea what this function is supposed to return or what it is used for so I suggest you ask that question to libretro devs on the libtretro fork repository.

And yes, Mega CD games use both CPU and so have access to Mega Drive Work RAM as well as Mega-CD PRG-RAM but also Word-RAM. To some extent you, it should expose all accesdible RAM (including Z80 RAM) so I guess you need to define the possible values of that 'id' parameter somewhere in the libretro core.
