### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Repliroid** [ekeeke/Genesis-Plus-GX#521]
Is it possible to put an overclock option to remove slowdown in games like retroarch?
And an option to hide overscan whitout distort the game image!

**Comment by ekeeke** [comment]
If you are talking about the GC/Wii version, there is already a CPU overclock option under SYSTEM options menu, just make sure you are using the latest build that can be found here: https://github.com/ekeeke/Genesis-Plus-GX/tree/master/builds

And there is also an option to disable colored borders if you like, as well as a manual scaling option if you don't like the default aspect ratio (which is however accurate to real hardware), all under VIDEO option menu.
