### ISSUE TITLE
[Request] Let GenPlusGx enter its menu with an analog gamecube button

### ISSUE THREAD

**Issue by almircanella** [ekeeke/Genesis-Plus-GX#522]
I've using blueretro and m30 to play 6 button games on genplusGX, and I think many people as well. 

-In 6 button control, megadrive has 8 digital buttons, gamecube has 8 as well, but in this situation, it needed one more...
-Blueretro connected joysticks buttons only works if assigned. m30 has more buttons than megadrive, that I linked to analog gamecube buttons. 
-GenplusGX wont let me assign an analog button to use as "Enter Menu". 

So the request is simple, let me use one. Then I will link it to some button on my m30, and configure it on the emulator.

**Comment by ekeeke** [comment]
Not sure what you exactly mean by "analog buttons" but pushing the C (yellow) analog stick to the right will let you enter emulator menu by default.

Alternativately, the configurable menu key combo let you map any combination of the 8 digital buttons + 4 directional buttons so I am sure you can find one combination that is usable with your controller setup (it is not necessary to assign one single button to menu key)

**Comment by almircanella** [comment]
Thanks anyway, Well. When using the blueretro, neither m30 button assigned with an analog gamecube button (c right) worked. Maybe it's m30 or blueretro fault then. I will look into the alternatives.

**Comment by almircanella** [comment]
So, I came back into this, sorry to disturb:

- Indeed"c stick" to the right enter the menu,config not needed. BUT when in the controller config, if I choose gamecube controller and 6 button megadrive controller, the menu will make me to press all the buttons to confgure, right? BUT the last one (menu) does not let me input any c stick direction. it does not recognizes.

MEGA DRIVE    |   NGC
       A                     A      
       B                     B  
       C                     X  
   START              START
      X                   DIGITAL L 
      Y                   DIGITAL R
      Z                      Y
 MODE                   Z    
 MENU                (genplus gx does not let me input c stick in here, wich is what I want, and I think, many m30/blueretro users.

**Comment by ekeeke** [comment]
>BUT the last one (menu) does not let me input any c stick direction. it does not recognizes.

This is used to configure menu key combo, using buttons that you press, an

alog sticks can not be used as they are not buttons technically. However c-stick will always be used to enter menu by default, no matter what menu key combo you define, so it does not matter what buttons combination you pick for MENU (pick one that you won't accidentally trigger while playing games, like MODE+START for example), you will still be able to use the c-stick if you prefer that to a buttons combo.

>also... How to configure the configurable menu combo? Could not find it...

Well, it is the last configurable key (MENU) in the controller config, I thought that it would be obvious... All you have to is to press buttons simultaneously (or successively while keeping each buttons of the wanted combo pressed) then release them for the key combo to be registered. For example, hold MODE and START buttons pressed then release them and now, every time those two buttons are pressed simutaneously during game, menu wiml be entered. But you can choose any combo that you want, using directional pads or buttons.

**Comment by almircanella** [comment]
I did it. Thanks. it was obvious, indeed...my bad.

For further reference, m30 controller and blueretroGC int this emulator, used:

-preset: merge analog r+l
-advanced config: changed some buttons to match all m/30 gamecube digital buttons, and M30 button Minus to mimic right c stick, to enter menu. **Still i had to configure the button combo** like ekeeke said, I was looking the wrong way to do this.

-now contra hardcorps + stationary hack: my body is ready.
