### ISSUE TITLE
More SMS multicarts dumped

### ISSUE THREAD

**Issue by litaniast** [ekeeke/Genesis-Plus-GX#523]
https://www.smspower.org/forums/19754-KoreanSMSMulticartsGalore2

Of course they use new mappers that need to implement on emulator.

**Comment by litaniast** [comment]
Another bunch of multicarts dumped. https://www.smspower.org/forums/19789-KoreanSMSMulticartsGalore3

**Comment by ekeeke** [comment]
Added in https://github.com/ekeeke/Genesis-Plus-GX/commit/a2931d161f017a0614426bb01ce33a4d2f250260
