### ISSUE TITLE
PAL Master System Games Forced At 60fps

### ISSUE THREAD

**Issue by pferreira1983** [ekeeke/Genesis-Plus-GX#524]
Is there any possibility of having a toggle for fps? Games automatically run at 60fps however I have encountered an issue where Lucky Dime Caper for Master System is running too fast. It's a PAL game although it was later released in Brazil, then released later on GG worldwide (http://www.hardcoregaming101.net/lucky-dime-caper-starring-donald-duck-the/). Any attempt to change the Vertical Refresh Rate via RetroArch doesn't work and changing region from Auto to PAL threatens to disable Hardcore Mode on Retro Achievements. The Master System version should really be running at 50fps.

This is how it currently runs on most emulators, hear the intro music: https://www.youtube.com/watch?v=1qfujDwXpOQ

Now this is the speed the music should be running at: https://www.youtube.com/watch?v=fH-7Fr8pabI

This seems to be an issue for a few people it seems: https://forums.libretro.com/t/genesis-plux-gx-pal-game-that-runs-too-fast-solved/19150

If there was an FPS marker to change the speed in the emulator and RetroArch it would helpful.

**Comment by pferreira1983** [comment]
I think the issue is more a Retro Achievements problem in relation to the emulator. Changing the region fixes the issue but disables Hardcore Mode which is kind of stupid.

**Comment by ekeeke** [comment]
No idea what 'disables Hardcore Mode' means but yes  that's not a core issue. Some games (that have noticeable issues in NTSC mode) are also forced to PAL when region is set to AUTO so it makes no sense to assume 'AUTO' sets a specific region or that is more legitimate than forced NTSC or PAL

**Comment by pferreira1983** [comment]
Mega Drive PAL games run at the correct speed but for Master System it always defaults to 60fps and Retro Achievements is used to their achievements being obtained at that speed.

**Comment by ekeeke** [comment]
Mega Drive games have a field in ROM header to indicate their supported regions and most games released after a certain date were region-protected according to that field so PAL only games are automatically detected when region is set to AUTO.

There is no such thing for Master System (there is a ROM header in some games but it only distinguishes between Export or Japan systems) and most games that were only released in PAL regions are perfectly compatible with NTSC systems (and for many of them, it could be argued that the music tempo at 60hz sounds better or at least more like what Japanese developers intended) so there is no real reason to force PAL region when AUTO is selected for the majority of Master System games that, for commercial reasons only, were only released in PAL regions. 

As already stated above, if you prefer PAL timings and large borders, all you have to do is force the use of PAL system in system region setting.
