### ISSUE TITLE
Support for .7z?

### ISSUE THREAD

**Issue by carlosgamer23** [ekeeke/Genesis-Plus-GX#525]
Could you add support for .7z?  It would be very useful, even more so for those who want to keep their roms organized and save space... Apart from that this is the only project for Sega classics, which is currently active, it would be good if you don't inherit the "Kega Fusion curse" ", where the project died without seeing the light of .7z support

**Comment by ekeeke** [comment]
If you are talking about the Gamecube/Wii standalone emulator, no, I am not interested.
If you are talking about the libretro/retroarch port, you will have to ask to Retroarch devs as it is a frontend feature

**Comment by carlosgamer23** [comment]
> Se você está falando sobre o emulador autônomo de Gamecube/Wii, não, não estou interessado (o suporte 7z requer um uso adicional significativo de RAM, que é bastante limitado nessas plataformas e melhor usado para outras coisas). Se você está falando sobre a porta libretro/retroarch, você terá que perguntar aos desenvolvedores do Retroarch, pois é um recurso de frontend (embora eu ache que arquivos 7z já sejam suportados). Se você está falando sobre suporte 7z para arquivos de imagem de CD, isso não é possível (veja também a edição #469 ) e você pode usar arquivos chd se quiser economizar espaço de armazenamento.

I use it for sega cd in chd, it's great, I miss something like this for Sega Saturn
