### ISSUE TITLE
BreakThru! (USA) (Proto) for Game Gear doesn't work

### ISSUE THREAD

**Issue by litaniast** [ekeeke/Genesis-Plus-GX#527]
I don't know what the reason, but it doesn't work in Genesis Plus GX. (I tested in libretro. Both win64 and android don't work) Only black screen.
Work fine on other core in libretro like Gearsystem.

**Comment by ekeeke** [comment]
According to [SMS Power release thread](https://www.smspower.org/forums/18638-UnreleasedBreakThruForTheGameGear), this prototype ROM does not work on real hardware either:
`
The version we obtained has a bug preventing is to run on more systems, so we are also provided a patched version (thanks to Calindro for reverse engineering the timing bug and making that patch).`
