### ISSUE TITLE
PCM chip's RAM unaligned access on DMA write

### ISSUE THREAD

**Issue by bnister** [ekeeke/Genesis-Plus-GX#529]
The `ram` field in `pcm_t` is declared as an array of `uint8` with 3 `uint8` fields before
https://github.com/ekeeke/Genesis-Plus-GX/blob/a2931d161f017a0614426bb01ce33a4d2f250260/core/cd_hw/pcm.h#L63
landing on an even address, but it's recast to `uint16 *` in `pcm_ram_dma_w`
https://github.com/ekeeke/Genesis-Plus-GX/blob/a2931d161f017a0614426bb01ce33a4d2f250260/core/cd_hw/pcm.c#L421
causing misaligned fetches and stores. It's not a such big deal for x86 and ARM, but MIPS raises an exception each time this happens, and that's a huge performance hit. Can you maybe align the field? I've just added a dummy `uint8 ram_alignment_filler` before the array to eliminate those.

**Comment by ekeeke** [comment]
I fixed instead CDC to DMA which was confirmed to do byte transfer (not word).
FIxed in https://github.com/ekeeke/Genesis-Plus-GX/commit/8e02a430aaee5415740cb6ea13e9d15d105e4ff9
