### ISSUE TITLE
Update Nuked-OPN2 sound core

### ISSUE THREAD

**Issue by eugene-s-nesdev** [ekeeke/Genesis-Plus-GX#530]
NukeYKT has been actively developing a low-level emulator this year (https://github.com/nukeykt/Nuked-MD, https://github.com/nukeykt/Nuked-MD-FPGA). 
Small improvements have also been made to the accuracy of the Nuked-OPN2 core:
https://github.com/nukeykt/Nuked-OPN2/commits/master

Can you synchronize them with Genesis-Plus-GX main branch please?

**Comment by ekeeke** [comment]
Done in https://github.com/ekeeke/Genesis-Plus-GX/commit/a42843bf6c9b40b4831bd29ca1ee795fe5dcf9bf
