### ISSUE TITLE
Game Gear games has borders while Borders enabled

### ISSUE THREAD

**Issue by MinecraftMario27** [ekeeke/Genesis-Plus-GX#537]
![Asterix and the Great Rescue (U)  ! -240112-174251](https://github.com/ekeeke/Genesis-Plus-GX/assets/137607853/f3f5dbc0-284b-4a4f-90f6-d1a252931f8b)

It's not supposed to show borders on Game Gear games

**Comment by ekeeke** [comment]
This is actually how Game Gear displays through TV adapter.
If you don't like colored borders, you can disable them through emulator settings (assuming you are using libretro core, it is in core settings)
