### ISSUE TITLE
Loading games from HDD says "file too large", i have the bios on the hdd and a bunch of games, all in .bin and .cue format, and when i open a small game, it crashes, any help?

### ISSUE THREAD

**Issue by randomman85** [ekeeke/Genesis-Plus-GX#540]

**Comment by ekeeke** [comment]
I assume you are talking about the Wii (or maybe Gamecube) version ?

 "file too large" means it is not a valid Mega-CD / Sega CD image file or a zipped file larger than max supported size (15MB on Wii, 10MB on Gamecube)

No idea about the crashes or what you exactly mean by "small games" but it's probably also an issue on your side (corrupted HDD or unsupported/invalid ROM file)

**Comment by randomman85** [comment]
i think it is the zipped format

**Comment by ekeeke** [comment]
Indeed, CD games must be unzipped , there is not enough memory to unzip them in RAM on load and real-time unzipping of CD data during emulation is impossible.

If you really need space on your drive or sdcard, you can use CHD compressed disc images, although real-time decompression has an impact on emulation processing time.

**Comment by SirYodaJedi** [comment]
> If you really need space on your drive or sdcard, you can use CHD compressed disc images, although real-time decompression has an impact on emulation processing time.

For games that use Redbook audio (which is most of them?) also more likely to get better space savings than CHD by compressing the audio tracks as lossy OGG Vorbis, leaving the data track uncompressed.
