### ISSUE TITLE
A lot dma fill fails in vdp port access test rom

### ISSUE THREAD

**Issue by SN902** [ekeeke/Genesis-Plus-GX#542]
Before there was only 1-2 fails, now 25
[VDPFIFOTesting.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/14467684/VDPFIFOTesting.zip)

**Comment by ekeeke** [comment]
Indeed, I introduced a stupid regression when attempting to improve DMA fill timings in a recent commit, which totally broke DMA fill (probably also affect many MD games), thanks for the report.

I reverted the change in https://github.com/ekeeke/Genesis-Plus-GX/commit/5af254cd23b0129204dd08419fde3c234de78bb4
and implemented (hopefully) proper DMA fill timing improvement in https://github.com/ekeeke/Genesis-Plus-GX/commit/8c72ba0d4557aab4bbbae05a0c6b1382d23b4e74
