### ISSUE TITLE
[RetroArch] Stuttering while playing Ultimate Mortal Kombat 3

### ISSUE THREAD

**Issue by Plaxaris92** [ekeeke/Genesis-Plus-GX#545]
Hi, i've noticed a lot of stuttering and really bad performance when playing this game (Ultimate Mortal Kombat 3 (USA) through RetroArch on my PC. I'm using the latest RetroArch version (1.17.0) and the latest core version. Also, i've recorded some gameplay to show the issue. If it helps, my setup is a Ryzen 1400 and a GTX 1050. This issue does nos happens when using another core like BlastEm. The recording was made using RetroArch, and the issue persists while not recording. 

https://github.com/ekeeke/Genesis-Plus-GX/assets/67250735/a7a3f61b-e015-48f9-ae9e-a08e4444e916

Edit: I can confirm that this issue is also present in the regular (not Ultimate) version of Mortal Kombat 3.

**Comment by ekeeke** [comment]
Tried it myself and didn't notice any issue (sorry, I suck at this game). 

https://github.com/ekeeke/Genesis-Plus-GX/assets/717091/3250f6c2-f84e-4e38-91ea-ce85d1cabba5

This might be related to some Retroarch specific hacks like CPU overclock or run-ahead if you have these activated.

In any cases, there doesn't seem to be any core issue with this game so there is nothing I can do (retrorach/libretro specific issues should be reported to retroarch/libretro devs)

**Comment by Plaxaris92** [comment]
It was caused by run-ahead, just so people know preemptive frames don't cause any issue, thanks for your help.
