### ISSUE TITLE
[GC] Possible to run the Menu in Interlaced mode?

### ISSUE THREAD

**Issue by LillyGameFox** [ekeeke/Genesis-Plus-GX#546]
So well perhaps not really an issue per say but i was wondering if its possible to hve the Menu running for example in 480i mode? my CRT TV can't handle Progressive in this resolution.

Additional information im using a GCHF Mk2 and an RGB Scart cable with Csync

**Comment by ekeeke** [comment]
The menu already runs by default in interlaced mode (480i) unless a component cable is detected, in which case it is assumed you are using a TV supporting progressive mode (480p) and it uses this video mode (for better video quality).

I have no idea what a "GCHF MK2" is but if this is a kind of third party adapter that convert gamecube component output to rgb signal, it will indeed force 480p output as it is detected as a connected component cable. In that case, you can hold B button on startup which will disable automatic progressive video mode and revert to interlaced video mode even when component cable is detected. You should hear a ring sound on startup which indicate it was changed. Note that you only need to do this once as this will be saved as setting in config file on your sdcard  (it can be reverted by either deleting congig file to restore default settings or by hilding B button again to switch back this setting to default).

**Comment by LillyGameFox** [comment]
oh okay thank you and i misstyped a lillte but the GCHD Mk3 is a GameCube HDMI adapter but also allows for the use of a Wii RGB Scart cable to be used.
