### ISSUE TITLE
[RetroArch/BizHawk] Port 1 controls Players 1/3/4 even if no multitap present in any of ports in Mega Bomberman

### ISSUE THREAD

**Issue by Ceotom** [ekeeke/Genesis-Plus-GX#547]
Connecting Teamplayer/4WayPlay in port 2 doesn't change anything. Inputs from Port 3 and 4 is ignored. This issue makes Battle Mode with more than 2 player unplayable.

https://github.com/ekeeke/Genesis-Plus-GX/assets/36301121/ab2f213d-c644-43cf-b4be-48d513671045

It's occurring in both USA and Europe versions

Version: 
RetroArch 1.17.0 (Core v1.7.4 667158b)
BizHawk 2.9.1
Can be reproduced with default config
Seems to be doesn't occur in other games

**Comment by ekeeke** [comment]
It works fine for me with "Port 1 controls" -> "Device Type" set to "MD Joypad 3 Button + Teamplayer" which emulates Sega TeamPlayer in Mega Drive input port #1 and is what the game expects for multiplayer configuration: each player is controlled independently

https://github.com/ekeeke/Genesis-Plus-GX/assets/717091/687f7e51-3a61-4fdf-8490-81de59347305

With default Controls settings i.e "Port 1 controls" -> "Device Type" and  "Port 2 controls" -> "Device Type" both set to "MD Joypad 3 Button", multitap is not emulated  and, in this case, the game makes player #1 controls the remaining players if you select a batlle with more than 2 players.

**Comment by Ceotom** [comment]
Games except multitap in any port, it just needs to be reset in order to apply changes. My bad.
