### ISSUE TITLE
GX still loads by default the "fixed for emulators" Overdrive demo bin

### ISSUE THREAD

**Issue by sergiobenrocha2** [ekeeke/Genesis-Plus-GX#55]
GX still loads by default that "fixed for emulators" bin even if It's working with the Hardware version.

Tested on RetroArch.

**Comment by ekeeke** [comment]
I don't understand what is your issue. The emulator loads the ROM you ask you to load, it does not load any ROM "by default".

**Comment by sergiobenrocha2** [comment]
Ah, ok, it makes sense, I thought it was picking the gen plus version of the rom, it just get the first it see, thanks.
