### ISSUE TITLE
Toggling graphical layers on and off

### ISSUE THREAD

**Issue by vadosnaprimer** [ekeeke/Genesis-Plus-GX#551]
BG A/B/Window, and sprites. Ideal if custom backdrop color could be set.

It's incredibly useful for making level maps and ripping sprites, and I already have the patch (mostly), but I wonder if it'd be a problem to have it upstream.

**Comment by ekeeke** [comment]
That's not something I am interested in adding to the emulation core as it and I think there already several emulators supporting this that are more suitable as debugging or ripping tool than this emulator.
