### ISSUE TITLE
We need an Android Port

### ISSUE THREAD

**Issue by joelos1111** [ekeeke/Genesis-Plus-GX#557]
Can you please make a port of this Sega Emulator for Android?, we android users are in need of a good quality Sega Megadrive/Genesis Emulator that really emulates not only the games but most specially the sound Chip YM2612 and yours achieve that sweet sound of the 90's home gaming consoles music, i'm sure we'll all appreciate so much if you can start making buids of this program for Android really soon

**Comment by ekeeke** [comment]
Sorry but I know nothing about Android apps developmrnt and have no time or motivatoon for this.
