### ISSUE TITLE
Automatic start occurs in US And EU bios for sega cd (Wii)

### ISSUE THREAD

**Issue by pokemonfan6498** [ekeeke/Genesis-Plus-GX#559]
i was testing mega/sega cd by launching any game i expect it to stay on bios intro until start button is pressed but for some reason it automatically presses idk if it's emulation feature what cannot be disabled or something else because this only occurs on American and European bios but not Japanese bios

**Comment by ekeeke** [comment]
This is how US and PAL BIOS behave on real hardware, they automatically start the game if a game disc is detected.

**Comment by Retrotainment** [comment]
Can you prevent this autostart to occure? I want to watch the funny logo ;)

**Comment by ekeeke** [comment]
Now that I think about it, if you load the BIOS ROM file (like any other ROM file), CD hardware will still be emulated so the BIOS will run as if Mega CD unit is booted with no CD game inserted and the intro should keep looping.

**Comment by Retrotainment** [comment]
How would you do that? I am trying to get this to work on a Sega Mega drive mini, using Hakchi2.

**Comment by ekeeke** [comment]
No idea how you load games in Hakchi2 but, instead of using a game ROM file, you use the BIOS ROM file, simple as that.

**Comment by Retrotainment** [comment]
Ok, I can't get it to work, it only shows a black screen. I have searched the internet and couldn't find an answer to this problem.
