### ISSUE TITLE
additional NTSC filters

### ISSUE THREAD

**Issue by SpelzR2** [ekeeke/Genesis-Plus-GX#563]
Is there any chance to integrate the advanced NTSC-Blargg filters by Cyber (provided in RetroArch) into the emulator and choose them in the core options like the current NTSC filters? Especially the S-Video one has some advantages over the old Blargg filters:
- less shimmering in motion (e.g. Waterfall in Sonic 1)
- less color artifacts (e.g. Delphine Software logo in Flashback)
- less aliasing on sprites (e.g. Palmtrees in Sonic 1)
- better handling of dithering with less artifacts (e.g. Jurassic Park or Phantasy Star 4)
- less halo effects around certain sprites and screen edges

Filters in RetroArch:
![filters](https://github.com/ekeeke/Genesis-Plus-GX/assets/174040074/379ae95b-e31c-48c7-bada-42fe45451465)

Sonic 1 NTSC Blargg (Composite):
![Sonic the Hedgehog (Sonic 1 Bugfix Hack)-240627-232511](https://github.com/ekeeke/Genesis-Plus-GX/assets/174040074/f5f6a995-6717-462c-b97f-2208b065064e)

Sonic 1 NTSC Blargg by Cyber:
![Sonic the Hedgehog (Sonic 1 Bugfix Hack)-240627-232534](https://github.com/ekeeke/Genesis-Plus-GX/assets/174040074/0fef0ba7-2e8d-4a20-8aa8-c33155c5e270)

**Comment by ekeeke** [comment]
I am not qure to understand why do you want to have this filter as a core serying if you can aleady use them though retroarch filter settings ? What difference does it make ?
Anyway, I do not really want to include another NTSC filter, especially a SNES NTSC filter, when the existing MD ones can already be customized and could probably produce the same results as the SNES one with appropriate settings. Looking at your pictures, I hardly see any differences between them, so it's probably only a matter of making custom MD / SMS NTSC filter setup. For the record, this can already be done in the standalone GC/Wii port by setting NTSC filter setting to MANUAL and adjusting the available NTSC settings (sharpness, hue, fringing, etc) as you prefer. This could easily be done too in libretro core settings but you will have to ask libretro devs for that.
