### ISSUE TITLE
Cannot open the internal memory on the CSD-G1M BIOS (Ver 2.11)

### ISSUE THREAD

**Issue by davidj1987** [ekeeke/Genesis-Plus-GX#564]
From what I've tested, games seem to be fine but when you open the "OPTION" menu where you get the CD player controls, it does the ring jingle and freezes with a black screen at that point. I have no idea if it's a faulty dump or an emulation bug..

EDIT: I tried the latest Retroarch core and with just this Sega CD BIOS (no US or EU one) in my system directory this is what I got with the Mega-CD Verificator:
![mcd-verificator (1)-240701-210342](https://github.com/ekeeke/Genesis-Plus-GX/assets/11603709/8f7ab16a-d50b-459c-ad4e-f50b81d09383)

**Comment by davidj1987** [comment]
For fun and it may not help but I tested this BIOS today on a Model 1 Genesis (with language switch), a Model 2 Sega CD using an Everdrive (the original one back in 2011) since it supports BIOS loading and I tested Anett Futatabi. The game played fine but same problem when opening the memory screen - hangs when entering the OPTION menu in the CD player.

Either the hardware of the AIWA CSD-G1M is that different or it's a bad dump.

**Comment by ekeeke** [comment]
Thanks for testing it on real hardware and confirming same problem occurring as in emulator . Closing this as it is unlikely a non-emulated hardware feature considering the debug tracelog did not show any undocumented memory access before the crash and more likely either a bug in original BOOT ROM or a bad ROM dump.
