### ISSUE TITLE
Sonic CD Audio

### ISSUE THREAD

**Issue by JonathanVeg0521** [ekeeke/Genesis-Plus-GX#567]
I know this is not an issue, but you know how in pc emulators, you can have mp3 files in the directory of the Sonic CD iso folder? Is it possible to implement that feature for the wii version of genplus-gx? I am sorry for posting a non-issue.

**Comment by ekeeke** [comment]
only CUE/BIN, ISO/WAV, ISO/OGG and CHD image formats are supported, MP3 files are not supported and I have no plan to add support for this format for several reasons (requires to embedd another decoding library , audio quality loss, etc...)
