### ISSUE TITLE
Add USB-HID controller support

### ISSUE THREAD

**Issue by 25minutes** [ekeeke/Genesis-Plus-GX#569]
[WiiStation](https://github.com/xjsxjs197/WiiSXRX_2022) now supports USB-HID controller, similar to Nintendont. Is it possible to implement the same in Genesis Plus GX?

**Comment by ekeeke** [comment]
Already loggued here: https://github.com/ekeeke/Genesis-Plus-GX/issues/321

I personally don't use usb controllers and maybe only have one to test with (mini md controller) so it's the kind of feature request where I am relyon on others to submit pull requests

Note that there is a pull request in progress but it needs some cleanup and only have support for one specific usb controller.
