### ISSUE TITLE
Sega CD Redump cue noise

### ISSUE THREAD

**Issue by Warriors-Blade** [ekeeke/Genesis-Plus-GX#57]
Quite strange that every other Sega CD emulator have no issue with proper redump images, just Gen Plus GX.

Once a audio track ends there will be a shrill noise before the track loops, here is a redump cue, http://pastebin.com/cwuEPrfw

TOSEC - http://pastebin.com/L7T2c56Z

Here is a isobuster cue - http://pastebin.com/LM5nTQZV

The issue occurs with any redump image.

**Comment by ekeeke** [comment]
You mean it only happens with the multiple BIN redump image, not the ISO/WAV or CUE/BIN you posted ?

It could be an implementation issue with this very specific format (those BIN files for audio tracks are actually same as WAV files, without WAVE header).

I am sure I tested this kind of image way back when I first implemented CUE file parsing but I either didn't test it throughfully or I might have broken something when recently adding support for Audio CD and CD+G.

Thanks for the insight, I will have a look.

**Comment by Warriors-Blade** [comment]
Yes only a split bin image.

I did thorough testing and came to that conclusion .

I love Genesis Plus GX and was surprised when I found this.

Thanks for checking ekeeke.

**Comment by ekeeke** [comment]
Well,  bugs happen... nothing surprising about that.
Also it's not exactly a common image format, so it's easy to get it unnoticed.

**Comment by Warriors-Blade** [comment]
Sorry about any misunderstanding with my last comment.

I was surprised because it runs so well and beats the pants off of kega fusion and I hit a tiny bug and it threw me off track, I thought it was a error on my part at first.

**Comment by ekeeke** [comment]
It was an error with track end time calculation when the pause was included in the audio file and defined in the CUE file (INDEX01 start time different from 00:00:00).

It should be fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/f9e74075ade51588cceb626caf30d22c836e2160
