### ISSUE TITLE
Sprite/tile Viewer?

### ISSUE THREAD

**Issue by jch02140** [ekeeke/Genesis-Plus-GX#60]
Wondering if it is possible to have some kind of Sprite Viewer like MAME emulator does.
When the game is running pressing F4 key will show the palette, tiles/sprites viewer and other thing...

**Comment by ekeeke** [comment]
It would be possible but is specific to a frontend, not emulation core.

I am personally not interested by this kind of feature and do not think libretro frontends either are much oriented to such debugging feature, but there is nothing preventing anyone to build its own debugger around genesis plus gx code.
