### ISSUE TITLE
(libretro) PSG volume Core Option

### ISSUE THREAD

**Issue by KagerouShinobi** [ekeeke/Genesis-Plus-GX#65]
I can't find any option within Retroarch to individually modify the volume of the PSG when playing Megadrive games. It seems to me that the PSG is much louder on Super Street Fighter II than it is on my Model 1 MD.

Is there any way to change this? Otherwise it might be a good idea to introduce individual volume for the PSG as a Core Option.

**Comment by ekeeke** [comment]
The PSG volume ratio was initially tested against my Model 2 MD with a few different games (not that one but it shouldn't matter, sound hardware is common to every games) then against my Model 1 MD but the differences weren't that much noticeable from what I remember.

That option exists in standalone Genesis Plus GX, however the way core settings are implemented in libretro does not make it suitable for fine volume control.
