### ISSUE TITLE
32X Support

### ISSUE THREAD

**Issue by Papermanzero** [ekeeke/Genesis-Plus-GX#66]
Could 32X support be added? This would fully complete the emulator.

Edit:
Sorry have not read the closed issues. Another request was already closed.
So this can be closed as well.
Btw could picodrive or gens be used as reference, for 32X emulation?

**Comment by Oggom** [comment]
This has previously been discussed here https://code.google.com/p/genplus-gx/issues/detail?id=65

32X emulation is just too slow to be portable and run at full-speed on a Wii at the same time

**Comment by Papermanzero** [comment]
For the Wii it is impossible, without doubt.
But the question is concerning the PC via libretro.

**Comment by ekeeke** [comment]
See issue #64 here or the one above on googlecode, I already stated my mind and don't feel like discussing the same thing again and again.

**Comment by Papermanzero** [comment]
Can the effort of these guys be ported?

http://www.1emulation.com/forums/topic/35435-neogensplusgx-v1b02-public-beta-pier-solar-rom-and-cd-new-update/

**Comment by ekeeke** [comment]
No, because the "effort" was just copying Genesis Plus GX code into their old XBOX Gens port to have 2 emulators in one: basically they just switch between Genesis Plus GX and their old emulator depending on the ROM type so they still use old Gens code for 32x and nothing has been added or modified in Genesis Plus GX core.

**Comment by Papermanzero** [comment]
I see. Thanks for the answer :)

**Comment by Papermanzero** [comment]
@ekeeke 
Just out of curiosity, I am looking what has to be done to add 32x support.
In general the 32x "only" persists of 2x SH2 CPUs (Master-Slave), a custom Sega 32X VDP processor for graphics, 256 KB RAM and 256 KB VRAM (128KB for each framebuffer).

The  SH2 CPU could be used from mame:
https://github.com/MisterTea/MAMEHub/blob/master/Sources/Emulator/src/emu/cpu/sh2/sh2.c
https://github.com/MisterTea/MAMEHub/blob/master/Sources/Emulator/src/emu/cpu/sh2/sh2.h

Therefore the only missing part is the communication (architecture) between the system components (memory, genesis CPU and audio). The benefit of Genesis Plus GX is, that the Genesis hardware including the Sega CD hardware are pretty accurate. Consequently the remaining parts are the memory and the communication between the SH2 CPUs

**Comment by 60fpshacksrock** [comment]
I know this is an old post but, I thought I should let you and others who see this post know that picodrive is now on Wii via retroarch and 32x support is there as well.

**Comment by Arnold101knight** [comment]
wii impossible you say? not true lol there is already a 32emu working fine

**Comment by birdybro** [comment]
Please don't necropost something just to argue and pester a developer who spends their time working on something for the community for free. It's very disrespectful and pointless.
