### ISSUE TITLE
OGG file will not play.

### ISSUE THREAD

**Issue by Allanbuzzy** [ekeeke/Genesis-Plus-GX#68]
I was hoping for my OGG file to run. It basically is the main theme of the Sega Channel, because my games were actually on SC. But when I put the OGG file into my SD card, it won't play when I open up Genesis Plus GX. I've tried renaming the file to BG_music.ogg but that didn't work either. Whats the issue here? The file is only 2,124 KB.

**Comment by ekeeke** [comment]
It should be named EXACTLY "Bg_music.ogg" and placed on SD card in /genplus directory (same directory where config.ini is created).

Any other filename or file location obviously won't work so there is no point trying anything else that what is mentionned in README.
