### ISSUE TITLE
SpriteMaskingTestRom doesn't work with bios enabled

### ISSUE THREAD

**Issue by sergiobenrocha2** [ekeeke/Genesis-Plus-GX#69]
SpriteMaskingTestRom is not working if "System bootrom" ON in libretro.

**Comment by ekeeke** [comment]
Yes, this test ROM only works on Model 1 console without TMSS license screen so this is accurate behavior. More precisely, it does not read the version register  and does not write "SEGA" to security register when running on later models, which causes a lock-out on real hardware just after the license screen.

**Comment by sergiobenrocha2** [comment]
Ok, thanks.
