### ISSUE TITLE
Classic Controller

### ISSUE THREAD

**Issue by QuantumVirus** [ekeeke/Genesis-Plus-GX#72]
I got an off brand classic controller and it works fine in everything else except this emulator.  I don't know what the problem is but in the menu it automatically presses buttons and in game it moves the left control stick to the bottom left.

**Comment by ekeeke** [comment]
What version are you using ? Alternatievly try latest 1.7.4 or 1.7.5 release candidate that are available here: https://bitbucket.org/eke/genesis-plus-gx/downloads

Also try deleting config.ini file in genplus directory and see if that helps.

**Comment by QuantumVirus** [comment]
I'm currently using the version that is on the homebrew browser.

**Comment by QuantumVirus** [comment]
I tried 1.7.5 and it fixed the problem.  Thanks.
