### ISSUE TITLE
type of gzopen

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [ekeeke/Genesis-Plus-GX#73]
Hi, compiling sdl version fails in sdl/fileio.c.
The return type of gzopen() should be gzFile, not gzFile*.
Changing line 124 from
    gzFile *gd = gzopen(filename, "rb");
to
    gzFile gd = gzopen(filename, "rb");
seems OK.
Cheers.

**Comment by ekeeke** [comment]
Indeed, for some unknown reason, both return type compile (and works) fine in zlib 1.2.3 which I am using here for testing but not on the later version of zlib.

Thanks for the notice, I will commit the fix when I got some time, although the win32/sdl port is not really maintained and there should not really be considered as good code example. Its only purpose is to show how to initialize and interface with the emulator core.

**Comment by ekeeke** [comment]
Fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/c0e7e595e4dabd0d7edb7b47a5fc461a8a92967d
