### ISSUE TITLE
OGG files not playing music correctly on main menu

### ISSUE THREAD

**Issue by hossbags2** [ekeeke/Genesis-Plus-GX#74]
I have tried a few OGG files that I have used in the past for the main menu and the music goes low and is cutting out.

**Comment by hossbags2** [comment]
I am using the latest build 2/28/2016

**Comment by ekeeke** [comment]
Nothing has been changed in regard to OGG player so I don't see why it wouldn't work correctly anymore. What was the latest version you were using that was playing them fine? You could also upload one of the OGG files that have issue now so I could check it.

**Comment by ekeeke** [comment]
Tested latest build with an OGG file and it worked fine, so it's an issue on your end.
Try adjusting bgm volume in menu settings or deleting config.ini to restore default (100%) volume...
