### ISSUE TITLE
Sprite deflickering not working for 8 bits systems like Master System - Game Gear - SG 1000

### ISSUE THREAD

**Issue by FeRchuLeS** [ekeeke/Genesis-Plus-GX#75]
Hi, the video deflickering option is not working, set to "auto" or "no" is the same for 8 bits consoles on the other hand it is working fine with Sega Genesis games.

**Comment by ekeeke** [comment]
It's a Wii-specific **hardware filter** to reduce the flickering of interlaced video output, it has absolutely nothing to do with sprite flickering on 8-bit system which is a limitation of the real hardware and is accurately emulated.

There is no plan to remove that limitation as it adds overhead in the sprite processing emulation code and is simply inaccurate.

**Comment by FeRchuLeS** [comment]
Sorry, I wasnt aware that flickering option is not related to sprite flickering
