### ISSUE TITLE
checksum autofix, future addition

### ISSUE THREAD

**Issue by 47iscool** [ekeeke/Genesis-Plus-GX#78]
Was wanting to know if you had any plans on implementing this feature.

**Comment by ekeeke** [comment]
No, this is only needed for a few ROM hacks and there are already plenty of programs that already do that for you, better fix the checksum of your ROM hacks once for all than have the emulator do it everytime on the fly.

http://www.romhacking.net/utilities/342/
http://mi.tsdx.net.ve/genSuite/gs_en.htm
http://www.hacking-cult.org/download/download/FixCheckSum.rar

**Comment by 47iscool** [comment]
Alrighty then.

Thanks for the links eke.
