### ISSUE TITLE
Retroarch GP-GX Core on Apple crashing

### ISSUE THREAD

**Issue by Cepheidsong** [ekeeke/Genesis-Plus-GX#82]
Hope this is the right place to report this- for the past month using Retroarch's Genesis Plus GX Core, it's been crashing on loadup (either with any Genesis titles or Sega CD titles I've tried).  I saw it was last updated on April 13th, but haven't had any fix on it.

I've tried a clean install too, but to no avail.  Same files worked if loaded with PicoDrive core

Loading Retroarch using iPhone 6 loaded from Cydia repo.  Everything else works just fine, just this one core does not.

On trying to load the core without any game, the core doesn't even load at all, just continues to say (No Core) so I wonder if it's just a file issue.

**Comment by ekeeke** [comment]
This should reported to whoever maintain the iOS port of RetroArch as this is not a core issue and likely not a libretro port issue either. Maybe something related to libretro Makefile, or some limitation of iOS port that somehow has an impact on the emulator, I dont know, I am not familiar with RetroArch ports, I only maintain generic libretro layer.
