### ISSUE TITLE
Debugging support

### ISSUE THREAD

**Issue by lab313ru** [ekeeke/Genesis-Plus-GX#85]
Is there any chance to add some debugger functionality?
I mean steps, breakpoints for vram/memory reading, etc.

**Comment by ekeeke** [comment]
That's something that must be handled by the frontend and I only maintain the Wii frontend, which I don't think is what you want to use for debugging.

**Comment by vadosnaprimer** [comment]
Just having a few hooks in the core would already be helpful. You won't need to support them in your own frontend just because it's not needed there. But in forks, it would make it very easy to keep the core up-to-date with upstream, and making use of those hooks would be entirely the job of the fork frontend. 

The hooks are lightweight and non-invasive, might be locked under preprocessor definitions if needed.

**Comment by lab313ru** [comment]
Absolutely agree with feos.
Debugging features (without gui, just steps, breakpoints, etc.) don't require everyday maintenance. Once implemented it will work all time.

**Comment by vadosnaprimer** [comment]
In bizhawk, all we have to add is callbacks on exec/read/write that the client then attaches to. Execution callback alone allows the client to do disassembling, trace-logging, step into and step over, and of course regular breakpoints. None of that has to be in the core, only the callback itself.

**Comment by ekeeke** [comment]
That's not something I am interested in implementing or that I need myself so it's up to people interested to come up with a solution that corresponds to their needs and submit it.

If the proposed solution keeps the codebase clean enough and if added hooks indeed are not too much invasive and do not restrict default emulator use, I do not see any problem with merging it.

**Comment by vadosnaprimer** [comment]
@ekeeke just to be sure, do you ever pull from musashi/mame? Original hooking code that's been there feels a bit messy, so I wonder if I should reimplement this from scratch and make it cleaner than it is in the original codebase.

**Comment by ekeeke** [comment]
What original hooking code? If you are talking about existing callbacks in Genesis Plus GX musashi core then I would prefer keeping them intact and only have a few additional (and optional) callback for debug that make use of existing functions if needed and existing data structure, without changing anything (ideally it's only required in a few spots like after instruction decoding for breakpoints and memory write handlers for real-time watchpoints, maybe also in exceptions processing I don't really know).

And no, I never kept the core updated with MAME codebase, this is based on an old version before they totally rewrote it (and added many MAME-specific macros and function prototypes, which now makes using or backporting it in another project quite difficult ) with many fixes added when improving megadrive emulation accuracy and compatibility, as well as a few stuff cleaned and optimized...

**Comment by vadosnaprimer** [comment]
I mean the system that was disabled here https://github.com/ekeeke/Genesis-Plus-GX/commit/62f1204476c788e51d09e62d168fad14fd39e075#diff-f1dc52f973c8d395f398593c5f04df7dL495 
And yes, it does indeed look too messy, I won't be restoring it.

**Comment by ekeeke** [comment]
Many unused stuff were removed in this commit (including support for non-MC68000 stuff) and I think only a few things were actually useful for debugging. It could for example limited to getting back m68ki_instr_hook definition and callbacks, there is no need to get back the whole hook system.
