### ISSUE TITLE
Paddle control is not recognized

### ISSUE THREAD

**Issue by FeRcHuLeS** [ekeeke/Genesis-Plus-GX#88]
Paddle Control - Wii
These games aren't recognized by the emulator even if you choose the paddle control in the options menu: Outrun ([!]), Outrun 3D, Super Racing.

Paddle Control - PC
Everything works fine.

**Comment by ekeeke** [comment]
There was a problem with peripheral auto-detection for SMS games that are in the database, gamepad was always forced for these games. This has been fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/c01c6404574480a00efcc0911f8ff2a4ca06d725

**Comment by FeRcHuLeS** [comment]
As you said the problem is fixed now, thanks for making a supporting the best of all times and the only emulator that supports many peripherals for sega's 8 -16 bits systems as today.
