### ISSUE TITLE
[libretro] PAL Mega CD CD-audio sync/timing problem

### ISSUE THREAD

**Issue by Silanda** [ekeeke/Genesis-Plus-GX#89]
Playing the PAL version of Snatcher, with an image created from my original CD, it loses synchronization between the CD-audio played over the intro and the intro graphics. The audio runs ahead of the on screen animations and, while I'm uncertain if this is the case, the sync seems to get increasingly out the longer the intro plays. I suspect that the sync problem will manifest in any part of the game where CD-audio plays over a cutscene. 

I created a bin/cue image with Imgburn, and an iso/wav/cue image using Turborip, and both play with exactly the same issue. I also listed this as for libretro as I have only tested this through Retroarch. FWIW, neither Picodrive, through Retroarch, or Kega Fusion exhibit this issue with the images I made.

**Comment by Silanda** [comment]
Oh, and this might be something or nothing, but I've noticed that if the frame throttle maximum run speed is set to 1.0, the framerate appears to be pegged at 49.7fps rather than 50.

**Comment by ekeeke** [comment]
I tried the PAL version on standalone Genesis Plus GX (SDL test version and Wii version) and I hardly noticed any sync issue during that intro. Maybe the few sound effects that are part of the audio are less perfectly synced with the corresponding graphics animation than with NTSC-U version of the game but it's very subtle, not what I would call complete desync. Is that what you are referring to or is there something else I should be looking to?

If so, it could be related to the number of cycles executed per line for the Sub-CPU, which should be a little different in PAL systems vs NTSC but was currently fixed to a single common value in the emulator. Indeed, changing that value seems to make the sound effects better synchronized with the graphics animation in the intro. Here is a modified win32 .dll if you want to test and report back (rename the .txt file to .dll and copy it back in your retroarch /libretro directory).

[genesis_plus_gx_libretro.txt](https://github.com/ekeeke/Genesis-Plus-GX/files/324410/genesis_plus_gx_libretro.txt)

**Comment by Silanda** [comment]
For me personally, by the time the intro reaches the part with the Snatcher hand moving its fingers (with accompanying SFX) the sound seems to be a second or more ahead of the animation, and I figure that it is going to look pretty ugly in some of the scenes that sync dialogue to lip movements. 

I've only tested the intro, but your build seems to fix it. Thanks!

**Comment by ekeeke** [comment]
This test build had timings hard-coded for PAL, this has been now properly be fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/ece23d007e44ed8d9a7281ef46e062a722760a9e

**Comment by Silanda** [comment]
Thanks for that! I'd compiled 64-bit builds with the hard-coded fix applied to use specifically with PAL games, but a proper fix is much better. Awesome!
