### ISSUE TITLE
Sonic 3 choppy sound

### ISSUE THREAD

**Issue by dredd90** [ekeeke/Genesis-Plus-GX#95]
The game is running flawlessly except for the sound which is fairly choppy. Keep up the good work! I'll add more posts as I test more games.

**Comment by ekeeke** [comment]
What version of the emulator are you using?

I don't notice any sound emulation issue in that game (using GameCube/Wii
version), you will have to be more descriptive when reporting issues.

**Comment by dredd90** [comment]
My apologies, I just realized this is a multi platform emulator. I'm using the Playstation Vita build.

**Comment by ekeeke** [comment]
There is no choppy sound in other ports so it's likely an issue specific to that port.
I am not maintaining the PS Vita port and won't be able to fix anything related specifically to it, you will have to contact the developer who did the port (https://github.com/frangarcj)
