### ISSUE TITLE
[feature] save scd_*.brm in the save dir instead system dir

### ISSUE THREAD

**Issue by sergiobenrocha2** [ekeeke/Genesis-Plus-GX#96]
Sega CD (scd_*.brm and cart.brm) saves goes to system dir when it's configured. Is it possible to change the brm files place to the save dir? It should be the save dir or the rom dir when it's not configured.

**Comment by sergiobenrocha2** [comment]
btw, why does it create a srm file for each Sega CD game in the save dir? I have a "Sonic The Hedgehog CD (1993)(Sega)(NTSC)(Jp)(en)[!].srm" for example.

**Comment by ekeeke** [comment]
I don't think libretro cores have to the save dir, hence why the system dir (or the roms dir if it is not configured) is being used.

Similarly, .srm filrd

**Comment by sergiobenrocha2** [comment]
It's user data, why it should be at System/BIOS Dir ?

Besides, it helps to have a consistent environment with all saves in only one place (it helps to sync between 2 different machines with cloud services, for example).

Take a look at the PR please :D

**Comment by ekeeke** [comment]
Like I said, this is how it was done initially in libretro port and I'm not really familiar with libretro so I didn't know save directory was accessible. Off course, it makes more sense to store save files in save directory, thanks for the pull request, it has now been merged.

**Comment by sergiobenrocha2** [comment]
Thanks ekeeke!!!
