### ISSUE TITLE
Special:Rewind not working

### ISSUE THREAD

**Issue by arutemun** [ekeeke/Genesis-Plus-GX#98]
When you press the button, only sound disappears, no rewind

**Comment by ekeeke** [comment]
And I guess it's referring to PSVita port again?

As already said, I am not the guy responsible of this port so I can not deal with frontend issues you have with it.

@frangarcj: please add an issue page on your fork repository as I feel I'm going to receive plenty issues report for this and I have better things to do than repeating the same thing and closing invalid issues, thank you ;-)

**Comment by frangarcj** [comment]
@ekeeke sorry but I didn't noticed that there were no issues page on the fork.
